### ISSUE TITLE
On windows 10, syncplay crashes with 'syncplay stopped working' at pressing 'safe config and play'

### ISSUE THREAD

**Issue by mokrates** [Syncplay/syncplay#100]

**Comment by Uriziel** [comment]
works for me

**Comment by blaenk** [comment]
I can confirm it works for me and my friends. What version of syncplay are
you using and what version of what player?

**Comment by Et0h** [comment]
Also, are you using any security/anti-virus software which could be causing an issue such as Avast and its Sandbox feature? Does it crash if you are run Syncplay without storing config?

**Comment by Et0h** [comment]
Is the issue resolved in Syncplay 1.4.0 RC1? http://syncplay.pl/syncplay-1-4-0/

**Comment by Et0h** [comment]
If you were using VLC this might be due to running an older version. In 1.4.0 RC2 Syncplay should now tell you to run a new version rather than trying to run anyway and risking a crash.
