### ISSUE TITLE
Debian (stable, amd64), syncplayClient has a problem with german umlauts in filenames

### ISSUE THREAD

**Issue by mokrates** [Syncplay/syncplay#101]

**Comment by Et0h** [comment]
Does this problem also occur in the latest version of the sharedplaylist branch?

If so, please provide more details regarding how to replicate the issue and what problem it creates.

**Comment by Et0h** [comment]
This problem may occur if you are using a relative path config file in a folder with a UTF-8 character. Does d20c20aae415ab889eac545a6b4905e627f6876d resolve your issue?

**Comment by Et0h** [comment]
This issue should be fixed by https://github.com/Syncplay/syncplay/commit/d20c20aae415ab889eac545a6b4905e627f6876d - let us know if it isn't.
