### ISSUE TITLE
vlc cannot find syncplay.lua thought its there and up to date

### ISSUE THREAD

**Issue by abhsag24** [Syncplay/syncplay#103]
i'm on fedora 23
and have a syncplay.lua at `/lib/vlc/lua/intf/syncplay.lua` 
it was already there and i also replaced it with  https://raw.githubusercontent.com/Uriziel/syncplay/master/resources/lua/intf/syncplay.lua
but i still get the error: `VLC has repored that the syncplay.lua....`

**Comment by Et0h** [comment]
Some questions to help us get to the bottom of it...
1) Does putting the file in /usr/local/lib/vlc/lua/intf/ work?
2) Are there any other files in /lib/vlc/lua/intf/?
3) What directory is http.luac or cli.luac or telnet.luac located in? Does putting syncplay.lua in that folder work?
4) What version of VLC and Syncplay are you using?

**Comment by Et0h** [comment]
Oh, and also try putting it in ~/.local/share/vlc/lua/intf/ and let me know if that works.

**Comment by abhsag24** [comment]
so following point 3 i found telnet.luac at `/usr/lib64/vlc/lua/intf/`  where i pasted syncplay.lua and it works now :) my syncplay version was 1.34 -RC2 and vlc version was 2.2.4

**Comment by Et0h** [comment]
Thanks for the update. It looks like https://github.com/Syncplay/syncplay/blob/master/GNUmakefile will need to be updated to work properly on systems where the relevant lib directory is /lib64/

**Comment by Et0h** [comment]
Not fixed yet, but syncplay.lua is now updated to explain that sometimes you need to use /lib64/ (76d63c94067320a3c0dee4269abea4a43e9cd232)

**Comment by daniel-123** [comment]
I've commited change to Makefile that should ensure syncplay.lua is always seen by VLC.

**Comment by JBeckwith** [comment]
I would just like to say that I recently installed syncplay on Ubuntu 20.04 using the snap channel provided and this issue occurred - VLC was installed beforehand, and yet this error was thrown.

**Comment by daniel-123** [comment]
Problem with snap packages seems to be unrelated to the one handled in this issue.

It's now followed in #302 and #301. If you have some insights about what exactly might be going wrong please share your investigation there.

**Comment by daniel-123** [comment]
@JBeckwith: Problem with snap packages seems to be unrelated to the one handled in this issue.

It's now followed in #302 and #301. If you have some insights about what exactly might be going wrong please share your investigation there.

**Comment by aboode95** [comment]
> I would just like to say that I recently installed syncplay on Ubuntu 20.04 using the snap channel provided and this issue occurred - VLC was installed beforehand, and yet this error was thrown.

@JBeckwith Can you let us know what version of syncplay and vlc you are using?

**Comment by JBeckwith** [comment]
I've been using Syncplay version 1.6.4, VLC media player 3.0.9.2.
