### ISSUE TITLE
Insufficient MPC-HC version with CCCP

### ISSUE THREAD

**Issue by Gstayton** [Syncplay/syncplay#105]
The version from the CCCP download meets the errors required version number, but still triggers the 'insufficient version' error

![image](https://cloud.githubusercontent.com/assets/1830866/17009216/4cd35c18-4ead-11e6-9a3a-9e48da570840.png)

Despite being a few minor versions behind (1.7.4 vs 1.7.10), it still meets the errors required minimum version.

Confirmed that the application indeed does work with the latest MPC-HC off the main site 

![image](https://cloud.githubusercontent.com/assets/1830866/17009241/88aeb28c-4ead-11e6-9e05-8b4c5128c758.png)

Working for now, but would like some insight as to why I can't use the CCCP variant, or if it is indeed unintended, to draw some light to the issue.

**Comment by Et0h** [comment]
My guess is that the CCCP build of MPC-HC is a branch that, as with the
MPC-BE fork, does not support the latest version of the MPC-HC API which
means it does not even respond to the version check (and would not support
API features that Syncplay needs).
