### ISSUE TITLE
OSX: time value error

### ISSUE THREAD

**Issue by kzsombor13** [Syncplay/syncplay#112]
Here is the full log: Last login: Tue Aug 23 21:16:46 on ttys000
Csak-egy-MacBook-Air:~ Zsemle$ source activate syncplay
(syncplay) Csak-egy-MacBook-Air:~ Zsemle$ cd syncplay
(syncplay) Csak-egy-MacBook-Air:syncplay Zsemle$ ./syncplayClient.py
Traceback (most recent call last):
  File "/Users/Zsemle/syncplay/syncplay/ui/GuiConfiguration.py", line 369, in _saveDataAndLeave
    self.loadLastUpdateCheckDate()
  File "/Users/Zsemle/syncplay/syncplay/ui/GuiConfiguration.py", line 281, in loadLastUpdateCheckDate
    if self.lastCheckedForUpdates > datetime.strptime(self.config["lastCheckedForUpdates"], "%Y-%m-%d %H:%M:%S.%f"):
  File "/Users/Zsemle/miniconda2/envs/syncplay/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '@Variant(' does not match format '%Y-%m-%d %H:%M:%S.%f'

PLEASE HELP ME! I already tried with python 2.7 and with 3.5 but nothing changed.

**Comment by Et0h** [comment]
Does it work fine if you run the Windows version via Wine?

**Comment by kzsombor13** [comment]
I tried it on my PC and everything works fine but I would like to use it on my mac as well.

**Comment by Et0h** [comment]
How about using the Mac with a Windows application emulator such as Wine for Mac?

**Comment by kzsombor13** [comment]
In wineskin it crashes and I installed the vlc tool but in the simple wine i can't install that any other solution?

**Comment by Et0h** [comment]
I don't use OSX so can't be of much more assistance. If you can find an active Python-OSX dev then please ask them to help resolve this issue.

**Comment by alby128** [comment]
I think I ran into the same issue, see #116 for further details.

**Comment by alby128** [comment]
This issue can be closed, since it is fixed by the patch applied on qt4 by cartr.

**Comment by Et0h** [comment]
Closed as the issue should be resolved by https://github.com/Syncplay/syncplay/pull/143 and http://www.albertosottile.it/syncplay/2017/09/08/install-syncplay-on-macos-10-8/
