### ISSUE TITLE
[Feature request] custom playback speed

### ISSUE THREAD

**Issue by bitingsock** [Syncplay/syncplay#115]
Usually when my group of friends watch movies we watch at 1.1-1.2X speed. This feature would be very desirable for us for syncplay to support. It seems that if everyone sets the speed at the same time it keeps us sync until it seeking or pausing resets it; but have a synced setting would be best.

**Comment by Et0h** [comment]
http://syncplay.pl/guide/trouble/ notes that: "Manually setting the playback rate may cause problems. Syncplay generally assumes a playback rate of 1.0 and in some instances sets the playback rate to help get everyone more in sync."

Not sure how much work it would take for the clients and servers to support varying playback speeds, but it'd certainly be non-trivial.

**Comment by winneon** [comment]
I know that MPC-HC and VLC both support playback speeds in their own form, and they act the same. I'm currently learning mpv as my main player, so I do not know if mpv supports the same thing, but if mpv and mplayer supports the same concept, it shouldn't be difficult to implement this, correct?

**Comment by Et0h** [comment]
The Syncplay client/server both assume things move forwards 1 second per second and that is an assumption made at various points in the code (e.g. using the difference in seconds to calculate current position if the player hasn't responded), so in addition to the protocol changes there would need to be some algorithm changes too (plus code to monitor speed to detect changes). Furthermore, if one wanted the 'slowdown on desync' feature at the same time as playback-syncing one has to be able to distinguish between them and potentially apply one to the other... eep!

**Comment by daniel-123** [comment]
@winneon I agree with other guys about this being a feature not really being worthwhile - it would take considerable effort to properly implement and vast majority of users would never use it. On the other hand Syncplay already can kinda support the feature if setup in particular way:

- "Fast-forward if lagging behind" option in Sync tab turned off on all clients
- All clients have exactly the same playback rate - as long as it isn't something crazy high/low. It can be for example passed as player argument (--speed=1.2 in mpv for example).

I have tested it only with mpv, which is by far most robust out of supported players. Dunno whether others will work.

**Comment by Et0h** [comment]
Have added it as an idea at http://syncplay.pl/about/ideas/ and anyone is free to implement it. If it were implemented, it would need to be done properly so it would work on a per-room basis and give a warning if someone has a client/player that doesn't support it.
