### ISSUE TITLE
Syncplay servers down cant get past "Connection with server failed"

### ISSUE THREAD

**Issue by MrCodZilla** [Syncplay/syncplay#119]
Me and my friend were going to watch the anime "Bleach" we binge watched like 24 episodes today but when it came to night time we couldn't connect to syncplay servers.
Also i checked most popular "is it down or just me sites" and it clearly says that syncplay is down on their end so im not sure when its coming back up.

Any help?

**Comment by Et0h** [comment]
Our DNS expired, but it should all be fine again now. Thanks for letting us know, and sorry for any inconvenience caused. If you ever want to run your own Syncplay server then instructions are available at http://syncplay.pl/guide/server/
