### ISSUE TITLE
no way to manually reconnect

### ISSUE THREAD

**Issue by alok0** [Syncplay/syncplay#122]
the automatic reconnect aborts after a certain amount of time, this seems like a flaw to me.

but on top of that there no way to manually reconnect.

**Comment by Et0h** [comment]
Uriziel did the original reconnect code so I'm not very familiar with it, and Uriziel lasted worked on it in 2013. As such, it might be difficult to say how easy it would be to change things without risking breaking things. How frequently is being disconnected for long periods an issue for you?

**Comment by alok0** [comment]
This is not normally an issue, but the easy fix would be to never give up reconnecting.

**Comment by Et0h** [comment]
Yes, one way to do that would be to remove the RECONNECT_RETRIES constant and the check on self._timesTried in clientConnectionLost and then limit the maximum retry interval increase on the callLater

**Comment by Et0h** [comment]
Alternatively, number of RECONNECT_RETRIES could just be set very high alongside the gap between attempts being limited. Does anyone have any good reason to prevent too may reconnection attempts?

**Comment by Et0h** [comment]
Okay, that update should do it...

**Comment by Acidic9** [comment]
This feature would be nice because sometimes I am mid way through a video, and I close my laptop overnight, and when I want to continue again I have to restart SyncPlay

**Comment by Et0h** [comment]
> This feature would be nice because sometimes I am mid way through a video, and I close my laptop overnight, and when I want to continue again I have to restart SyncPlay

This is something which should be addressed on private servers with room permeance/persistence enabled when https://github.com/Syncplay/syncplay/pull/434 gets integrated.
