### ISSUE TITLE
vlc <3.0 broken on linux

### ISSUE THREAD

**Issue by blaenk** [Syncplay/syncplay#125]
If anyone else is running vlc <3.0 on linux with no problems on RC4 or later, please let us know.

It seems like 401e08a7e08a2da5eaa27b827ac4a64f555a5ab0 was an effort to achieve vlc 3 compatibility but it seems to have been at the expense of vlc 2.x. Particularly in `lineReceived()` of players/vlc.py, having `constants.VLC_LISTEN_FOR_STDOUT` not `True` causes syncplay to give a "Failed to connect to VLC" error. When I set that constant to `True` everything seems to work perfectly.

**Comment by Et0h** [comment]
I'm hoping the recent commits to the 1.4.x Syncplay branch will resolve the various VLC issues, but I've only tested it on Windows. If Linux users can test the Syncplay 1.4.x branch GIT HEAD with VLC 2.2.4 and VLC 3.x and let me know how it goes that'd be useful.

**Comment by blaenk** [comment]
Confirmed working on linux with vlc 2.x.

**Comment by Et0h** [comment]
Thanks for the confirmation
