### ISSUE TITLE
Cant connect to VLC (Ubuntu 16.04)

### ISSUE THREAD

**Issue by gadd1** [Syncplay/syncplay#129]
When running syncplayClient.py and trying to open connection I get an error "Failed to connect to VLC" although VLC open and in the plugin manager I can see the synplay lua
Followed instructions on plugin location (tried several places - VLC sees it only under .local)

Syncplay v 1.4-RC4
 ~/.local/share/vlc/lua/intf/synplay.lua - v0.3.3

 cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"

python --version
Python 2.7.12

vlc --version
VLC media player 2.2.2 Weatherwax (revision 2.2.2-0-g6259d80)
VLC version 2.2.4 Weatherwax (2.2.3-37-g888b7e89)
Compiled by buildd on lgw01-57.buildd (Sep 24 2016 12:29:53)
Compiler: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2)

./syncplayClient.py
error: uncaptured python exception, closing channel <__Listener(VLC Listener, started daemon 140698292131584)> (<class 'socket.error'>:[Errno 111] Connection refused [/usr/lib/python2.7/asyncore.py|read|83] [/usr/lib/python2.7/asyncore.py|handle_read_event|446] [/usr/lib/python2.7/asyncore.py|handle_connect_event|454])

On windows 10 same VLC and Syncplay versions it work OK
I can even see the UB16.4 host connect and disconnect from the server 

appreciate your help

**Comment by Et0h** [comment]
Syncplay.lua needs to be in the same folder as http.luac. This should not
be an issue on Git head of master branch or 1.4.x branches which should
both be more stable than the RC4 labelled release.

**Comment by Et0h** [comment]
Your issue may be #125 which is resolved in the latest Git heads in master
or 1.4.x.
