### ISSUE TITLE
Linux ~> Decode Error

### ISSUE THREAD

**Issue by DarkNikGr** [Syncplay/syncplay#131]
Hello i get this error after push button run syncplay

my distro is Neon KDE

`Traceback (most recent call last):
  File "/usr/bin/syncplay", line 19, in <module>
    SyncplayClientManager().run()
  File "/usr/lib/syncplay/syncplay/clientManager.py", line 12, in run
    interface.addClient(syncplayClient)
  File "/usr/lib/syncplay/syncplay/ui/gui.py", line 323, in addClient
    self.showErrorMessage("Failed to load some settings.")
  File "/usr/lib/syncplay/syncplay/ui/gui.py", line 663, in showErrorMessage
    self.newMessage(time.strftime(constants.UI_TIME_FORMAT, time.localtime()) + message + u"<br />")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 10: ordinal not in range(128)
[1]    22560 segmentation fault  syncplay
`

Can anyone help me?

**Comment by Et0h** [comment]
What is your system locale? Does it work fine in --no-gui mode?

**Comment by Et0h** [comment]
Change line 663 of /usr/lib/syncplay/syncplay/ui/gui.py from:

>        self.newMessage(time.strftime(constants.UI_TIME_FORMAT, time.localtime()) + message + u"<br />")

To:

>        self.newMessage(time.strftime(constants.UI_TIME_FORMAT, time.localtime()).decode('utf-8') + message + u"<br />")

And let me know what happens.

**Comment by DarkNikGr** [comment]
ok thnx its work but add decode and on line 339 on same file.

**Comment by Et0h** [comment]
Is eb22f5d1c80fa6a06f29a47735a222f92305d04a an appropriate fix?
