### ISSUE TITLE
Client doesn't detect File loaded when using Mpv with --msg-module flag

### ISSUE THREAD

**Issue by Felhamed** [Syncplay/syncplay#134]
Syncplay client version : 1.4.0 OS: 4.10.11-1-Arch Linux
Syncplay Debug logs: https://pastebin.com/raw/Qn9gUA3e

Description:
When using the flag `--msg-module` in `mpv.conf` the client isn't able to detect that a file has been loaded. Tested by commenting out `msg-module` flag and Syncplay works as expected.

```
 #msg-module                             # prepend module name to log messages
 msg-color                               # color log messages on terminal

```

Edit: This isn't really an issue but I did a bunch of troubleshooting since I wasn't able to load the file with my mpv.conf vs running it with no conf and narrowed down to this flag.

**Comment by Et0h** [comment]
Does this resolve the issue satisfactorily?

```
+++ syncplay/players/mplayer.py
@@ -168,6 +168,8 @@
     def lineReceived(self, line):
         if line:
             self._client.ui.showDebugMessage("player << {}".format(line))
+            line = line.replace("   cplayer: ","")  # --msg-module workaround
+            line = line.replace("  term-msg: ", "")
         if "Failed to get value of property" in line or "=(unavailable)" in line or line == "ANS_filename=" or line == "ANS_length=" or line == "ANS_path=":
             if "filename" in line:
                 self._getFilename()
```

**Comment by Felhamed** [comment]
Confirmed that fix resolved it, works perfectly. Thanks

**Comment by Et0h** [comment]
Excellent. Thanks for your support in squashing this bug :)
