### ISSUE TITLE
Support connections from a reverse proxy/URI with a path

### ISSUE THREAD

**Issue by Yuri-M-Dias** [Syncplay/syncplay#136]
# The problem
I want the client to be able to connect to `hostname:port/path`, and not ignore when it when there's a "/path". Currently, if I try to connect using that scheme, I get a:
```
$ syncplay -a hostname.tld:80/nginx --no-gui -r room --player-path mpv 
Port must be valid! 
Some necessary arguments are missing, refer to --help
```

# The reason
I have a reverse proxy server(Nginx) running on a machine, and I want to deploy syncplay from behind the proxy. I don't want to open another port on the server, as that would defeat the purpose of the reverse proxy. However, even if the reverse proxy works(I can curl/access it using the `hostname/path` URI), I can't connect to the server using the client, even when by setting up the port.

I'm willing to implement this, I just need a few pointers as to what I'd need to change to allow for it/if it's really a good change.

**Comment by Et0h** [comment]
Syncplay was not designed to connect to HTTP servers so does not support
HTTP reverse proxies.
