### ISSUE TITLE
Syncplay seeks to the position in the previous file on playlist change

### ISSUE THREAD

**Issue by Jokler** [Syncplay/syncplay#138]
We usually use the playlist to add videos which we want to add next.
If you manually change from one video to the next(e.g. you skip the outro of a video) Syncplay skips into the next video - possibly spoiling its contents.

Since we almost never need this behaviour and it often gets in the way it would be nice to hear from more people if they need it or would rather want it changed.

**Comment by Et0h** [comment]
The current expected behaviour is that Syncplay only rewinds when it is autoplaying the next file or if you shift+drag the file in to Syncplay. I'm happy with making it also rewind when you change playlist item. Anyone have any strong views in favour or against?

**Comment by Et0h** [comment]
If the behaviour is changed then there could be a "change without rewind" menu item too, but not sure if that'd add unnecessary complexity.

**Comment by iafst** [comment]
Have the same problem with next episode in list. It will be very useful thing for me. Even checkbox in menu will be ok :)

**Comment by Et0h** [comment]
It seems like the consensus view is to make this change, so I'll do that next time I have some free time (unless someone else gets to it first).

**Comment by Et0h** [comment]
The changes I've made should do the trick. Let me know if it doesn't work.
