### ISSUE TITLE
Include License File

### ISSUE THREAD

**Issue by Reanmachine** [Syncplay/syncplay#140]
It took me at least 10 minutes of trawling around to find out the project is licensed under [`Apache-2.0`](https://www.apache.org/licenses/LICENSE-2.0).

Technically Apache 2.0 requires you distribute the license with the software/source anyway.

**Comment by tompreuss** [comment]
It's distributed with the source at [resources/license.txt](https://github.com/Syncplay/syncplay/blob/master/resources/license.txt).

**Comment by Reanmachine** [comment]
Oh, I see. Not a typical location but good that it's there. Thanks.
