### ISSUE TITLE
Trying to get Syncplay to work on Mac OSX El Capitan

### ISSUE THREAD

**Issue by nyansensei** [Syncplay/syncplay#142]
I know it's not the best option to use Syncplay on a Mac but regardless I was curious. 
This is my first time using syncplay and I'm not entirely too familiar with the Mac terminal either, but I did follow all of the instructions up until the end where:

```
After you’ve installed Conda, Syncplay and an appropriate media player (see above) enter the following into the terminal:
source activate syncplay
cd syncplay
./syncplayClient.py
```
I just can't get ./syncplayClient.py to work and it keep saying:` -bash: cd: syncplayClient.py: No such file or directory`

Everything is in place, Conda Syncplace, and VLC yet I can't get syncplayClient to process. I'm wondering if it's because I noticed pyside being downgraded from 1.1.2 to 1.1.1 which doesn't support GUI

```
The following NEW packages will be INSTALLED:


    icu:    54.1-0      


The following packages will be UPDATED:


    qt:     4.7.4-0      --> 5.6.2-2     

The following packages will be DOWNGRADED:


    pyside: 1.1.2-py27_1 --> 1.1.1-py27_0


Proceed ([y]/n)? y
```

if this is the case, and the source of the problem, should I upgrade pyside? How would I do that?

I also don't have Python, but do I need it to run the .py scripts? I thought miniconda would take care of that?

On another note: should I try another workaround using Wine as a Windows emulator and running Syncplay through that? Seems like there's  alot of steps to run Wine on a Mac too

Hope anyone can help!

**Comment by alby128** [comment]
I am sorry, but I do not understand what you did. I am particularly puzzled by the fact that something is trying to update your qt to qt5 and downgrade pyside to 1.1.1 at the same time, and these two libraries are incompatible between each other. Could you please paste the command that is giving you this error? 

About the "no such file" error, you should navigate in the terminal (using cd namedir and cd ..) into the folder in which you cloned this repository using the git command. 

Finally, it would also be nice to know how you installed python in your system. In general, it is better to not mess with system python and install a fresh 2.7 copy using homebrew.

Hope this helps.

**Comment by Et0h** [comment]
Please try following the instructions at http://www.albertosottile.it/syncplay/2017/09/08/install-syncplay-on-macos-10-8/

**Comment by alby128** [comment]
@nyansensei Do you have any news on this issue?

**Comment by alby128** [comment]
No news in ten days, also we are in the middle of releasing a packaged .dmg, so I am closing this.
