### ISSUE TITLE
Support for MPC-BE

### ISSUE THREAD

**Issue by marwanpro** [Syncplay/syncplay#158]
Hello,

I use MPC-BE (Like MPC-HE, but with black UI and some improvements..)

It seems to not be usable. Can you add support, thanks

Exe name: mpc-be64.exe

**Comment by Et0h** [comment]
We have looked into this before and it turned out that because MPC-BE did not support the latest version of the MPC-HC API there was nothing we could do from within Syncplay to support it. As such, you should be asking MPC-BE to support Syncplay rather than asking Syncplay to support MPC-BE. If MPC-BE ever supports the current MPC-HC API then we'd love for someone to let us know because then we could just tweak our MPC-HC code to support MPC-BE.

**Comment by marwanpro** [comment]
Thanks for your reply. 

Here the API of MPC-BE (from the official SVN): http://svn.code.sf.net/p/mpcbe/code/tags/release_1.5.1/src/apps/mplayerc/mpcapi.h

**Comment by Et0h** [comment]
Missing from MPC-BE 1.5.1 API:
-  CMD_VERSION             = 0x5000000A,
- CMD_DISCONNECT          = 0x5000000B,
- CMD_PLAY = 0xA0000004,
- CMD_PAUSE = 0xA0000005,
- CMD_GETVERSION = 0xA0003006
- CMD_SETSPEED            = 0xA0004008,

**Comment by v0lt** [comment]
Try MPC-BE 1.5.2.3123 or later.

**Comment by Et0h** [comment]
Thanks @v0lt for https://sourceforge.net/p/mpcbe/code/3116/ and https://sourceforge.net/p/mpcbe/code/3119/

Seems to work on a cursory test with MPC-BE 1.5.2.3148 x64, but haven't done a thorough test. If you are using MPC-BE 1.5.2.3123 or above then please copy mpc-be64.exe and rename it mpc-hc64.exe (or mpc-be.exe and rename it mpc-hc.exe), set that as the path to player executable in Syncplay 1.5.0, and tell me how well it works. If we can confirm it works without issue then we can add recognition of the MPC-BE executable filenames to Syncplay. If there are issues we can see if they can be resolved Syncplay-side or if they need further changes to MPC-BE.

@joeoe asked about MPC-BE support back in 2015 (#68) so they might be able to test it too.

**Comment by Et0h** [comment]
Syncplay with MPC-BE support test build available from http://syncplay.pl/syncplay_v1.5.0_mpcbe.zip - please test it and let me know how it works.

**Comment by marwanpro** [comment]
Hello, 

It seems to work fine, no apparent lags, every functions seems to work fine.

Thanks bro

**Comment by Et0h** [comment]
@marwanpro Thanks for testing it. I've not had any problems with it either so it seems good to include in the next release of Syncplay.

**Comment by Et0h** [comment]
MPC-BE support is now in Syncplay 1.5.1: http://syncplay.pl/syncplay-1-5-1/
