### ISSUE TITLE
Using 2 different MPC-HC doesn't start both when re-starting after pause.

### ISSUE THREAD

**Issue by xNinjaKittyx** [Syncplay/syncplay#159]
My friend and I have been watching some dramas on syncplay, and we've run into an annoying problem where VLC isn't starting the 2nd time.

Setup: Friend using VLC, I'm using MPC-HC - Streaming it off some site.
1) Either of us starts the video.
2) MPC or VLC pauses
3) MPC starts the video again.
4) VLC doesn't start and freezes on a frame. (seems like even changing the timestamp doesn't do anything.

**Comment by Et0h** [comment]
Try VLC without Syncplay and do the same pauses and unpause to see if it is
actually a VLC bug. Then try the latest version of VLC to see if it is
fixed. In my experience if you are streaming the best media player to use
is mpv.

**Comment by alby128** [comment]
I was not able to reproduce this with VLC 2.2.6 and MPC-HC 1.7.13 . I tried both with local files and streaming on multiple operative systems. It could be something related to the specific file.

**Comment by Et0h** [comment]
https://trac.videolan.org/vlc/ticket/10893 and https://trac.videolan.org/vlc/ticket/5093 and https://forum.videolan.org/viewtopic.php?t=136486 and https://forum.videolan.org/viewtopic.php?t=108185 indicate that VLC has historically had issues with network streams timing out when paused without proper re-connection on unpause, but at least some of these issues appear to have been fixed in VLC 3.

**Comment by xNinjaKittyx** [comment]
I know this probably doesn't mean anything, but the URL was first placed into the playlist and both of us  opened it via the playlist.

I'll try to reproduce it with my friend again and make sure I know his exact configuration.

**Comment by xNinjaKittyx** [comment]
Ok new configuration, Sorry the first one is wrong my friend was trolling me.

1) MPC-HC - 1.7.13 64-Bit Streaming -- Friend
2) MPC-HC - 1.7.9 32-Bit  -- Me (using the one that came with KCP)

Either of us can stop, but if either of us starts, he freezes (has to restart), and it's running for me.

**Comment by Et0h** [comment]
1. Is what is said at http://syncplay.pl/trouble about MadVR relevant?

2. Does it mess up even without Syncplay?

**Comment by Et0h** [comment]
If you are using MPC and pauses are ignored then it is probably because you are using madVR. If you are have set the video filter to madVR then you will need to revert to the default filter or disable the ‘delay playback start until render queue is full’ option within madVR.

**Comment by xNinjaKittyx** [comment]
The thing is my pauses aren't being ignored.
Both of us pause when either of us pauses. It's only when we start, his MPC doesn't start (one without madVR)

**Comment by Et0h** [comment]
And what happens if everyone using madVR disables the 'display playback start until render queue is full' option?

**Comment by xNinjaKittyx** [comment]
I'll reopen a ticket when I find the time to see if this is reproduceable. Thanks.
