### ISSUE TITLE
USER POLL: Maximum username length

### ISSUE THREAD

**Issue by Et0h** [Syncplay/syncplay#160]
We want people to be able to choose a username which suits them but longer names mean less space for chat messages, filenames, etc.

If we were to limit the maximum length of the username, what is the shortest limit which would be reasonable for Syncplay?

**Comment by blaenk** [comment]
I don't know about the shortest, but preferably it'd be nice if three-character names are possible.

**Comment by alby128** [comment]
I would not go below 10 characters.

**Comment by xNinjaKittyx** [comment]
I think 16 is probably a reasonable maximum.

**Comment by Et0h** [comment]
Across all mediums we had 15 responses to our lowest reasonable maximum username length poll:
* 13% were happy with less than 8 characters
* 27% were happy with 8+
* 60% were happy with 10+
* 73% were happy with 12+
* 80% were happy with 15+
* 100% were happy with 16+

Outside of this poll other ideas have been put forward such as having no limit, having a per-client limit, and having a 32-character limit.
