### ISSUE TITLE
mpv enhanced chat feedback thread (Syncplay 1.5.2)

### ISSUE THREAD

**Issue by Et0h** [Syncplay/syncplay#168]
Enhanced chat support for mpv is ready for testing.

**Features:**
- You chat straight from mpv. By default you press enter, write your message, then press enter again. There is also an optional mode so you can start typing straight away.
- You can how see multiple chat messages at once in a ‘chat room’ style or a ‘scrolling text’ style.
- New ‘Chat’ tab in the Syncplay configuration dialogue. To get to this check ‘Show more settings’ in the normal dialogue.
- (Experimental) Enter the commands from the command line interface mode straight into Syncplay by prefixing your message with “/”, e.g. “/u” to undo last seek and “/t” to toggle whether you are in ready mode.

**Known limitations:**
Only supports input of US-ASCII characters via mpv. Other characters can be pasted in or entered via the main Syncplay UI. If you can figure out how to get around this then feel free to make a Pull Request!
You need to be using mpv >= v0.28.0 for the On-Screen Controller to be hidden during chat (e.g. to avoid it overlapping with the text input when it is positioned at the bottom)
Not all responses to /commands are relayed to mpv and only appear in the Syncplay notification window. If you want to fix this then feel free to make a Pull Request!

Release page: http://syncplay.pl/syncplay-1-5-2-beta-2-enhanced-mpv-chat-support/

**Comment by Et0h** [comment]
**Tweaks and bug fixes in Beta 2 include:**
* Fix to bug with % symbol being used in chat or filenames
* Introduction of font multiplier so lower number fonts are useful
* Various visual tweaks as to how input and output are displayed
* Improved support for non-US ASCII characters (such as é) in mpv chat input
* Increases to chat and username limit (requires server to run Beta 2 for maximum limit)

**For download links etc see http://syncplay.pl/syncplay-1-5-2-beta-2-enhanced-mpv-chat-support/**

**Comment by Et0h** [comment]
Chat support is now out. If you want to make suggestions then e-mail, talk on IRC or make a new issue. Discussion on formatting at https://github.com/Syncplay/syncplay/issues/175

**Comment by Slider-Whistle** [comment]
Just want to say that I love you for implementing scrolling-style chat

**Comment by Et0h** [comment]
> Just want to say that I love you for implementing scrolling-style chat

Cheers, I think you're the first person outside of the developers to actually comment on that feature. Do you actually use scrolling-style chat or do you just admire it from afar?

**Comment by Slider-Whistle** [comment]
I haven't actually had much of an opportunity to convince my friends into using this program at all, but I think I would as long as they're not spamming.
