### ISSUE TITLE
Additional characters

### ISSUE THREAD

**Issue by Corginyan** [Syncplay/syncplay#174]
Can't type "А" or "а" characters in MPV chat (first letter of cyrillic alphabet). Maybe problem is here:

https://github.com/Syncplay/syncplay/blob/406e9a4af50f30f2291b2887ec52988a3f89bee5/resources/syncplayintf.lua#L63

**Comment by Et0h** [comment]
Thanks for reporting this omission. Does replacing your /resources/syncplayintf.lua file with https://raw.githubusercontent.com/Syncplay/syncplay/master/resources/syncplayintf.lua succeed in  allowing the input of the first letter of the Cyrillic alphabet through mpv? Are there any other characters that need adding?

**Comment by Corginyan** [comment]
> succeed in allowing the input of the first letter of the Cyrillic alphabet through mpv?

Yes.
> Are there any other characters that need adding?

Now i can input every cyrillic character.

**Comment by Et0h** [comment]
This issue should now be resolved by the [Syncplay 1.5.2 Official Release](http://syncplay.pl/syncplay-1-5-2/) so I'll close the issue for now. If the issue persists then please let me know.
