### ISSUE TITLE
Connect, Lose Connection, Reconnect Loop

### ISSUE THREAD

**Issue by blaenk** [Syncplay/syncplay#177]
With the Windows 1.5.2 Beta 3 binaries, the server launches fine but launching the client shows in its log window that it connects, loses connection, then reconnects, all in very quick succession, in a loop. This also resulted in a Syncplay.exe.log file, which I [posted as a gist](https://gist.github.com/blaenk/b0f331c3f685b5a455df8b2d1d517521).

Let me know what other information may be useful.

**Comment by Et0h** [comment]
Thanks for posting Blaenk. I should probably be able to figure it out with just that but I do have a few questions that might be helpful:

1. What OS were you using?
2. What media player were you using?
3. Were you trying to connect to the default Syncplay servers or a private server?
4. If you were on a private server, what build was the private server using and does connecting to a public server make a difference?

**Comment by blaenk** [comment]
Oops sorry for missing that stuff:

1. Windows 10 64-bit
2. Tried with both MPC-HC (the usual one I use) and VLC 3.0. Both did the same, although I'm ignoring VLC 3.0 since it just came out today and it may or may not have other incompatibilities with Syncplay
3. Private server from the same binary release, 1.5.2 Beta 3
4. Just now tried connecting to the public server at `syncplay.pl:8997` and it did not present this issue.

For what it's worth, I have not restarted my computer after installing this latest Syncplay, as I've never needed to before, but I'll give it a shot.

Also, I've always upgraded it by installing over Syncplay, not bothering to uninstall the previous version beforehand. This had not been an issue until possibly now, so if you suspect that may be the cause, I'll try uninstalling and installing cleanly.

Also, I do have Python 3 installed on this system, but it wasn't causing any issues with the previous version of Syncplay I had installed, which, I'm sorry to admit, I don't recall the exact version, but I imagine it must have been 1.5.1 release.

**Comment by blaenk** [comment]
As a follow up, I uninstalled Syncplay and its configuration file (checked the checkbox), and did a clean install of 1.5.2 Beta 3 again, then restarted, but the issue persisted.

**Comment by Et0h** [comment]
This issue will be fixed in the next release. A workaround is to specify the chat message length when you run the server: `--max-chat-message-length=125`

**Comment by Et0h** [comment]
This should now be resolved by Syncplay 1.5.2 Official Release http://syncplay.pl/syncplay-1-5-2/ so I'll close the issue for now. If problems recur in the new version then please let me know.
