### ISSUE TITLE
Latest macOS client can't find syncplayintf.lua

### ISSUE THREAD

**Issue by sometoby** [Syncplay/syncplay#181]
Starting the latest (1.5.3) Syncplay client for macOS with mpv, I get this error:

```
[syncplayintf] Lua error: cannot open /Applications/Syncplay.app/Contents/Resources/resources/syncplayintf.lua: No such file or directory
```

The error does not occur when I start the client with VLC instead of mpv.

**Comment by albertosottile** [comment]
Confirmed. On it.

**Comment by Et0h** [comment]
[Syncplay 1.5.3a](https://syncplay.pl/syncplay-1-5-3/) should resolve the issue. Thanks for reporting it!
