### ISSUE TITLE
sync over lan with udp

### ISSUE THREAD

**Issue by amaau** [Syncplay/syncplay#190]
is it possible to sync playback over LAN?

**Comment by albertosottile** [comment]
Well, as far as I know, it is possible to run your own server inside your LAN and have all the clients connect to it. 

I would like to point out something though, in view of this and of the other issue you opened (#189): Syncplay does not synchronize the players with high precision, and it is not designed to do that. Hence, a delay of 1 or 2 seconds between clients is perfectly normal for Syncplay. So, if you are planning to synchronize video players in the same room, Syncplay might not be the best tool.

**Comment by amaau** [comment]
Okay, thanks for clarifying!

**Comment by wation** [comment]
Which player can play synchronously without delay in LAN?
