### ISSUE TITLE
Syncplay can unknowingly uses old VLC lua script

### ISSUE THREAD

**Issue by Et0h** [Syncplay/syncplay#193]
Syncplay 1.4.0 fixed issue #108 back in January 2017, preventing erroneous jumps from VLC that were caused by VLC changing the unit used for reporting position.

The Syncplay installer will place the newest version of syncplay.lua in the %PROGRAMFILES% folder which will resolve the issue. Normally this is fine, but if someone has an old version of syncplay.lua in their VLC %APPDATA% folder then VLC will use that in favour of the more recent version in %PROGRAMFILES%.

Even worse, Syncplay won't notice it's on an old version, meaning on some version mismatches it will act incorrectly without the user knowing why.

**Comment by benplumley** [comment]
Just downloaded 1.6.0 and this caught me out, even though I downloaded both the application and the Lua script fresh today. The cause of this, for me, was that the script in the VLC addon repository is not up-to-date.

**Comment by Et0h** [comment]
@benplumley  Thank you for letting me know that the version in the VLC repository needed updating. I have now updated the version in the VLC repository.

**Comment by Et0h** [comment]
https://github.com/Syncplay/syncplay/pull/220 hopefully resolves this issue.
