### ISSUE TITLE
Support for mpc-qt

### ISSUE THREAD

**Issue by 54** [Syncplay/syncplay#197]
Hey,

I haven't personally looked into how much extra work it'd be to add support for mpc-qt. But, it'd be nice to have. Essentially, it is a crossplatform remake of mpc-hc using qt5 and libmpv.

You can find it on GitHub here: https://github.com/cmdrkotori/mpc-qt

**Comment by Et0h** [comment]
Context: Implementing and maintaining support for a media player can be a major commitment, as there can often be changes required to the media player to support the relevant API features, and once that support is implemented it needs to be maintained through multiple versions of the media player software. It is not unusual for breaking changes to be implemented in media players without notice, so it needs people who are using the software regularly and keeping up with the betas for the media player to keep things working.

**Comment by albertosottile** [comment]
Also, if I may, the fact that there is no indication of stability nor a release candidate makes even more awkward to provide a completely external Syncplay support for this software. Having a stable tagged release could allow us to work with it and at least attempt to support it from our side. Given the current situation, I agree that involving the developer might be the best shot for adding it in Syncplay.

**Comment by Et0h** [comment]
I am closing this issue for now in line with the above discussion, but if anyone wants to volunteer to work on this (ideally the mpc-qt developer) then I am happy to re-open it.
