### ISSUE TITLE
Syncplay server no longer works with --password option

### ISSUE THREAD

**Issue by alxpettit** [Syncplay/syncplay#200]
Syncplay server exits with TypeError when I try to start it with `--password` option.

```
[syncplay@caesium ~]$ /usr/bin/syncplay-server --port [REDACTED] --password [REDACTED]                          
Welcome to Syncplay server, ver. 1.5.6
Traceback (most recent call last):
  File "/usr/bin/syncplay-server", line 36, in <module>
    args.stats_db_file))
  File "/usr/lib/syncplay/syncplay/server.py", line 28, in __init__
    password = hashlib.md5(password).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
```
I fixed the code by adding `password = password.encode('utf-8')` before line 28 in `server.py`. Some similar modification should be made to fix this regression. :wink:

**Comment by Et0h** [comment]
Your suggested fix has now been implemented. Thank you for flying with Syncplay :)
