### ISSUE TITLE
Was the website hacked?

### ISSUE THREAD

**Issue by lmmfranco** [Syncplay/syncplay#203]
It currently shows a picture of Gasai Yuno

**Comment by Et0h** [comment]
I don't think we've been hacked, I think it might just be a DNS configuration/propogation issue combined with shared hosting. If you have problems then try changing your DNS server, e.g. to 1.1.1.1 (Cloudflare DNS), 8.8.8.8 (Google Public DNS) or 208.67.222.222 (Cisco OpenDNS), and let us know if that helps.
