### ISSUE TITLE
Better import error message

### ISSUE THREAD

**Issue by Xcelled** [Syncplay/syncplay#206]
When running syncplay, I got `Could not import GUI libraries. If you do not have PySide installed then you will need to install it for the GUI to work.`

I think this is misleading for a few reasons:
1. I'm running Python 3.6 (the default for Ubuntu Bionic), so I really needed to install PySide**2**
2. I still received the same error even after installing PySide2. By executing the imports one at a time in the REPL, I discovered I also needed to install twisted, though of course the message didn't indicate this.

IMO, the error message shouldn't be hardcoded to tell the user to install a particular library for these reasons. A possible enhancement would be to bundle syncplay as a pip package, so said requirements can be automatically installed. (Plus, you could then just do `pip install syncplay` to install on all platforms)

**Comment by albertosottile** [comment]
Side note: you can also install PySide 1.x on Bionic and Python 3.6 with the `python3-pyside` package (https://packages.ubuntu.com/bionic/python3-pyside). As far as I know, PySide2 is not necessarily required on Linux on any version of Python, yet.

**Comment by Xcelled** [comment]
There's precedent for using pip to install "apps", eg https://github.com/nvbn/thefuck. Also setup.py provides a [mechanism](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html) for registering python scripts as executables.

I'd make the argument that, since syncplay doesn't install required packages automatically, `pip` knowledge is still required to get syncplay running and that not leveraging setup.py's dependency mechanisms means that *more* pip knowledge is required. Case in point: I didn't know that PySide1.x was called `python3-pyside`. Sure, I could have looked it up, but that's beside the point.

I'm not saying that a `pip` package is the way to go, I'm just urging you not to discount it right away.

**Comment by albertosottile** [comment]
> I'd make the argument that, since syncplay doesn't install required packages automatically, pip 
> knowledge is still required to get syncplay running and that not leveraging setup.py's dependency 
> mechanisms means that more pip knowledge is required.

We had a similar discussion within the team during the introduction of PySide2. When I raised that very same argument, the general consensus was that Linux users install dependencies mainly through packages, and not using `pip`. Anyway, I encourage you to comment in #199 about this.

**Comment by albertosottile** [comment]
For the moment, I am fixing only the error message that shows if Twisted is missing. We will address the PySide error message as soon as PySide2 packages are commonly available for Linux. Thanks for reporting this.
