### ISSUE TITLE
No way to generate optimized bytecode?

### ISSUE THREAD

**Issue by alxpettit** [Syncplay/syncplay#207]
I'm now a co-maintainer of the [syncplay AUR package](https://aur.archlinux.org/packages/syncplay). Ideally, we'd have the installation have `.pyc` files generated and packaged so that they're tracked by `pacman` -- but currently we do not. I'd like to know what the equivalent is of `--optimize=1` for your install toolchain, since you're not using `setup.py`.

**Comment by Et0h** [comment]
I do not have any experience with setup.py, so you might need to find someone with relevant experience to make an appropriate PR.

**Comment by albertosottile** [comment]
In the last few days, I investigated the possibility of using `setuptools` with Syncplay (hence writing a `setup.py` script). Unfortunately, our current project structure does not match the one typically used for python modules or packages, and these differences really stood out in my attempts to adapt `setuptools` to Syncplay, creating a lot of issues.

At this moment, we would like to keep our current folder structure, so we decided to abandon the idea of using also `setuptools` for distributing Syncplay. @alxpettit, going back to your question, a way to generate optimized bytecode for all the python files in Syncplay could be to run 
`python -m compileall .` while being in the repository main folder. Please let us know if this command can be included in the workflow used to pack AUR packages. In the meantime, I am closing this issue.
