### ISSUE TITLE
Windows 10. Nothing happens when I open SyncPlay.

### ISSUE THREAD

**Issue by themegabyte** [Syncplay/syncplay#208]
Hello Guys,

Could you please have a look at my issue? I cannot seem to debug it. I am quite lost. When I double click SyncPlay.exe, nothing happens.

My config is up to date windows 10 (12/2/18), SyncPlay 1.6.1, VLC 3.0.4.

Please help. Thank you and Regards.

Video of the issue: https://youtu.be/GB7vLslNk3U

**Comment by Et0h** [comment]
Please try the Syncplay portable version available from https://github.com/Syncplay/syncplay/releases/download/v1.6.1/Syncplay_1.6.1_Portable.zip

If that doesn't work then please install the Microsoft Visual C++ 2010 Redistributable Package (x64) available from: https://www.microsoft.com/en-us/download/details.aspx?id=14632

If that doesn't work then please install the Microsoft Visual C++ 2008 Redistributable Package (x86) available from https://www.microsoft.com/en-gb/download/details.aspx?id=29

Please report back on if that works and if so what did the trick.

**Comment by Et0h** [comment]
If that does not work yo could also try the Visual C++ Redistributable for Visual Studio 2015 available from https://www.microsoft.com/en-us/download/details.aspx?id=48145&751be11f-ede8-5a0c-058c-2ee190a24fa6=True

**Comment by Kardzhilov** [comment]
same issue as OP, i tried the suggestions and they didn't help

**Comment by Et0h** [comment]
@themegabyte  @Kardzhilov Three more things to try:
1. Checking %APPDATA%\.syncplay.log to see if it contains any error information.
2. Running Syncplay as administrator.
3. Trying Syncplay 1.5.5: https://syncplay.pl/Syncplay_v1.5.5_Portable.zip

**Comment by Kardzhilov** [comment]
> @themegabyte @Kardzhilov Three more things to try:
> 
> 1. Checking %APPDATA%.syncplay.log to see if it contains any error information.
> 2. Running Syncplay as administrator.
> 3. Trying Syncplay 1.5.5: https://syncplay.pl/Syncplay_v1.5.5_Portable.zip

1. No log file found, only a config file that seemed fine.
2. Did not make a change.
3. Works! Something must have been changed between that version and the newest that just makes it refuse to start up

**Comment by Et0h** [comment]
@Kardzhilov  @themegabyte  Please try out https://bintray.com/alby128/Syncplay/download_file?file_path=Syncplay_1.6.2_Portable.zip and let us know if it works. In this test version of Syncplay @albertosottile has updated pypiwin32 and pyside2 and it would be useful to know if that fixes the issue. 

I'm not sure, but but it is also possible that if you run Syncplay with the --debug command line switch then it will make it more likely to create a useful .syncplay.log file in %APPDATA (just don't leave it in --debug mode all the time or your log file will get pretty long).

**Comment by mrg0lden** [comment]
Hey, I had the same problem, but got it resolved by installing Microsoft VS C++ 2010 Redistributable and 2013 Redistributable both x86 and x64.

**Comment by Kardzhilov** [comment]
> @Kardzhilov @themegabyte Please try out https://bintray.com/alby128/Syncplay/download_file?file_path=Syncplay_1.6.2_Portable.zip and let us know if it works. In this test version of Syncplay @albertosottile has updated pypiwin32 and pyside2 and it would be useful to know if that fixes the issue.
> 
> I'm not sure, but but it is also possible that if you run Syncplay with the --debug command line switch then it will make it more likely to create a useful .syncplay.log file in %APPDATA (just don't leave it in --debug mode all the time or your log file will get pretty long).

I was unable to figure out how to start it with debug mode, but version 1.6.2 works! I tested 1.6.1 and it still does not work so the changes have helped :)

**Comment by themegabyte** [comment]
Hey guys, So sorry for not following up on this. My syncPlay started working after a windows update. Very weird but that's how it got fixed.

@Et0h Thanks for the path to the log file. I will refer to it if it doesn't work again.
