### ISSUE TITLE
Bug report: --max-chat-message-length can't be used to raise the maximum length

### ISSUE THREAD

**Issue by csritu** [Syncplay/syncplay#224]
It seems like [this](https://github.com/Syncplay/syncplay/blob/master/syncplay/server.py#L172) is the offending line, but I don't fully understand the architecture so I could be misunderstanding the root of the problem.

**Comment by Et0h** [comment]
Thank you for reporting this issue and identifying where the problem might have arisen. You identified the correct line of code and I have now corrected it so the bug should hopefully now be fixed.
