### ISSUE TITLE
youtube-dl not working on mpv client inside syncplay

### ISSUE THREAD

**Issue by brenolf** [Syncplay/syncplay#228]
Whenever I try to add an URL to syncplay playlist to run, MPV will throw

```
[ytdl_hook] youtube-dl failed: unexpected error ocurred 
Failed to recognize file format.
```

This doesn't happen if I call mpv directly from the terminal, even if I pass `--player-operation-mode=pseudo-gui` to it, it will normally play the video. `youtube-dl` is on `/usr/local/bin/youtube-dl` and `/usr/local/bin` is on my PATH.

**Comment by albertosottile** [comment]
Thanks for reporting this. We need further information to reproduce the issue:
- your Syncplay client version
- your operative system version
- your mpv version
- (if possible) the URL that caused the problem, or another URL that causes the same problem

**Comment by brenolf** [comment]
Syncplay: 1.6.2
youtube-dl: 2019.03.09
mpv: 0.29.1

Running on OSX Mojave 10.14.3

Any URL fail, for example https://www.youtube.com/watch?v=VrS6akzR3sk.

**Comment by albertosottile** [comment]
Reproduced, but only on Mojave 10.14.3, which is not my primary system (I had to install a VM). Youtube links work on High Sierra. 

My error message is quite different, though:
```
[ytdl_hook] youtube-dl failed: not found or not enough permissions 
Failed to recognize file format.
```

This message and the fact that this bug occurs only on Mojave suggest some permission issue caused by the updated security measures in 10.14. I am going to investigate it as soon as I can.

**Comment by brenolf** [comment]
Sometimes I also get that error, which made me think `youtube-dl` was not in the PATH or that it didn't have the right permission. I tried changing it to 777 and creating a symlink inside ~/.config/mpv but none of these approaches worked.

Thanks for checking, though, and awesome work with Syncplay 🏆

**Comment by albertosottile** [comment]
I was wrong, the bug is reproducible at least on 10.13 and 10.14 (but probably also on older systems) and from Syncplay 1.5.0. So, thank you for reporting this! 

We identified `py2app` as the culprit and I am currently drafting a workaround.

**Comment by albertosottile** [comment]
@brenolf Could you please test the fix on your system? If you are running Syncplay from the packed dmg, you can download an updated test version from my Bintray: 
https://bintray.com/alby128/Syncplay/download_file?file_path=Syncplay_1.6.3.dmg

**Comment by brenolf** [comment]
yes, it works! thanks @albertosottile!

**Comment by albertosottile** [comment]
Thank you for testing this. I am going to close this issue now. Remember to download the next official release of Syncplay with the included fix as soon as it is ready.

**Comment by brenolf** [comment]
thanks for the fast fix! 🚀

**Comment by brenolf** [comment]
For other people that might face this problem: running on

```
Syncplay: 1.6.3
youtube-dl: 2018.XX.XX
mpv: 0.29.1
Running on OSX Mojave 10.14.3
```

Caused error on some videos. Solved by upgrading `youtube-dl` to the newest version.
