### ISSUE TITLE
Running the client headlessly?

### ISSUE THREAD

**Issue by ritiek** [Syncplay/syncplay#229]
Hi, thanks for the awesome tool!

I'd also like to be able to use the syncplay client on headless machines for only listening to audio. Since, syncplay client pops up the player window (which requires an X server) and due to this one cannot play audio-only files with syncplay client on headless machines. Would something like this be possible?

**Comment by ritiek** [comment]
I got it to work for mpv-player by adding `vo=image` to my `/etc/mpv/mpv.conf` on my headless device! `vo=tct` seems to work as well!

**Comment by ritiek** [comment]
So far I managed to get syncplay dirty work on headless machines, though you still need atleast 1 client with access to X-server. This client (with X-server enabled) will control the music and it would be reflected back on headless devices.

I tried this with only mpv-player. On your headless devices, you need to add these lines in your `/etc/mpv/mpv.conf`:
```
vo=null
no-video
```
and then use syncplay as usual!

----------

I also got this working on Android with Termux. mpv for Termux is built without lua support (lua support was added recently in https://github.com/termux/termux-packages/commit/f1a2af56d2c75aa1ac8af2db33469d5de5b4f583, but it isn't available with `pkg` yet and I don't know much on how to build packages manually for Termux).

Since no lua support, so before compiling syncplay on my Android, I removed this line https://github.com/Syncplay/syncplay/blob/bcf8174b7d4ae723c4bb9788d701a646367a023f/syncplay/players/mpv.py#L44

Also, mpv on Termux does not have access to X11, so you would need to add the above config for mpv here as well (in `/data/data/com.termux/files/usr/etc/mpv/mpv.conf`), so that it works headlessly with Termux.

----------

However, I'd still very much appreciate a command-line only mode for mpv. mpv allows all usual controls such as pause, volume control, seek, etc. through the command-line itself. If this gets implemented, we won't need an X-server enabled device for controlling playback on headless devices. And also, we would be able to control playback on clients via SSH which would be very nice, atleast for me! :D

**Comment by Et0h** [comment]
You could probably hack the Syncplay code to convert chat messages into mpv commands, which means that any client can control things via the chat facility.

You might also be able to enable IPC on mpv to allow for it to be controlled by an IPC script you write: https://github.com/mpv-player/mpv/blob/master/DOCS/man/ipc.rst
