### ISSUE TITLE
Media Player detected as MPlayer if path contains "*mplayer" anywhere (e.g. SMPlayer)

### ISSUE THREAD

**Issue by elvissteinjr** [Syncplay/syncplay#234]
Been trying to use the same mpv build I use with SMPlayer for Syncplay.

For example, my mpv executable is located in "C:\Program Files\SMPlayer\mpv\mpv.exe".
This is detected as mplayer, so trying to use it results in an "Fatal Error" message.

Putting a copy of mpv elsewhere or renaming the directory to not contain "mplayer" works of course, but it would be nice if that wasn't necessary.

**Comment by Et0h** [comment]
Thanks for raising this issue - this should be fixed in future versions.
