### ISSUE TITLE
VLC Portable fails

### ISSUE THREAD

**Issue by poisonborz** [Syncplay/syncplay#235]
The Portable version (PAF) still has the #220 issue as script is not copied. As this is a popular version, the docs could mention where the .lua should be placed.

**Comment by Et0h** [comment]
Can you make a PR so it detects the portable version and copies it to the correct folder automatically?

**Comment by poisonborz** [comment]
Sadly not. A mention in the docs of where this correct location in the VLC root (in all os versions) would be already be a big help for all those who seek answers after this error pops up (file copy could fail also because of permission error, etc) .

To note, [PAF](https://portableapps.com/apps/music_video/vlc_portable) version's App/vlc folder mirrors a standard vlc root.

**Comment by Et0h** [comment]
If someone made a PR which did this and tested it then I would accept it. Otherwise I'll get to it when I have some free time (which might not be for a while).

**Comment by albertosottile** [comment]
>  As this is a popular version, the docs could mention where the .lua should be placed.

To be honest, I would also like to know where it should be placed. Is there a particular reason why the PAF version ignores the files in the `APPDATA\VLC` folder?

**Comment by Et0h** [comment]
@albertosottile I think the reason VLC portable (PAF) ignores the APPDATA\VLC folder is to be portable, i.e. ensure that it can run off a portable hard drive on any PC and operate in the same way. Syncplay similarly only uses the syncplay.ini file in the Syncplay folder when in portable mode, ignoring the file in the APPDATA\VLC folder.

The other question you raise is about placing the script in the playerPathFolder\lua\intf\ folder. This is what I was alluding to in my earlier post, and @poisonborz explained that this might not work in circumstances where Syncplay did not have write access to the VLC portable folder.

One potential option is for Syncplay to have special rules for VLCPortable.exe: Try to copy to `playerpath\App\vlc\lua\intf`, and in the event that the write fails it can display a message telling people about manually copying the file over to that folder (or directing them to a webpage that provides relevant instructions).

**Comment by poisonborz** [comment]
Just for clarification:
- the lua file needs to be compiled to .luac
- the file needs to be copied to `%vlcportablelocation%/app/vlc/lua/intf`

**Comment by Et0h** [comment]
@poisonborz  Why does it need to be compiled to .luac?

**Comment by Et0h** [comment]
@poisonborz I've added initial support for VLC. If you close VLC via Syncplay it is fine, but if you close it via VLC itself then next time you run VLC via Syncplay it complains stating: "VLC Media Player Portable did not close properly last time it was run and will now clean up". I don't know if there is any way to prevent this behaviour other than Syncplay doing some sort of manual clean of the VLCPortable folder which doesn't seem very elegant.

**Comment by poisonborz** [comment]
> Why does it need to be compiled to .luac?
@palbertosottile as I could see all the lua files in VLC folders were .luac - and the script seemed to be only recognized when compiled to such.

> if you close it via VLC itself then next time you run VLC via Syncplay it complains
In my own shell scripting with PAF apps I just did it manually, but yeah, in a production software this is not the best. This is standard PAF behaviour and there might be a way around it, maybe a post in https://portableapps.com/forums/support/music-video could help.

**Comment by Et0h** [comment]
> > Why does it need to be compiled to .luac?
> 
> @palbertosottile as I could see all the lua files in VLC folders were .luac - and the script seemed to be only recognized when compiled to such.

I think VLC gives preference to .luac but still runs .lua fine, and that seems consistent with my testing of the PAF version of VLC.

> > if you close it via VLC itself then next time you run VLC via Syncplay it complains
> 
> In my own shell scripting with PAF apps I just did it manually, but yeah, in a production software this is not the best. This is standard PAF behaviour and there might be a way around it, maybe a post in https://portableapps.com/forums/support/music-video could help.

If someone who uses VLC PAF wants to take responsibility for being a Syncplay maintainer for it then they can raise the issue with the portable apps team and try and get it working.

 I don't use VLC PAF so I am not well positioned to be a maintainer for it (plus I already have to maintain VLC, mpv, MPC-HC and MPC-BE so don't really have the time for taking on additional responsibilities).
