### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by nirolada** [Syncplay/syncplay#236]
Hi,

I'm running linux mint cinnamon 19.1 on a Lenovo Yoga 710.
I tried to install syncplay with the tar.gz archive according to the guide on your website. After taking care of many problems with python, I still get an error I have not enough knowledge to deal with.
Error:
Segmentation fault (core dumped)

What can I do to make your application work?
[btw, I'm quite noob on linux]

**Comment by albertosottile** [comment]
Hi, could you tell us exactly what did you do to set up your environment? Thanks.

**Comment by Et0h** [comment]
For full functionality Sycplay has the following dependencies:
- python >= 3.4.0 (Last version which supported Python 2 was Syncplay 1.5.5)
- twisted >= 16.4.0 (on Debian based distros python3-twisted)
- PySide >= 1.2.2 or PySide2 >= 5.12.0
- certifi >= 2018.11.29
- pyopenssl >= 16.0.0
- service_identity
- idna >= 0.6 != 2.3
- VLC >= 2.2.1 and/or mpv >= 0.6.2

It would be helpful if you could let me know what versions you are using for these. It would also be helpful to know your system locale (i.e. what language everything is in).

**Comment by albertosottile** [comment]
@nirolada If you want, you could also beta test our AppImage release, downloadable from [here](https://bintray.com/alby128/Syncplay/download_file?file_path=Syncplay-1.6.3-x86_64.AppImage). This release should allow you to use Syncplay without setting up its environment. Further information about AppImages can be found on the official website: https://appimage.org.

**Comment by albertosottile** [comment]
I am closing this since no feedback has been received in the past three weeks. Please feel free to reopen it if you still encounter this issue. Once again, I encourage you to test our AppImage.
