### ISSUE TITLE
Syncplay (in CLI mode) hangs when entering common keypresses during termination sequence

### ISSUE THREAD

**Issue by alxpettit** [Syncplay/syncplay#238]
## Status
System: `Linux caesium 5.0.19.a-1-hardened #1 SMP PREEMPT Tue May 28 23:55:46 CEST 2019 x86_64 GNU/Linux`
Syncplay Version: `1.6.3.r10.g3a4cf41-1`

Should have been pulled fresh from the git repo as of today (2019-06-15), if my AUR system is working as intended.

## Steps to reproduce:
1) Close media player window.
2) When you get the `Press enter to exit`, do what I did and press Ctrl+D instead on muscle memory.
3) Watch in awe as it becomes completely non-responsive to all input and has to be terminated with a SIGKILL.

No error messages, even when running with `--debug` flag.

**Comment by albertosottile** [comment]
@alxpettit Just two quick questions for you: was your player `mpv`? Did you close the player to trigger the `Press enter to exit` message? Thanks.

**Comment by alxpettit** [comment]
Yes. And yeah, I closed the media player window. Just pressed Q.

**Comment by albertosottile** [comment]
Thanks for reporting this. We are going to eliminate that prompt request entirely and let Syncplay close automatically in those cases, since that prompt was inserted there for historical reasons that should no longer be relevant.

**Comment by alxpettit** [comment]
Yay, thanks ^_^
