### ISSUE TITLE
Program exits after clicking run

### ISSUE THREAD

**Issue by TETYYS** [Syncplay/syncplay#240]
No matter the settings, program exits after clicking either of run buttons on 1.6.4. Works normally on 1.6.3.

**Comment by albertosottile** [comment]
Thanks for reporting this. Could you give us more information about the OS you are using?

**Comment by TETYYS** [comment]
Windows 10 1809

**Comment by albertosottile** [comment]
Did you use the portable version or the installer?

**Comment by TETYYS** [comment]
Both exit without any messages or warnings.

**Comment by Et0h** [comment]
Does anything appear in %APPDATA%\syncplay.log?

**Comment by TETYYS** [comment]
No, I don't have such file.

**Comment by Et0h** [comment]
What media player are you using and what version of that media player?

**Comment by TETYYS** [comment]
Any media player I choose and before clicking run results in program exiting, I have mpv 0.29.1, mpc-hc 1.8.3 and VLC 3.0.4

**Comment by Et0h** [comment]
Are you specifying a room name and a server?

**Comment by TETYYS** [comment]
Specifying a room worked! I think it should print or show some kind of message that it's required.

**Comment by Et0h** [comment]
Yes, it used to show an error message... will need to figure out why it doesn't any more. Thanks for flagging up this issue!

**Comment by Et0h** [comment]
@TETTYS Does the new versions in https://github.com/Syncplay/syncplay/releases/tag/v1.6.4 resolve this bug for you?

**Comment by TETYYS** [comment]
yep 👍

**Comment by albertosottile** [comment]
@TETYYS Thank you very much for reporting this so quickly. You literally saved the day! Enjoy this new release :)
