### ISSUE TITLE
"This client does not support TLS" on Windows 1.6.4

### ISSUE THREAD

**Issue by Tremolo4** [Syncplay/syncplay#241]
I just updated to v1.6.4 using `Syncplay-1.6.4-Setup.exe` but my Windows client still shows
> This client does not support TLS

when connecting to my TLS-enabled server.

**Comment by Et0h** [comment]
Does it work fine with the portable version?

**Comment by albertosottile** [comment]
Hi, thanks for reporting this. Did you try to use the same client with one of our public servers? 

If you could run the client in debug mode, you could get more useful error messages in the log file. Please, run it from the cmd prompt with —debug as argument, then look in the %APPDATA%\.syncplay file and paste here its content.

Also, if you could try to connect to your server from another platform (Linux or macOS) and confirm that TLS works fine in such a case, that would be great.

**Comment by Tremolo4** [comment]
Happened as well with the public servers, then I went to run it with `--debug`, so opened a console in the Syncplay folder and ran `Syncplay.exe --debug` and enryption worked. Also works without `--debug`.

:thinking: 

So I went to check the syncplay shortcut in my start menu and it turns out the directory to execute in is set to `"C:\Program Files (x86)\Syncplay\styles"`. Running it from the styles folder in the console triggers the "does not support TLS" message as well. Seems like that's the problem! I'm quite certain I didn't touch the shortcut, so it must have been created like this by the installer.

**Comment by albertosottile** [comment]
We added an instruction in our NSIS script that should explicitly set the "start in" path in links generated by NSIS. @Tremolo4 can you test the [updated installer generated by our CI](https://bintray.com/syncplay/Syncplay/download_file?file_path=Syncplay-1.6.4-Setup.exe)? Thanks.

**Comment by Tremolo4** [comment]
I ran your linked installer over my current installation with the broken shortcut and it got fixed. Also tested uninstalling and re-installing with the new installer, also worked.

Nice, thanks!
