### ISSUE TITLE
[Feature request] TLS with fullchain.pem file

### ISSUE THREAD

**Issue by Tremolo4** [Syncplay/syncplay#242]
The TLS functionality on the server apparently requires a `cert.pem`, `chain.pem` and `privkey.pem` file. However my hosting provider (www.uberspace.de) only provides Let's Encrypt certificates in the form of `fullchain.pem` and `privkey.pem`.

Essentially not a big deal since the actual certificates are the same: currently I'm using a small script to split the `fullchain.pem` file -- first cert is `cert.pem`, any additional certs are `chain.pem`.

I was wondering whether syncplay could be taught to read the certificates out of a single fullchain.pem file as well, so I don't have to bother with splitting it.

Thanks for reading :)

**Comment by albertosottile** [comment]
Believe me, we tried to get rid of the extra `chain.pem` file but, as far as we know, that is currently not possible with Twisted. See [their documentation](https://twistedmatrix.com/documents/current/api/twisted.internet.ssl.CertificateOptions.html) and also [this post](https://community.letsencrypt.org/t/pyopenssl-twisted-servers-certificate-chain-is-incomplete/18591). You can also find more information about our implementation of TLS in the comments of issue #217.

If things will change in newer releases of Twisted, I would be more than happy to amend this feature.

**Comment by Tremolo4** [comment]
The insufficient APIs there are indeed annoying. But I've managed to come up with something that works!  #243
