### ISSUE TITLE
MPVNet Support

### ISSUE THREAD

**Issue by grravity** [Syncplay/syncplay#246]
Would love to have MPVNet support. It just errors when trying to use it.

**Comment by Et0h** [comment]
I can confirm that it gives the following error:
```
Exception

version: MPV_ERROR_PROPERTY_NOT_FOUND

System.Exception: version: MPV_ERROR_PROPERTY_NOT_FOUND
   at mpvnet.mp.set_property_string(String name, String value, Boolean throwOnException) in D:\Projekte\CS\mpv.net\mpv.net\mpv\mp.cs:line 420
   at mpvnet.mp.ProcessCommandLine() in D:\Projekte\CS\mpv.net\mpv.net\mpv\mp.cs:line 544
```

I think if you want MPVNet to support Syncplay then you will need to discuss this with the MPVNet developers.

**Comment by stax76** [comment]
mpv.net has no switch called --version

**Comment by stax76** [comment]
@Et0h 

There is a property called 'mpv-version' you can get via json ipc.

**Comment by Et0h** [comment]
@stax76 Even with version checks enabled it still gives the error I noted in my first response.

**Comment by stax76** [comment]
I knew mpv reacts to keys pressed in a console window but that you can send input commands to stdin is new to me. It's hard to tell how hard it would be to replicate this in mpv.net. You seem to send --script, there would be a property called 'scripts' but it can only be set before libmpv initialization and mpv.net parses the command line after initialization. My python knowledge being only very basic don't help either, there might not be an easy way for us to make this work.

**Comment by stax76** [comment]
well, I figured there is input-terminal

```
            if (App.IsStartedFromTerminal)
            {
                set_property_string("terminal", "yes");
                set_property_string("input-terminal", "yes");
                set_property_string("msg-level", "osd/libass=fatal");
            }
```

maybe it's not that hard, we'll see.

**Comment by stax76** [comment]
I got this totally working... Just don't invoke an instance to get the version and try my next release.

**Comment by stax76** [comment]
https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/f/s!ArwKS_ZUR01gySQIE1QCL2i9F_uR

**Comment by Et0h** [comment]
@stax76 Nice one - it works! :)

mpvnet support can now be added to Syncplay.

**Comment by Et0h** [comment]
Okay, initial support should be added by 187c8d87fc369faa9b0a71715f771b94ea9810fc which you can test out at https://bintray.com/syncplay/Syncplay/Syncplay/v1.6.5#files

**Comment by Et0h** [comment]
@Z3ROGRAV1TYx Can you please test the test build of mpvnet with the test build of Syncplay and let me know if it works for you? Seems to be working fine for me.

**Comment by fmohican** [comment]
It's work! Smooth!!!
Tested with last version of MPV.NET && V1.6.5 Dev.

**Comment by RaXorX** [comment]
![image](https://user-images.githubusercontent.com/44987810/69480099-55419c80-0e2a-11ea-9268-c23c4b753a1b.png)

@Restia666Ashdoll @Et0h 
I'm getting this issue while using the latest mpvnet (5.4.4.0) and syncplay.

**Comment by Et0h** [comment]
@RaXorX What version of Syncplay are you using? I tried MPVNet 5.4.4.0 on Windows 10 with Syncplay 1.6.5 pre-realse at https://bintray.com/syncplay/Syncplay/Syncplay/v1.6.5#files and it works fine.

Actually, when I say "works fine" there is one outstanding issue with Syncplay and MPVnet which I need to get to the bottom of, which is that sometimes when you try to use the in-player chat facility by pressing "enter" while a video is playing it won't let you type anything (or exit chat input mode).

**Comment by RaXorX** [comment]
@Et0h v1.6.5 works fine but I was on the current stable version 1.6.4 provided from the site itself. That one threw and still throws an error as I mentioned above.

**Comment by Et0h** [comment]
I've tested mpv.net-portable-x64-5.4.8.0 with Syncplay 1.6.5.-GIT and it seems to be working fine. It would be helpful if someone else could test it too, e.g. @grravity or @RaXorX - especially the shared playlist feature and handling of EOF.

You can get MPVNet from: https://github.com/stax76/mpv.net/releases
You can get Syncplay 1.6.5-GIT from: https://bintray.com/syncplay/Syncplay/Syncplay/v1.6.5#files
