### ISSUE TITLE
Cloudflare support

### ISSUE THREAD

**Issue by Ayrler** [Syncplay/syncplay#251]
I had no success in making my cloudflare signed certificates work with Syncplay. I couldn't find an equivalent for `cert.pem` that was mentioned in the documentation.

I have tried using [Cloudflare Origin CA — RSA Root](https://support.cloudflare.com/hc/en-us/articles/115000479507-Managing-Cloudflare-Origin-CA-certificate#h_30cc332c-8f6e-42d8-9c59-6c1f06650639) but the server kept trying to reconnect and displayed the following error ```OpenSSL.SSL.Error: [('x509 certificate routines', 'X509_check_private_key', 'key values mismatch')]```

As Syncplay server does not specifically ask for any DNS, I was wondering how it did guess the DNS and eventually if it supported subdomains.
If someone could tell me what I am missing here I would greatly appreciate it.

**Comment by albertosottile** [comment]
Hi, I read the Cloudflare link you posted here, but it is not clear to me how many and which files the Crypto app provides to you by default. 

By looking at the [Apache guide](https://www.digicert.com/csr-ssl-installation/apache-openssl.htm#ssl_certificate_install) linked in Step 2 (even though that guide seems made for Digicert and I am not sure if that exactly applies to Cloudflare as well), it seems that three files are provided. I quote:
> - **SSLCertificateFile** is your DigiCert certificate file (e.g., your_domain_name.crt).
> - **SSLCertificateKeyFile** is the .key file generated when you created the CSR (e.g., your_private.key).
> - **SSLCertificateChainFile** is the DigiCert intermediate certificate file (e.g., DigiCertCA.crt)

If this is true, I would just use the SSLCertificateFile as `cert.pem`, the SSLCertificateKeyFile as `privkey.pem`, and the SSLCertificateChainFile as `chain.pem`. Is that what you did?

**Comment by daniel-123** [comment]
Syncplay is not DNS aware in any way. It doesn't know or care what DNS your operating system is using to resolve domain names.

Syncplay requirements are pretty simplistic:
- cert.pem needs to be a PEM format file containing single [leaf certificate](https://en.wikipedia.org/wiki/Public_key_certificate#End-entity_or_leaf_certificate) - this is the bit that you get back from whoever signs your certificate after you sent them request with your public key. If you look at it with tools that can understand PEM format you'll see Common Name (CN) with your domain name.
- privkey.pem is the file with your private key (that matches to the public key you sent). It generally is generated along with public key in the very beginning of the process of getting your valid TLS certificate
- chain.pem contains intermediate certificate that was used to sign your leaf certificate. Its name always (I think so?) tells you which certificate authority has signed your certificate. In your case it will be Cloudflare.

The error you have seems to point towards something being wrong with the files. Either they don't have the contents Syncplay expects, or they are in wrong format.

That said - from glancing at your link it seems that Cloudflare Origin certificates are supposed to be used for encrypting communications between your server and Cloudflare proxies (which have the actual certificates that clients will see). Cloudflare Origin Root CA isn't trusted by normal clients so I'm unsure what exactly are you trying to achieve here? Unless you want to proxy your Syncplay connections over Cloudflare infrastructure for some reason? Even if you manage to provide this certificate to Syncplay in right format, you'd still have to manually add Cloudflare CA to trust roots of all the clients (which is almost certainly not what you are supposed to do).

**Comment by Et0h** [comment]
If my reading of https://support.cloudflare.com/hc/en-us/articles/200169156-Which-ports-will-Cloudflare-work-with- is correct then Cloudflare does not support non-HTTP/HTTPS traffic and so will not be compatible with Syncplay.

**Comment by Ayrler** [comment]
Thanks you all for your quick responses.
As @daniel-123 pointed out, I was not sure about what I wanted to accomplish. I was trying to proxy HTTPS communications on an app that didn't use HTTP(S) to begin with.
For that I would need Cloudflare Spectrum proxying which is only available in the enterprise plan as denoted above by @Et0h.
Everything is now more clear in my head!
