### ISSUE TITLE
Can syncplay provide millisecond precision playback synchronization?

### ISSUE THREAD

**Issue by wation** [Syncplay/syncplay#254]
Whether the time synchronization error can be reduced to less than 30 milliseconds can basically achieve synchronous viewing.

**Comment by wiiaboo** [comment]
I'd assume not really possible unless the syncplay client and server are as close as possible (LAN or even same computer).

**Comment by daniel-123** [comment]
Syncplay was never designed to provide millisecond precision.

It still tries to be as accurate as possible, but it generally has the following limitations:
- network jitter. Consistent ping times are accounted for. I'd assume any non-broken LAN will have both of those below 2 ms.
- ability of given player to timely execute commands from Syncplay. Especially on slow PC and with heavy file it might take some time to seek to a specific frame (it's even more complex once you get into types of frames used in video encoding).
- first player to unpause will always be slightly earlier.

If you were to have one instance of Syncplay running as a "controller" that doesn't display anything, and all the others as "slaves" they should react with very good consistency. If the server is also inside your LAN I'd expect it to get to milisecond precision most of the time. Lastly using MPV might also help as it generally is very responsive.

**Comment by Et0h** [comment]
https://syncplay.pl/guide/trouble/ notes that "Syncplay is not designed to have millisecond-level precision as this is not necessary for users to have a shared viewing experience". However, Dan's comments should be helpful for this.
