### ISSUE TITLE
Is it achievable to consider the delay between client & server？

### ISSUE THREAD

**Issue by Lqlsoftware** [Syncplay/syncplay#255]
Is it achievable to consider the delay between client & server？
My girlfriend is far between me, and my server is located in NYC.
Do we get any idea about the delay things? Maybe consider the average pings between client & server, and just adjust the speed of playing by very little to keep synchronized.

**Comment by Et0h** [comment]
Syncplay already takes latency (the delay between clients and the server) into account. I use Syncplay to watch stuff with people in other countries all the time and it works fine even when the server is in a third country. The delay in voice chat is sufficiently greater than any differences between the position of our respective media players that we never accidentally 'spoil' one another about what is coming next.
