### ISSUE TITLE
GTK scaling isn't very good with mixed DPI monitors, pyside2

### ISSUE THREAD

**Issue by Hubcapp** [Syncplay/syncplay#257]
After upgrading from syncplay 1.5.x to 1.6.5 dev, I'm experiencing poor dpi scaling. I can use the following as a workaround:

`alias syncplay='QT_AUTO_SCREEN_SCALE_FACTOR=0 /home/tyler/code/notMine/syncplay/syncplayClient.py'`

Attached are two pictures:
This is syncplay 1.6.5 on one of my low-dpi monitors (real resolution):
<img src="https://i.imgur.com/7sfq0nD.png"/>

This is syncplay 1.6.5 on my 4k monitor:
<img src="https://i.imgur.com/DUdVYZg.png"/>

This is I believe due to the new dependency on pyside2.

with QT_AUTO_SCREEN_SCALE_FACTOR turned off, the previous behavior of being legible on all monitors from syncplay 1.5 is restored.

**Comment by Et0h** [comment]
One potential change is the addition of the following to `gui.py` and `GuiConfiguration.py`:
```
if hasattr(QtCore.Qt, 'AA_EnableHighDpiScaling'):
    QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)
if hasattr(QtCore.Qt, 'AA_UseHighDpiPixmaps'):
    QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)
```
If you change `True` to `False`, does it change to a behaviour you like?

**Comment by Hubcapp** [comment]
Debian.

Possibly this is just an environment error, and I really need QT_AUTO_SCREEN_SCALE_FACTOR=0 set for all my programs, for the new behavior. I've encountered this undesirable scaling in at least 1 other program, but not all of them.

I can't check for that code change for a couple weeks, I'm away from my computer.

**Comment by Et0h** [comment]
@Hubcapp Able to check the code yet?

**Comment by Hubcapp** [comment]
A family emergency came up, and I've been still away from my computer. I'll be able to test it on Tuesday or Wednesday next week.

**Comment by Et0h** [comment]
@Hubcapp My thoughts are wish you and your family. Take as much time as you need, just let me know once you've tested it.

**Comment by Hubcapp** [comment]
Answer:

Yes, changing those booleans to False in those files fixes my issue without the QT_AUTO_SCREEN_SCALE_FACTOR environmental variable manually set (tested setting it back to True & it "broke" again)

Sorry it took so long for me to be able to test this, but good job identifying a possible fix.

**Comment by Hubcapp** [comment]
dragging the configuration window from a 4K monitor to an 800x600 monitor, the interface is usable on both with that Boolean change.

**Comment by Et0h** [comment]
Cheers. I guess the question now is which OS we want this change on because at the moment the only issue raised is presumably with respect to Linux. Does anyone have a high-DPI monitor and a Mac? If so, how does it fare?

**Comment by Hubcapp** [comment]
I'm still catching up on stuff i have to do, but when i have time, i'll setup syncplay on my mac & connect the 4k monitor to it.

**Comment by Et0h** [comment]
@Hubcapp Managed to test it on a Mac with a 4K monitor yet?

**Comment by Hubcapp** [comment]
I was able to test current master on a mac with mixed DPI monitors (after buying a new cable, but that's what you get when you buy Macs...!)

Syncplay displays normally, at a usable resolution, on 4K, 1080p, and 480p resolutions.

1080p:
![Screen Shot 2020-06-17 at 6 57 23 ](https://user-images.githubusercontent.com/1337967/84896013-ccf64380-b068-11ea-8c2d-e6dd21cd74dd.png)

4k:
![Screen Shot 2020-06-17 at 6 57 02 ](https://user-images.githubusercontent.com/1337967/84896014-cd8eda00-b068-11ea-927c-b7139ef8bf97.png)

**Comment by Hubcapp** [comment]
Current master also works for me on Linux, Issue seems to be resolved.
