### ISSUE TITLE
GUI does not start with new pyside2

### ISSUE THREAD

**Issue by tippl** [Syncplay/syncplay#259]
OS: Linux
Distribution: Arch
Versions:
* syncplay - 1.6.3-1
* python - 3.8.0-1
* pyside2 - 5.13.2-2
---
After a full system update, where python did the jump from 3.7.4-2 to 3.8.0-1, pyside2 also updated with support for it. After that, when trying to use syncplay, it does not work anymore.
Stacktrace:
```
Traceback (most recent call last):
  File "/usr/bin/syncplay", line 16, in <module>
    from syncplay.clientManager import SyncplayClientManager
  File "/usr/lib/syncplay/syncplay/clientManager.py", line 2, in <module>
    from syncplay import ui
  File "/usr/lib/syncplay/syncplay/ui/__init__.py", line 9, in <module>
    from syncplay.ui.gui import MainWindow as GraphicalUI
  File "/usr/lib/syncplay/syncplay/ui/gui.py", line 117, in <module>
    class AboutDialog(QtWidgets.QDialog):
TypeError: 'Shiboken.ObjectType' object is not iterable
```
---
Second minor issue: this issue also happens with the --no-gui option even tho the issue is with GUI libraries. Is there a way for those to not be loaded at all if the option is specified? I had to uninstall pyside2 to be able to start syncplay in no gui mode.

**Comment by tippl** [comment]
Well, it seems the issue is more with pyside2 and not really fixable here.

The update which i thought was python 3.8 support seems to only have moved libs to 38 folders but not actually add the support. A bug with Qt has been made after i first encountered the issue and didn't find anything online.

Link: https://bugreports.qt.io/browse/PYSIDE-1140

Closing this and will have to wait for an update.

**Comment by ObserverOfTime** [comment]
You can set `QT_PREFERRED_BINDING=PyQt5` but Syncplay doesn't seem to be using it.
At least the CLI works that way.

**Comment by FichteFoll** [comment]
As an update, the upstream issue has been closed, but there hasn't been a release with the fix yet. The targeted version of the fix is 5.14.

**Comment by FichteFoll** [comment]
And its finally on the main repos.

**Comment by LeKite** [comment]
Sorry to necropost this.. but I am having this very issue 4 years later. How could it be possible since it was fixed? My syncplay GUI does not open on latest version on my Arch machine..

**Comment by FichteFoll** [comment]
I suggest creating a new issue with your details, i.e. syncplay version, qt version, pyside version, traceback, etc.
