### ISSUE TITLE
Syncplay crashes before playback starts

### ISSUE THREAD

**Issue by l0cKy93** [Syncplay/syncplay#260]
OS: Linux
Distribution: Ubuntu 19.10
Python: 3.7.5rc1
syncplay: 1.6.4 
(installed via snap in --classic mode)

Syncplay crashes at the moment when i click on the "open" file" menu of the VLC player. The same happens when i drag a mp4 file into the vlc window.

There are no error messages written to the console in debug mode exept 
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-WARNING **: Loading IM context type 'ibus' failed

**Comment by albertosottile** [comment]
Hi, thanks for reporting this. What happens if you open the file from Syncplay window?

**Comment by Et0h** [comment]
Is this issue just with VLC (as opposed to mpv)? If so, which version are you using?

If you are using VLC 4 then you will have to move to mpv until we release Syncplay 1.6.5 or temporarily move away from snap to use our VLC 4 branch: https://github.com/Syncplay/syncplay/tree/VLC4

**Comment by l0cKy93** [comment]
I am using vlc 3.0.8. If I directly specify an mkv file, vlc crashes too.
I installed mpv (version 0.29.1 via apt on ubuntu 19.10) and syncplay crashes when i point it to the mpv binary

**Comment by l0cKy93** [comment]
It is interesting: If I choose an audio file, everything works fine

**Comment by Et0h** [comment]
I don't know what might be causing it. Some sort of privilege issue associated with the account running Syncplay?

**Comment by l0cKy93** [comment]
A late reply, with a solution: The prime setup of my notebook is causing the problem. 
If you have a nvidia card (with nouveau driver) just start syncplay with "DRI_PRIME=1 syncplay".
