### ISSUE TITLE
Expand protocol: "List" functionality

### ISSUE THREAD

**Issue by Slider-Whistle** [Syncplay/syncplay#263]
On sites like Cytube, I occasionally like to look through the room list and just have a look at what's going on if I find anything interesting. I don't think the situation often pops up where a person wants to watch something with their friends, and they manage to successfully convince all of them to install both this program (and Python which they haven't got it already, which will be most windows users), and then start watching their movie because to most people that's just not worth the effort. Especially considering that in private circles like this, they'll probably just prefer to time it all over voice chat anyway. I think that a lot of people install this program, look for other people using it, and then stop altogether when they realise they can't find anyone.
Therefore I think it's better to emphasise this model where people using this program can just find eachother naturally, using the server at syncplay.pl, and then the program will start to become more and more popular.

I understand that some people already running syncplay rooms might be uncomfortable with the idea that the server's going to just automatically start listing their rooms (how many rooms are there at the moment anyway?), so I guess you can tag this "WONTFIX" if it's not meant to be that kind of program.

Anyway, as for how I imagine it being implemented, I guess it could be added as a chat command (this would need you to be in a room already though, maybe it'd be better if you didn't need to join a room to connect to a server) and stuffed somewhere in Syncplay's "join server" and room GUI windows.

**Comment by Et0h** [comment]
Syncplay is primarily designed to be used by people who know one another. It also supports managed rooms to allow for existing communities to arrange to watch stuff together.

I can see exactly where you are coming from and agree that operating a Syncplay matchmaking service could help make Syncplay more popular, but we don't have any plans to go in that direction. I'm sure if someone wants to do that then they can make a third-party Reddit for it or something, but this is software we develop in our spare time and don't make money off so we don't want to create the added burden of having to administer a matchmaking service.

Public servers run in 'room isolation' mode which means that you can't see what is happening in other rooms. This is both for privacy purposes and to discourage people joining random rooms to cause disruption, and effectively makes the room name a password. Those running private servers can disable this feature which means that when you join the server (which can be password protected) you can see what is happening in other channels. As such, anyone wanting to create an open server where anyone can connect and see what others are watching are free to do so, but that isn't something we want for our public server.

**Comment by Slider-Whistle** [comment]
Okay, I understand. I didn't know about that feature either, it sounds helpful.
