### ISSUE TITLE
Youtube-dl cuts connection between syncplay and mpv

### ISSUE THREAD

**Issue by lc-guy** [Syncplay/syncplay#265]
Playing any youtube video will cut the connection between mpv and syncplay. The video plays fine, but seeking/pausing/changing video doesn't work anymore, syncplay automatically quits after 60 seconds because it can't detect the player, and messages don't appear in the GUI. (typing a message will send it correctly, though)
arch linux, latest syncplay appimage release, mpv 0.30.0, youtube-dl-git (built on 2019-11-28)

**Comment by Et0h** [comment]
Things work fine for me on Windows when I use mpv and YTDL, so the issue might be the AppImage. Does it work fine if you run Syncplay through other means on Arch?

**Comment by lc-guy** [comment]
Same thing happened before I updated, back when I was using the AUR package. (switched to appimage temporarily because of the pyside bug)

**Comment by daniel-123** [comment]
I've just tried this on my Debian with mpv 0.30.0, youtube-dl 2019.09.28 and Syncplay git master. It works as you'd expect, though my youtube-dl is 2 months old.

Do you have an easy way to test with older version of youtube-dl?

**Comment by lc-guy** [comment]
Bug present as far back as youtube-dl 2019-10-29, can't test with older versions as they do not run with latest python on arch

Can also confirm it happens whenever youtube-dl handles a video, not just youtube

This doesn't happen when I try to load a .webm directly from an url, since that seems to be handled directly by mpv with no need for ytdl.

**Comment by lc-guy** [comment]
Fixed by removing "profile=gpu-hq" from my mpv config, which apparently interacted weirdly with syncplay on my machine.
