### ISSUE TITLE
Honor mpv HTTP headers when streaming videos

### ISSUE THREAD

**Issue by LiteracyFanatic** [Syncplay/syncplay#266]
Some streaming sites require certain HTTP headers to be set in order to play properly. For example, using plain MPV, `mpv 'https://twist.moe/anime/trigun/[a-s]_trigun_-_01_-_the_$$60_billion_man__rs2_[590CCDF8].mp4'` fails but `mpv --referrer 'https://twist.moe/' 'https://twist.moe/anime/trigun/[a-s]_trigun_-_01_-_the_$$60_billion_man__rs2_[590CCDF8].mp4'` works fine. I've tried adding `--referrer 'https://twist.moe/'` to the player arguments in the settings window, but syncplay still fails to load the video.

**Comment by Et0h** [comment]
I have no idea how the mpv referrer system works, so you might need to do some more research and figure out how to implement it yourself (or find someone who can) if you want this feature.

**Comment by Et0h** [comment]
@LiteracyFanatic Does running Syncplay 1.6.7 and under 'Player Arguments' specifying referrer=URL work?

**Comment by LiteracyFanatic** [comment]
Unfortunately it still doesn't work. I've attached a log file. This line stood out to me.

```
player >> ['loadfile', 'https://twist.moe/anime/trigun/[a-s]_trigun_-_01_-_the_$$60_billion_man__rs2_[590CCDF8].mp4']
```

Maybe this needs to be handled from lua. Perhaps loading a URL from lua doesn't respect the command line options.
[log.txt](https://github.com/Syncplay/syncplay/files/5432859/log.txt)

**Comment by Skrity** [comment]
It works but something happens with quotes that breaks it.

If I put `referrer=https://twist.moe/` into arguments _exactly_ like this it works, if you put quotes around the website mpv seem to inherit them and put them into the variable which _presumably_ breaks parsing on mpv/ffmpeg's end.
Dunno if problem is in syncplay or mpv, but seems like a serialization issue.

This doesn't happen when you put `referrer="https://twist.moe/"` into mpv.conf or use input.conf binding `w cycle-values referrer "https://twist.moe/" ""`.

To check this enable mpv console and do `show-text ${referrer}`. The referrer variable shouldn't contain any quotes.

**Comment by Et0h** [comment]
I've not tested your particular use case but I have added some code to strip quotation marks from the beginning and end of per-player arguments which hopefully resolves any Syncplay-side issues with handling player arguments (https://github.com/Syncplay/syncplay/commit/5c3982f313114d14a8cfd693d827ddd846cefb5b).
