### ISSUE TITLE
Mac: Add file menu is in German and sometimes pops up on its own.

### ISSUE THREAD

**Issue by Duamer** [Syncplay/syncplay#268]
Syncplay version 1.6.4a
macOS: 10.14.6

The menu for "Add file(s) to bottom of playlist" is stuck in German and will sometime pop up on its own. System's language setting is English(US) and this is the only menu that's in German. The menu will sometimes pop if there's a few files in the playlist, but no files will appear. At least, I haven't noticed it when it's empty. If I open the menu normally, a second menu will appear on top of the glitched on and both ill disappear. 

Neither problem is effecting functionality.

Here's a screen grab of the language issue. Next time I see the menu that's glitched, I'll screen grab that.
https://i.imgur.com/h6tm6Oy.png

**Comment by Et0h** [comment]
As far as I know this issue will be fixed in the next version of Syncplay: https://github.com/Syncplay/syncplay/commit/5aee6d97c916e4e6b8fc05c988ebd16409a26b94#diff-f2f4408f1aa0211e78de0c32bf8765dc

**Comment by Et0h** [comment]
You can test out the latest development version of Syncplay at https://bintray.com/syncplay/Syncplay/Syncplay/v1.6.5#files to confirm whether or not it resolves your issue.

**Comment by Duamer** [comment]
1.6.4 fixes the problem that 1.6.4a had. 

1.6.5 has a different problem that makes it unusable though. I'm going to see if it happens on more than one machine before submitting a bug report, but when I launch it on the one machine, the icon is the Syncplay icon while loading, then turns into VLC and VLC is what actually loads.

**Comment by Et0h** [comment]
Okay, in that case I'll close this issue as it's resolved in 1.6.5 and if you can confirm your other issue then you can make a new issue for it.
