### ISSUE TITLE
"mpv-version-error" is very misleading when entering incorrect player arguments

### ISSUE THREAD

**Issue by Gnuxie** [Syncplay/syncplay#270]
https://github.com/Syncplay/syncplay/blob/4765fa452caba35793003e48c953ddfddd7a05e0/syncplay/players/mpv.py#L101

I've been fooled by this for a month thinking my distros mpv version was bad and actually i had just accidentally entered garbage into the player arguments.

**Comment by Et0h** [comment]
You're right, that is confusing. Thanks for reporting the issue and sorry about any confusion!

**Comment by Et0h** [comment]
I've hopefully resolved this issue with 5df3046287523f3df65c350b91a429fe39152dcd.

**Comment by Gnuxie** [comment]
I'd say so :)
