### ISSUE TITLE
Trying to bind to IPv6 while disabled and failing to start

### ISSUE THREAD

**Issue by Flutterr** [Syncplay/syncplay#271]
I have IPv6 disabled on my ubuntu machine due to DynDNS issues, so turning it back on is not an option for me. However, when I start syncplay-server, it tells me it

"Couldn't listen on :::8999; [Errno 97] Address family not supported by protocol.
IPv6 listening failed".

Is there any way to make my server bind to a certain address, or to disable ipv6 support? Why doesn't it try to bind to a IPv4 address instead?

**Comment by daniel-123** [comment]
Do you have any IPv6 entries leftover in your /etc/hosts file?

**Comment by albertosottile** [comment]
@Flutterr I am not sure I understood your issue. Did you try to connect on the server via IPv4? If you disabled IPv6 on that machine, that log message is completely normal. The server tries to bind first on IPv6+IPv4, then, if it fails, it binds only on IPv4 (which I think is what happened in your case). If both binding attempts fail, the server process closes itself with this log message: "Unable to listen using either IPv4 and IPv6 protocols. Quitting the server now.".

**Comment by Flutterr** [comment]
I will try looking at my hosts file tomorrow. To specify, @albertosottile, I am trying to host a syncplay-server on a machine that has ipv6 disabled. The server apparently only tries to bind to ipv6, as there is no reason binding to an ipv4 address wouldn't work, and it fails and stops the server with the message "IPv6 listening failed.", however I don't even want it to use IPv6 at all.

**Comment by Et0h** [comment]
@Flutterr Have you tried connecting to the server via ipv4 after it gives the error? If so, what happens?

**Comment by Flutterr** [comment]
Yup, tried it out and the error message did not prevent the server from starting, I can connect via IPv4. Thanks a lot!
