### ISSUE TITLE
Adding URL (or path) to the playlist from the clipboard

### ISSUE THREAD

**Issue by FichteFoll** [Syncplay/syncplay#272]
I'd love to be able to add a URL (maybe also a path, but I personally don't really need that since you can drag) from the clipboard by just pressing ctrl+v. 

Currently I need to right click on the playlist view, select the correct item and *then* paste the url into the popup and then also hit "OK".

**Comment by Et0h** [comment]
My main concerns about a context menu or button to paste from clipboard to the playlist are (a) it adds clutter, and (b) you might accidentally have the wrong thing in your clipboard compared to what you expected.

However, I do think it could be good to have an easier way to add things to the end of the playlist - one option is to add it as a console option which people can access via the chat box. This means people can add something like "/add [path]" or "/a [path]" and can visually review it in the chatbox before pressing enter or "send". What do people think about this?

**Comment by FichteFoll** [comment]
> it adds clutter

In which way? I mean the menu entry, yes, probably, but they key binding certainly not. If you're opening the menu für this, you'd probably be okay with choosing the current item for that anyway.

> you might accidentally have the wrong thing in your clipboard compared to what you expected.

Hm, that may or may not be an issue. The log doesn't show how the playlist has been modified, so you could still delete it quickly, hopefully, but leaking passwords for example would of course be a problem. Either a console or an OK-Cancel dialog would be able to allow the user to review their clipboard contents and I would be fine with either. The former is better for correcting mistakes while the latter needs less key inputs.

Also, this is in part related to https://github.com/Syncplay/syncplay/issues/232, which would allow for scripting this.

**Comment by Et0h** [comment]
Closing this issue as the ability to add files via the chat box would be resolved by #262 (and doing it another way would would have drawbacks as discussed). Thanks for sharing your thoughts and ideas.
