### ISSUE TITLE
TLS connection fails when starting with video file

### ISSUE THREAD

**Issue by Corship** [Syncplay/syncplay#278]
TLS works when starting syncplay and joining the room before selecting a video.
When I join the room with a video pre selected results in the TLS error message "this client does not support TLS"
Version 1.6.4

**Comment by Et0h** [comment]
Thanks for reporting this. I think the issue might be because opening a file with Syncplay changes the working directory.

**Comment by albertosottile** [comment]
Most likely the change in the working directory affects the loading of `cacert.pem` which happens here: https://github.com/Syncplay/syncplay/blob/bf5c8dd531a5c88479d17f290ec8bdfda425b12a/syncplay/client.py#L20

I would investigate this code on Windows after Syncplay is opened from the contextual menu of a file.

**Comment by daniel-123** [comment]
@Corship on what operating system have you seen this issue? What installation method did you use?

**Comment by Corship** [comment]
Hello :)
I hope I can give some more insigths about the setup.
I watch on a linux machine, compiled from source and there it works flawlessly.
The person watching with me, uses a windows 10 machine and downloaded from the https://syncplay.pl/ site.
Sadly i do not own a windows machine, so I can only forward what they told me:
------------------------------
The tls connection works when connecting to the server if no video is preselected, but if I set syncplay as default video viewer for the file type or use "open with" option it says the connection is not secure. aka no green lock in the top corner.
-----------------------------------
I hope this helps.

**Comment by albertosottile** [comment]
This issue should be solved in the latest version of `py2exe` (https://github.com/albertosottile/py2exe/releases/tag/v0.10.0.1).

I tested a build of Syncplay 1.6.6 made with that version and I was unable to reproduce the bug with it. In case you are interested in testing the fix, you can find the custom build here: https://bintray.com/alby128/Syncplay/Syncplay/v1.6.6#files .

In any case, we will probably upgrade our Windows build chain to `py2exe` 0.10.x starting from the next version of Syncplay (1.6.7).
