### ISSUE TITLE
Typo in client.py:FileSwitchManager.setClient()

### ISSUE THREAD

**Issue by SiIky** [Syncplay/syncplay#282]
Shouldn't it be `_client` here? I see that `setClient()` isn't used right now, but it could be the origin of a bug in the future.

https://github.com/Syncplay/syncplay/blob/bf5c8dd531a5c88479d17f290ec8bdfda425b12a/syncplay/client.py#L1900

**Comment by Et0h** [comment]
Nice catch. I think you're probably right on both counts.
