### ISSUE TITLE
timestamp-based approach during streams results in desynchronization

### ISSUE THREAD

**Issue by prez** [Syncplay/syncplay#284]
Steps to reproduce:
1. user A switches tracks to e.g. an mp3 stream
2. user B does not switch immediately. User A's stream continues to play in the meantime.
3. when user B switches tracks after some amount of time, user A's stream gets reset to 0.00 - 
the timestamps are now synced, but the only way to sync back the stream's contents is to change the track twice for all users. 3. can also happen if e.g. another user joins.

I am not sure if there even is a mechanism to solve this problem right now, but it might be a good idea to leave this issue open until there is.

**Comment by lc-guy** [comment]
Another case where this would happen:

- All users are watching an mp3 stream
- Some user joins the room, starts at 0.00

**Comment by Et0h** [comment]
If you're using Syncplay to play music then consider the following:
1. Use mpv version 0.6.2 and youtube-dl, not other media players.
2. Use shared playlists feature 
3. Try the development version of Syncplay 1.6.5 available from https://bintray.com/syncplay/Syncplay/Syncplay/v1.6.5 to see if you like the 4765fa452caba35793003e48c953ddfddd7a05e0 feature for seamless playlist advancement for shared playlists using mpv.
4. Use shared playlists.
5. Depending on circumstances, you may also want to try using managed playlists as per https://syncplay.pl/guide/client/

Given then Syncplay only has limited control over how streams work, I'm not sure what more we can do to improve the payback experience in your circumstance. However, it would be useful to know the extent to which the above measures improves matters.

**Comment by seitokaichou** [comment]
Thank you for the quick response! 

I'm not sure how the shared playlist feature would help here, as the issue would still occur if a third user would join a room with a stream playing, but maybe I am misunderstanding you.

I will try the seamless playlist advancement once v1.6.5 is in the repos of my distro and report back.
