### ISSUE TITLE
Language detection does not work correctly

### ISSUE THREAD

**Issue by v-ji** [Syncplay/syncplay#288]
Hi everyone,

The code for [getInitialLanguage()](https://github.com/Syncplay/syncplay/blob/3c273417f826221600703170b71d5965442d1d13/syncplay/messages.py#L46) does not seem to be working correctly across platforms.

On macOS, it automatically sets Syncplay to English even though my system language is German. Python’s `locale.getdefaultlocale()` returns `('en_GB', 'UTF-8')`. After a bit of searching it seems like unfortunately, there is no straightforward cross-platform way to get the system language in Python.

Is this working correctly for users on other platforms or other macOS users?

**Comment by Et0h** [comment]
It's a shame it doesn't work, but not sure if there is a fix other than manually setting the language, e.g by following the guidance at https://syncplay.pl/guide/client/ and:
- Clicking the "Show more settings" checkbox in the configuration window, then going to "Messages", then selecting Language -> Deutsch.
- Running Syncplay with the `--language de` command line switch

**Comment by Et0h** [comment]
@vaviary What result do you get from `locale.getpreferredencoding()` on macOS?

**Comment by vaviary** [comment]
Sorry, I made a dumb mistake there: My `.zshrc` had the line `export LC_CTYPE=en_GB.UTF-8`. Launching Python in Terminal.app without a shell it returns the following:

```python3
>>> locale.getpreferredencoding()
'UTF-8'
>>> locale.getdefaultlocale()
('de_DE', 'UTF-8')
```

Where does Syncplay get its locale from, then?

**Comment by Et0h** [comment]
I don't know as I don't use macOS. Are you using the AppImage available from https://github.com/Syncplay/syncplay/releases/download/v1.6.4a/Syncplay_1.6.4a.dmg and/or the slightly more recent experimental one available from https://bintray.com/syncplay/Syncplay/download_file?file_path=Syncplay-1.6.5-x86_64.AppImage ? Is there a difference between the two?

**Comment by vaviary** [comment]
I’m using the latest GitHub release as installed by Homebrew, so version 1.6.4a.

I went ahead and downloaded the [1.6.5 .dmg from Bintray](https://bintray.com/syncplay/Syncplay/download_file?file_path=Syncplay_1.6.5.dmg) (I think you accidentally linked to the AppImage). Unfortunately, it still detects English as the system language.

**Comment by albertosottile** [comment]
Interesting... Which version of macOS do you have? Can you make a screenshot of the Language & Region settings in System Preferences? I am interested in what languages are listed there and in which order. Thank you.

**Comment by vaviary** [comment]
I’m using macOS Catalina 10.15.3 and here’s a screenshot of the language settings menu:

<img width="762" alt="Bildschirmfoto 2020-04-06 um 11 55 24" src="https://user-images.githubusercontent.com/1476338/78546493-cabc7100-77fd-11ea-84bb-495d963402c9.png">

German is the primary language on the left (“Primär”).

**Comment by JBeckwith** [comment]
Would just like to add that this appears as an issue in the "inverse" - the language will be set to German on a Mac with English set as the default language.

**Comment by pratyushmanocha** [comment]
Hi, I would like to mention that even I am facing this issue but in my case, the language displayed to me is Russian. My default language is English but I have no clue how this is happening. In addition to this, I am unable to add a server password in the password field in the gui config panel. 

I tried running Syncplay from the cli using the -g argument that forcefully brings up the gui.  This allows me to modify the password field (only in this session) but the on-screen language for the Mac OS folders is still Russian. 

I installed Syncplay using brew cask install syncplay and am running it on MacOS Catalina. 

Apart from this, I have been facing a few more issues and if possible, would like to create another discussion thread for them. 

I would be glad to furnish any more information that would be required. 
Thanks in advance.

**Comment by albertosottile** [comment]
@v-ji I just reproduced the issue in my local testing virtual machine. I will try to investigate it as soon as I can.

@JBeckwith @pratyushmanocha I think we are mixing different issues here. The original issue is that the GUI is displayed in English even though the System language is set to a different, supported one (e.g. German). If you are experiencing other bugs, please open new issues in the tracker. Please note that a language issue has been solved in the unreleased 1.6.5 version linked above (https://bintray.com/syncplay/Syncplay/download_file?file_path=Syncplay_1.6.5.dmg). I would encourage you to test it before opening a new issue.

**Comment by albertosottile** [comment]
Hello @v-ji, I just prepared a build with a fix for this issue in my fork. Could you download this version from https://bintray.com/alby128/Syncplay/download_file?file_path=Syncplay_1.6.5.dmg and test in on your system? Please, let me know if the correct language is shown when you use this build.

**Comment by v-ji** [comment]
I just tested it and it works flawlessly!
<img width="881" alt="Bildschirmfoto 2020-04-24 um 13 46 24" src="https://user-images.githubusercontent.com/1476338/80209263-05ae0980-8632-11ea-98d7-56410107b875.png">
