### ISSUE TITLE
Add flags for disabling file name/size/duration warnings

### ISSUE THREAD

**Issue by MikeRixWolfe** [Syncplay/syncplay#303]
It would be nice if there was a launch flag to disable the warnings for file differences since users may be obtaining copies of movies from various sources they are not guaranteed (or in my experience, likely) to match exactly. It would be nice to be able to disable the warning that flashes constantly when the movie isn't being played.

**Comment by Et0h** [comment]
If you run Syncplay and in the settings dialogue click "Show more settings" and go to "Messages" then you can uncheck "Include warnings" and/or "Warn about media duration mismatches" to change the behaviour.

**Comment by MikeRixWolfe** [comment]
This works, thanks
