### ISSUE TITLE
Bump python version to 3.8

### ISSUE THREAD

**Issue by ElDavoo** [Syncplay/syncplay#304]
Hello,
I tried compiling and using syncplay with python 3.8 and it works fine. Is it possible to officially support it?

**Comment by daniel-123** [comment]
I'm not sure what do you mean by "officialy support it". Only statement about supported Python version is the one that 3.4 or newer is required.

**Comment by Et0h** [comment]
Sorry, I don't understand what you mean either because Syncplay officially supports Python 3.8.

**Comment by Et0h** [comment]
https://github.com/Syncplay/syncplay/commit/e736ba5a46cfbc6f7bfa2cde48f65d890989fcd7 might be what you were asking about

**Comment by ElDavoo** [comment]
thank you :)
