### ISSUE TITLE
How to build the dmg file for mac

### ISSUE THREAD

**Issue by devpro9219** [Syncplay/syncplay#308]
Hi. I am trying to build the dmg file, however, once I build the dmg file, it's not working on Mac. 
It doesn't open at all. 
Can you please guide me on how to build the dmg file correctly? 

Thank you. 
Miguel

**Comment by Et0h** [comment]
I'm not responsible for the macOS version but looking at https://github.com/Syncplay/syncplay/blob/master/.travis.yml and https://github.com/Syncplay/syncplay/blob/master/buildPy2app.py might be of assistance. Why do you need to build your own dmg file?

**Comment by Et0h** [comment]
If you want the latest development builds of Syncplay then they are available from: https://bintray.com/syncplay/Syncplay/Syncplay/v1.6.5#files

**Comment by Et0h** [comment]
We do not prov
