### ISSUE TITLE
Weird behaviour if you disconnect a screen

### ISSUE THREAD

**Issue by DieNand** [Syncplay/syncplay#325]
After disconnecting my external monitor from my laptop and connecting to the server the window disappears (as if still trying to display on the other screen).

This even happens after a reboot with the external monitor still disconnect.

**Comment by Et0h** [comment]
Try running Syncplay with the --clear-gui-data command line switch and see if that fixes it.

**Comment by DieNand** [comment]
Ah thanks, yeah that fixed it!

**Comment by daniel-123** [comment]
Just for curiosity sake: what window manager/OS even allows such behavior?

**Comment by DieNand** [comment]
Windows 10. 🤦‍♂️

**Comment by Et0h** [comment]
Yes, this is a known Windows issue. There is even a page at https://support.microsoft.com/en-gb/help/181691/some-programs-are-displayed-off-the-screen which describes a number of workarounds to resolve the issue.
