### ISSUE TITLE
Youtube(-DL) Automatic Subtitle Option

### ISSUE THREAD

**Issue by Fidgetcetera** [Syncplay/syncplay#332]
Youtube-DL has the option to download auto generated subtitles, which I believe can hold a preference towards manual subtitles first. It'd be nice to also have this option in Syncplay, as when a video is not captioned, I need at least automatic captions.

**Comment by daniel-123** [comment]
In theory Syncplay allows you to pass arbitrary option to the player (mpv in this case), which in turn accepts option to pass parameters to ytdl: `--ytdl-raw-options=<key>=<value>[,<key>=<value>[,...]]`. Does that work for you?

You should add it in "Player Arguments (if any)" box which appears if you enable “Show more settings”.

**Comment by Et0h** [comment]
It is possible that changes to Syncplay to move mpv to the new API mean it doesn't like having multiple = within a passed command line any more, as such this would need testing.

**Comment by Et0h** [comment]
Issues with passing = in arguments should have been resolved by #333 so you should now be able to get subtitles using Dan's proposed solution.
