### ISSUE TITLE
Syncplay now crashes when passing player arguments that worked fine before

### ISSUE THREAD

**Issue by alexbobp** [Syncplay/syncplay#333]
It is common for my friends to keep the following in their player arguments field: `--ytdl-format=bestvideo[height<=1080]` in order to reduce bandwidth by not streaming youtube videos and the like in 4K.  With the latest syncplay, these player arguments started causing immediate crashes of syncplay/mpv, even before any media attempts to load.

Specifically, we tested this on windows, using mpv.exe as the player.

I narrowed down the issue to the `=` character.  Specifically, I can use `--ytdl-format=bestvideo[height<1081]` as a workaround.  I hope this helps diagnose the bug.

**Comment by Spincervino** [comment]
I have this problem too, removing the = sign from commands lets syncplay start normally. 
Before version 1.6.4a i did not have the problem.

**Comment by Et0h** [comment]
Thanks for reporting this issue. Is it resolved by f7ca631e08564db92508b183fa81622c4df16fcd?
