### ISSUE TITLE
Unable to change chat fonts

### ISSUE THREAD

**Issue by julioea** [Syncplay/syncplay#338]
Running on Archlinux
Software versions 
`syncplay 1.6.5-1`
`python 3.8.3-1` 
`python-twisted 20.3.0-1`
`python-pyside 1.2.4-10`
`python-pyside-common 1.2.4-10`

When I try to change the font settings through the GUI but they always returns to the default value.

Workaround:
Changing default settings in `constants.py`.

Log:
```Traceback (most recent call last):
  File "/usr/lib/syncplay/syncplay/ui/GuiConfiguration.py", line 1016, in <lambda>
    self.chatOutputFontButton.released.connect(lambda: self.fontDialog("chatOutput"))
  File "/usr/lib/syncplay/syncplay/ui/GuiConfiguration.py", line 1059, in fontDialog
    self.config[configName + "FontFamily"] = value.family()
AttributeError: 'bool' object has no attribute 'family'```

**Comment by Et0h** [comment]
It works fine for me on Windows so it might be a Linux/Ubuntu (or Linux implementation of Python or PySide) issue.

**Comment by Et0h** [comment]
The following has been added to https://syncplay.pl/guide/trouble/

**I tried changing the chat font, but it didn't work**

- Manually change the font by modifying the configuration file (syncplay.ini / .syncplay).
- The relevant options for chat input be in the [gui] group are: chatInputFontFamily, chatInputRelativeFontSize, chatInputFontWeight, chatInputFontUnderline, and chatInputFontColor.
- The relevant options for chat put be in the [gui] group are: chatOutputFontFamily, chatOutputRelativeFontSize, chatOutputFontWeight, and chatOutputFontUnderline.

**Comment by daniel-123** [comment]
I'm not sure what was the original cause of this problem, but I haven't managed to reproduce it on Debian 11 with Syncplay 1.6.7. So it's probably not something Linux specific, but might be either related to the specific config @julioea is running or Arch in general.

I'd assume that by now arch has latest pyside2 and such, does the problem still occur?
