### ISSUE TITLE
Weird output when using quotes in chat.

### ISSUE THREAD

**Issue by Yzuriha** [Syncplay/syncplay#342]
Whenever I use quotes ("), the output in MPV gets like this: https://i.fiery.me/FPFIP.png
In the normal client is looks fine.
This issue came ever since I updated to the new version of Syncplay.

**Comment by AtilioA** [comment]
This has been addressed in 1ad10632c6f027f8de74bcf211b4bf872c5e2678. You will have to build Syncplay yourself or wait until the next release (which will include the fix).

**Comment by AtilioA** [comment]
This has been addressed in 1ad1063. You will have to compile Syncplay yourself or wait until the next release (which will include the fix).
