### ISSUE TITLE
Windows XP support

### ISSUE THREAD

**Issue by maximilliangreat** [Syncplay/syncplay#347]
Hi!
1.6.5 do not run in WinXP. I tried up to 1.6.0, older versions are removed from site.
Is latest version supposed to run under XP? If not, where can I find last version which supported WinXP?

**Comment by daniel-123** [comment]
Windows XP is not supported as it's already long past its end of life.

You can find legacy versions of Syncplay on [releases page on this github repo](https://github.com/Syncplay/syncplay/releases). Some old version should work assuming you'll also use a media player that's compatible with that particular Syncplay version and Windows XP.

**Comment by maximilliangreat** [comment]
> Windows XP is not supported as it's already long past its end of life.
> You can find legacy versions of Syncplay on releases page on this github repo. Some old version should work assuming you'll also use a media player that's compatible with that particular Syncplay version and Windows XP.

old versions (compiled) are missing from GitHub, they were hosted on syncplay.pl. Links are dead (404) now.

**Comment by daniel-123** [comment]
Hmm, you are right.

Then there still is old repository on sourceforge: https://sourceforge.net/projects/syncplay/files/ .

**Comment by maximilliangreat** [comment]
Thanks. 1.5.5 is the last one with XP support. Works fine.
Probably worth mention on site, like VLC still hosts version  for Windows 95/98/Me :)

**Comment by Et0h** [comment]
Windows XP is no longer getting security updates and so I cannot recommend connecting it to the internet.
