### ISSUE TITLE
Question: Is syncplay messages encrypted or logged?

### ISSUE THREAD

**Issue by lilcsz** [Syncplay/syncplay#349]

**Comment by daniel-123** [comment]
Official server code can optionally gather very basic usage stats: number of connected clients and their version. This is what you can expect when connecting to official servers.

Client has option to do pretty detailed debug logging, but only has access to your local information and whatever server sends. Which is user names, room names, playback state and messages. There is also file size and name which by default are shared, but you can choose in client settings to just send a hash of those or nothing at all - which limits functionality of playlist synchronization for obvious reasons.

Modern Syncplay versions by default use strong TLS encryption when connecting to server which is configured to use it. That said - currently this is not enforced so it's always possible to initiate unencrypted connection. As how that relates to messages:

- They are encrypted if all clients are 1.6.4 or newer and server is configured to use TLS. Any client that's older will receive and send messages unencrypted.
- Every client which is connected to given room has full access to all messages that it received and can log them.

In the end it's worth keeping in mind that Syncplay is not designed to be a secure communications platform. Its primary purpose is to send playback state of video player which is not sensitive information at all (sending filenames is optional). There is no end-to-end encryption and both permission system and password support are extremely rudimentary. What TLS support is there, is mainly to ensure that the server you are connecting to is what you think it is.

**Comment by lilcsz** [comment]
thanks

**Comment by arkangel-dev** [comment]
Can I temporarily disable TLS for testing purposes?

**Comment by daniel-123** [comment]
@arkangel-dev TLS in Syncplay is opportunistic in first place. There is no "switch" to enable or disable it, it will always try to use it if it's possible. It's very easy to make it impossible by either running a server without TLS encryption or by not allowing the client access to TLS libraries.

**Comment by Et0h** [comment]
A hacky way to do it would be to temporarily set your clock forwards a few years which will make Syncplay reject the certificate of the server you connect to, but it will also prevent you from visiting any websites until you've changed it back (and you might even need to restart your browser to get it working again). See https://kb.wisc.edu/helpdesk/page.php?id=79027 for instructions on how to do this on Windows 10.
