### ISSUE TITLE
IINA Support

### ISSUE THREAD

**Issue by Boundarybreaker** [Syncplay/syncplay#359]
[IINA](http://iina.io) is an mpv-based video player for MacOS, similar to what mpv.net is for Windows. From what i can tell, it should function effectively identically to mainline mpv in terms of syncplay integration, but due to having a different name syncplay can't recognize it.

**Comment by Et0h** [comment]
@Boundarybreaker A test build of PR #360 which introduces IINA support to Syncplay is available for testing from https://bintray.com/alby128/Syncplay/download_file?file_path=Syncplay_1.6.7.dmg - If you can try it out and let us know if it works then that'd be great.

**Comment by Boundarybreaker** [comment]
I'll test it as soon as I can!

**Comment by Boundarybreaker** [comment]
It looks to work mostly well! It looks like IINA has built-in youtube-dl, so if it could use that instead of Brew's it'd be really good, since Brew youtube-dl doesn't seem to work for me. I also can't figure out how to get the chat prompt up in IINA like I can in mpv.

**Comment by albertosottile** [comment]
It looks like IINA is not passing keystrokes to mpv so, at the moment, I am afraid that we cannot support in-player chat on IINA. Further limitations can be found here: https://github.com/Syncplay/syncplay/pull/360. 

About youtube-dl, we do not force the use of the Brew version in our code. Hence, whatever is happening on your system might be something related to IINA, mpv, or the installations of youtube-dl. How did you determine that the Brew version was used by IINA? Can you try uninstalling or simply unlinking the Brew version of youtube-dl to see if this makes any difference?

**Comment by Boundarybreaker** [comment]
I'll take a look at it. I've assumed it's the Brew version since updating the Brew ver previously fixed issues with it, but it seems to have stopped working so it might be using a different version now.

**Comment by Boundarybreaker** [comment]
Weird...if IINA is launched through the Mac app package, it downloads youtube videos just fine. However, if it's launched through syncplay, even manually adding a youtube link to IINA fails. That's...really weird. I've got the most recent youtube-dl both on pip and brew, and I'm not sure where else it might be. I wonder what's going on...

**Comment by albertosottile** [comment]
I am actually unable to reproduce on my system but I can imagine why this is happening... Could you please try again to use youtube-dl with this build: https://bintray.com/alby128/Syncplay/download_file?file_path=Syncplay_1.6.7.dmg ? Please re-download it as Travis changed the file content/

Thanks again for your time.

**Comment by Boundarybreaker** [comment]
That works!!! Thank you so much.
