### ISSUE TITLE
Options on start up

### ISSUE THREAD

**Issue by MarisKori** [Syncplay/syncplay#361]
I chose "do not show this dialog on start up" (about options), but it is shown again and again each time I start the Syncplay.
v1.6.6 beta 2 (release 89)

**Comment by Et0h** [comment]
Do you mean the _"Don’t always show the Syncplay configuration window"_ option?

As noted in the tooltip text and the guide at https://syncplay.pl/guide/client/ this option only means that Syncplay won't open the configuration window if you open a file with Syncplay unless you need to specify configuration options. If you are running Syncplay directly then it will always display the configuration window irrespective of what you choose for that option.

**Comment by MarisKori** [comment]
Yes, I meant exactly than option. I translated it from Russian. And in Russian it sounds like "Don't show the Syncplay configuration window at all".

**Comment by Et0h** [comment]
I just checked and you're right, according to Google "Не показывать больше этот диалог" translates to "Don't show this dialog again". Can you please review this @and-semakin ?

**Comment by Et0h** [comment]
@MarisKori If you let me know what the Russian translation should be then I can change it. @and-semakin can then tweak if it needed.
