### ISSUE TITLE
Refresh filesize for display

### ISSUE THREAD

**Issue by FichteFoll** [Syncplay/syncplay#362]
When a file is still being downloaded, the file size at the time is loaded and shown in the "who is playing what" list, but this is never refreshed. It would be nice if it was refreshed every 10s or so (until it doesn't change anymore, if this is a problem).

**Comment by Et0h** [comment]
This is related to #345 which wants a manual metadata refresh option.

**Comment by FichteFoll** [comment]
True, that sounds like the same thing but manual. I'll add this to that issue.
