### ISSUE TITLE
Syncplay doesn't always syncronize with VLC

### ISSUE THREAD

**Issue by JacopoMolteni** [Syncplay/syncplay#365]
In some occasions when I start Syncplay VLC starts but it doesn't pickup the playlist and doesn't sync the commands (play, pause and so on). When this happens if I close Syncplay the VLC windows stays open and I have to manually close it. The issue is sometimes solved restarting Syncplay multiple times, other times I have to restart the PC. I'm on Windows.

**Comment by Et0h** [comment]
I don't have that issue, but I think I might have identified and fixed it. Unfortunately, I can't easily test it.

@JacopoMolteni Please try 1.6.7 development version from https://bintray.com/syncplay/Syncplay/Syncplay/v1.6.7#files (Syncplay-1.6.7-Setup.exe or Syncplay_1.6.7_Portable.zip) and let me know whether or not it fixes it.

**Comment by JacopoMolteni** [comment]
@Et0h thank you very much, I've tried to open it a few times and it seems to work. I'll use it more in the next few days and I'll let you know if I encounter the issue again

**Comment by JacopoMolteni** [comment]
Ok after some time I feel positive the issue is fixed. Thank you for the help.

**Comment by Et0h** [comment]
> Ok after some time I feel positive the issue is fixed. Thank you for the help.

Great to hear, thanks for the update. Hope to get an official beta out soon for 1.6.7.

**Comment by jvschiavo** [comment]
Do I need to have the same version of syncplay as my friends to work?

**Comment by Et0h** [comment]
> Do I need to have the same version of syncplay as my friends to work?

No, but you all need versions which are compatible with the version of your respective media players. As such, if you are having problems then you could try asking everyone to upgrade Syncplay to 1.6.7 (which is now released).

**Comment by albertosottile** [comment]
This was fixed in [1.6.7](https://github.com/Syncplay/syncplay/releases/tag/v1.6.7).
