### ISSUE TITLE
Opensuse kde, both appimage and snap don't start/connect to server

### ISSUE THREAD

**Issue by hikagura99** [Syncplay/syncplay#366]
When selecting the executable from the file manager, this error pops up, which translates as "For security reasons, the usage of executables is not permitted in this context" ![image](https://user-images.githubusercontent.com/64305290/98693365-7a4b5a00-2370-11eb-9677-1fad2bae3ec0.png)

When starting it via console, this other error pops up. ![image](https://user-images.githubusercontent.com/64305290/98693809-09f10880-2371-11eb-8aa8-711cb98c3af2.png), it starts but it couldn't connect to the servers![image](https://user-images.githubusercontent.com/64305290/98694037-49b7f000-2371-11eb-9be3-f29cb530c5c0.png), and then it crashes.
I'm running it on an OpenSUSE Tumbleweed KDE machine, here are my specs ![image](https://user-images.githubusercontent.com/64305290/98694258-8552ba00-2371-11eb-92fc-b2ddb804aad8.png).

**Comment by Et0h** [comment]
Does it work fine if you manually install Syncplay using the source code from https://github.com/Syncplay/syncplay ?

**Comment by hikagura99** [comment]
> Does it work fine if you manually install Syncplay using the source code from https://github.com/Syncplay/syncplay ?

nope it doesn't, same error attribute etc,

**Comment by Et0h** [comment]
If your OS is not allowing Syncplay to run mpv then the problem might like with your OS or its configuration. I know of people having issues running VLC in past because they were trying to run Syncplay as root, but other than that I can't be of assistance because I use Windows where the issue does not occur. Do things work fine if you try running Syncplay with VLC?

**Comment by hikagura99** [comment]
> If your OS is not allowing Syncplay to run mpv then the problem might like with your OS or its configuration. I know of people having issues running VLC in past because they were trying to run Syncplay as root, but other than that I can't be of assistance because I use Windows where the issue does not occur. Do things work fine if you try running Syncplay with VLC?

the problem pops up at start, so even before the mediaplayer is loaded. I don't know about configs, since i fresh installed the os not many time ago

**Comment by Friskygote** [comment]
I hit similar issue on my Linux installation. At first I simply edited PKGBUILD of syncplay AUR package to support newer version, it crashes with time of starting mpv. I fiddled around and tried other AUR package (syncplay-git) and later AppImage. All crash at same point.
I previously had 1.6.4 version installed and its AppImage still works, 1.6.5 and 1.6.6 both seemingly result in the following stacktrace:

```
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/tmp/.mount_Syncpl8usqio/usr/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/tmp/.mount_Syncpl8usqio/usr/conda/lib/python3.7/site-packages/syncplay/players/python_mpv_jsonipc/python_mpv_jsonipc.py", line 163, in run
    current_data = self.socket.recv(1024)
AttributeError: 'NoneType' object has no attribute 'recv'
```
Same stacktrace (with different paths) was when I were launching 1.6.6 from Git version, although after fidding around with it I no longer can get the stacktrace and it just exits without printing the error.

**Comment by Et0h** [comment]
For now I'm closing this issue because the problem appears to be with openSUSE Tumbleweed KDE (or its configuration) rather than with Syncplay.

In terms of the problem which @Friskygote mentioned I think it might be related to #321 which occurred when people were using an unreliable/incompatible release of PySide2. In any case, it appears to be unrelated to the issue which is the focus of #366.
