### ISSUE TITLE
Feature request: Editable server IP list / server profiles

### ISSUE THREAD

**Issue by kommersch** [Syncplay/syncplay#371]
It would be nice to be able to edit the drop-down menu with the server addresses just like it is already possible with the room list. Even better: implementation of a profile system for each syncplay server that remembers password, username, default room as well. 
Since I jump around syncplay servers fairly regularly, retyping or remembering everything is a PITA and this would make it much easier.

**Comment by Et0h** [comment]
When it comes to profiles, different people might want different things to change. As such, there is no one simple profile system which would satisfy everyone. Adding additional UI elements might make it easier for some, but it could make it more confusing for others.

For Windows users there are three main ways to do a profile system, and some work for other operating systems (some requiring appropriate tweaks):
(1) **Multiple shortcuts**. Create a shortcut to Syncplay per profile, and use the command line options to specify any value you want to change. See https://syncplay.pl/guide/client/#commandline for a list of command line switches, but the main ones are --host, --name, and --password
(2) **Multiple portable versions of Syncplay**. A portable version of Syncplay is just a version of Syncplay which has a syncplay.ini configuration file within the same folder as Syncplay.exe. You can copy and paste the Syncplay folder and have a different configuration file for each version of Syncplay.
(3) **Use per-folder configuration file**. If you separate your media into folders for each of your servers and have a syncplay.ini in each, then any settings you specify in that file will be applied if you right click on that file and select to open it with Syncplay. This is explained at https://syncplay.pl/guide/client/#advanced

I think for 99% of use cases, option (1) is perfectly fine. If you give me a common use case where it isn't enough then that could potentially justify an additional command line option such as --config-path=[] to allow for people to specify multiple profiles. This would help keep the interface clean, allowing more advanced users to specify multiple profiles without it cluttering or confusing things for regular users.

**Comment by Et0h** [comment]
The advice set out above has now been featured at https://syncplay.pl/guide/trouble/ so people who need multiple server profiles now have that information readily accessible to them. As such, I'm closing this issue as there are no plans at present to implement another way to manage multiple server profiles.
