### ISSUE TITLE
Add openSUSE Package Install Instructions

### ISSUE THREAD

**Issue by nopeinomicon** [Syncplay/syncplay#373]
Heya, I packaged syncplay for openSUSE, and I think it would be a help to potential syncplay users on openSUSE for there to be some reference to this on the Syncplay website, preferably install instructions or a link to the package in the openSUSE database here: https://software.opensuse.org/package/syncplay. The package was just accepted, but should be officially included in the Tumbleweed distribution whenever the next snapshot drops.

If it helps, once that snapshot drops, installing syncplay on openSUSE Tumbleweed can be done by running:
`sudo zypper in syncplay`

Also if there are any package specific issues, I maintain the package too, so feel free to contact or mention me if needed. Thanks everyone here for making this project!

**Comment by Et0h** [comment]
Cheers for this, I've added a link to the package at https://syncplay.pl/download/

**Comment by nopeinomicon** [comment]
Thanks a bunch!!
