### ISSUE TITLE
Snap package is 1.6.5

### ISSUE THREAD

**Issue by MrNessuno** [Syncplay/syncplay#376]
![2021-01-02_18-58](https://user-images.githubusercontent.com/20603088/103463430-99d98000-4d2c-11eb-9600-ffc5aca2d184.png)
Installing syncplay with Snap install an outdated version in Manjaro.

**Comment by daniel-123** [comment]
Where did you download the snap from?

**Comment by MrNessuno** [comment]
> Where did you download the snap from?

![immagine](https://user-images.githubusercontent.com/20603088/103464603-5fc0ac00-4d35-11eb-9f50-2107c9569d86.png)
From here, the default package manager in Manjaro. (I also checked with Discover, a software center I installed but no updates available.

**Comment by albertosottile** [comment]
Hello, we are aware that the latest version published on the snap store is 1.6.5. We are in the process of preparing a new snap build for 1.6.7 via GitHub Actions (see #374 for further information). 

At this link ([GitHub](https://github.com/albertosottile/syncplay/actions/runs/451657911), [direct](https://nightly.link/albertosottile/syncplay/workflows/build/actions_snapcraft)), you will find a test build of the new 1.6.7 snap. We would really appreciate if you could install it on your system (via `sudo snap install --classic --dangerous ./syncplay_1.6.7_amd64.snap`), test it, and report any issues. Thanks in advance for your time.

**Comment by MrNessuno** [comment]
> Hello, we are aware that the latest version published on the snap store is 1.6.5. We are in the process of preparing a new snap build for 1.6.7 via GitHub Actions (see #374 for further information).
> 
> At this link ([GitHub](https://github.com/albertosottile/syncplay/actions/runs/451657911), [direct](https://nightly.link/albertosottile/syncplay/workflows/build/actions_snapcraft)), you will find a test build of the new 1.6.7 snap. We would really appreciate if you could install it on your system (via `sudo snap install --classic --dangerous ./syncplay_1.6.7_amd64.snap`), test it, and report any issues. Thanks in advance for your time.

i got this error starting syncplay: 
`Traceback (most recent call last):
  File "/snap/syncplay/x1/bin/syncplay", line 33, in <module>
    sys.exit(load_entry_point('syncplay==1.6.7', 'gui_scripts', 'syncplay')())
  File "/snap/syncplay/x1/lib/python3.5/site-packages/pkg_resources/__init__.py", line 473, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/snap/syncplay/x1/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/snap/syncplay/x1/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2447, in load
    return self.resolve()
  File "/snap/syncplay/x1/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2453, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/snap/syncplay/x1/lib/python3.5/site-packages/syncplay/ep_client.py", line 3, in <module>
    from syncplay.clientManager import SyncplayClientManager
  File "/snap/syncplay/x1/lib/python3.5/site-packages/syncplay/clientManager.py", line 2, in <module>
    from syncplay import ui
  File "/snap/syncplay/x1/lib/python3.5/site-packages/syncplay/ui/__init__.py", line 9, in <module>
    from syncplay.ui.gui import MainWindow as GraphicalUI
  File "/snap/syncplay/x1/lib/python3.5/site-packages/syncplay/ui/gui.py", line 17, in <module>
    from syncplay.ui.consoleUI import ConsoleUI
  File "/snap/syncplay/x1/lib/python3.5/site-packages/syncplay/ui/consoleUI.py", line 200
    playlist_elements = [f"\t{i+1}: {el}" for i, el in enumerate(playlist._playlist)]
                                        ^
SyntaxError: invalid syntax
`

**Comment by albertosottile** [comment]
I suspect that you do not have the right snap file, as the right one should use Python 3.8 and this one still uses 3.5... Unfortunately, GitHub Actions does not provide direct links. 

Could you try to download the snap from here: https://github.com/albertosottile/syncplay/actions/runs/451657911 (link to syncplay_1.6.7_amd64.snap at the bottom of the page). I would also remove the older snaps from the system before trying again (`sudo snap remove syncplay`). Thanks

**Comment by MrNessuno** [comment]
> I suspect that you do not have the right snap file, as the right one should use Python 3.8 and theone you report still uses 3.5... Unfortunately, GitHub Actions does not provide direct links to artifact files and this could cause some confusion.
> 
> Could you try to download the snap from here: https://github.com/albertosottile/syncplay/actions/runs/451657911 (link to syncplay_1.6.7_amd64.snap at the bottom of the page). I would also remove the older snaps from the system before trying again (`sudo snap remove syncplay`). Thanks

new installation, new error:
`Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
[1]    56462 segmentation fault (core dumped)  syncplay
`

**Comment by albertosottile** [comment]
Ok. let's try again. Could you try a snap downloaded from here: https://github.com/Syncplay/syncplay/actions/runs/449720192 ? Thanks.

**Comment by MrNessuno** [comment]
> Ok. let's try again. Could you try a snap downloaded from here: https://github.com/Syncplay/syncplay/actions/runs/449720192 ? Thanks.

i did `sudo snap remove syncplay` and reinstalled like the other snap and:
`
[1]    56045 segmentation fault (core dumped)  syncplay`

**Comment by MrNessuno** [comment]
tryed to reinstall and got this error:
`[1]    3933 segmentation fault (core dumped)  syncplay`

**Comment by soredake** [comment]
> Ok. let's try again. Could you try a snap downloaded from here: [Syncplay/syncplay/actions/runs/449720192](https://github.com/Syncplay/syncplay/actions/runs/449720192) ? Thanks.

Can you also switch compression to lzo?

https://ubuntu.com//blog/snap-speed-improvements-with-new-compression-algorithm
https://snapcraft.io/blog/why-lzo-was-chosen-as-the-new-compression-method

**Comment by daniel-123** [comment]
@soredake Current state of snaps is that we haven't managed to create a process which would produce a snap that works reliably across few systems we tested it on. Because of that it's most likely that we'll drop snap as release channel entirely.

To be quite honest, current architecture of Syncplay where we call video player to start is not really what snaps were created in mind with (hence the --classic requirement). We also have an AppImage that works, which already provides distribution-independent runtime.

**Comment by daniel-123** [comment]
As we stopped building snaps with 1.6.8 due to serious problems with getting them to work consistently, I'm closing this issue.
