### ISSUE TITLE
Error on startup Qt::AA_EnableHighDpiScaling must be set

### ISSUE THREAD

**Issue by Joonaset** [Syncplay/syncplay#377]
Tested on Arch Linux with official arch repo package, syncplay-git package from AUR and AppImage downloaded from https://syncplay.pl/syncplay-1-6-7/. All versions let you input connection details on screen, but when connecting, crashes with error

```Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.```

edit: MPV as media player

**Comment by daniel-123** [comment]
That message itself is not related to any crashes.

Are you trying to connect to official servers?

Does running with `--no-gui` option change anything?

I find it quite odd that both package and AppImage have issues - in general they effectively run in different environments (native vs. packaged python and libraries). So it's pretty rare for a crash to occur in both of them.

**Comment by daniel-123** [comment]
Given that there hasn't been a response in a while and this seems like an isolated case, I'll close the issue for now. Feel free to provide more details and reopen the issue should the problem persist.
