### ISSUE TITLE
ModuleNotFoundError: No module named 'twisted'

### ISSUE THREAD

**Issue by Morsine** [Syncplay/syncplay#378]
please add the required version of "twisted" to the requirements.txt file.

and thank you for this amazing app!

**Comment by daniel-123** [comment]
Could you specify what problem you mean in more detail?

Twisted is already [present in requirements.txt](https://github.com/Syncplay/syncplay/blob/master/requirements.txt#L2) and the required version is 16.4.0 or higher. Is that line not suitable for some specific circumstances?

**Comment by Morsine** [comment]
> Twisted is already [present in requirements.txt](https://github.com/Syncplay/syncplay/blob/master/requirements.txt#L2) and the required version is 16.4.0 or higher. Is that line not suitable for some specific circumstances?

oh I'm sorry, I followed the [instructions on the Syncplay website](https://syncplay.pl/guide/server/) to compile and install a server-only package (on a raspberry pi), and it didn't automatically install twisted, so I thought I should let you know if there is something wrong which is causing that.

Sorry (´・ω・｀)
