### ISSUE TITLE
AppImage GUI crash on Debian 10 due to missing libxcb1

### ISSUE THREAD

**Issue by zyusouken** [Syncplay/syncplay#380]
I only just downloaded 1.6.7 today, and the GUI fails to open in both the Appimage and .deb versions.

I also get different error messages depending on which version of 1.6.7 I'm using, along with some other strange behavior.

1.6.6 still works fine.

It would take a while to describe every detail of this in text, so here's a video showing the issue. My neofetch information is included at the end, in case that's helpful.

https://user-images.githubusercontent.com/32340670/105233184-1f33a180-5b2f-11eb-9c82-43f216b1ddb8.mp4

**Comment by Et0h** [comment]
Linux is not my area, but based on #377 it might be helpful if you (1) stated your versions of python, pySide and python-twisted, and (2) let us know whether it worked in --no-gui mode.

**Comment by SwampRabbit** [comment]
@Et0h @albertosottile 


I can confirm something is up at least on when building from source on Debian 10 with what appears to be the proper dependency and requirements versions.  No change using --no-gui.

python2 (2.7.16), python3 (3.7.3), libpyside2-5.11 (5.11.2), libpyside2-py3-5.11 (5.11.2), pyside2-tools (5.11.2), python-pyside2uic (5.11.2), python3-pyside.qtcore (5.11.2), python3-pyside2.qtwidgets (5.11.2), python3-twisted (18.9.0, python3-twisted-bin (18.9.0), python3-requests (2.21.0), python3-certifi (2020.6.20)

Attempting to launch syncplay an syncplay-server from terminal outputs the following:
```
$ syncplay
Traceback (most recent call last):
  File "/usr/bin/syncplay", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyside2>=5.11.0' distribution was not found and is required by syncplay
```
One thing to note (might not be relevant here) is that python modules may be named differently between Linux distributions and sometimes they are split up differently.  I haven't had more time to dig into the above more.

**Comment by zyusouken** [comment]
I've never used the `--no-gui` mode, so I didn't do much with it. But it does make some of the errors in the terminal go away, and gets MPV to open with the Appimage version.

Both the installed and Appimage versions of 1.6.7 are able to open MPV with `--no-gui`, and look like this in the terminal:

```[17:18:38] Attempting to connect to syncplay.pl:8995
Using fallback command list.
[17:18:39] Attempting secure connection
[17:18:39] Successfully reached syncplay.pl (151.80.32.178)
[17:18:50] Secure connection established (TLSv1.3)

Hello Jim,

The Syncplay latest is available from http://syncplay.pl/


[17:18:56] Successfully connected to server
In room 'secret':
*<Jim>* is not playing a file
```

It seems that both versions of 1.6.7, as well as  the Appimage of 1.6.6 which I used as a control test, opened fine with `--no-gui`, and did not give me any errors.`

`python -V` and  `python2 -V` show version 2.7.16, `python3 -V` shows version 3.7.3.

python-twisted is on version 18.9.0-3

apt can't locate pyside, but I did happen to notice that "pyside" was mentioned in a few of the packages while scrolling through `apt list --installed`.

```python-apt-common/stable,stable,now 1.8.4.3 all [installed,automatic]
python-asn1crypto/stable,stable,now 0.24.0-1 all [installed,automatic]
python-attr/stable,stable,now 18.2.0-1 all [installed,automatic]
python-automat/stable,stable,now 0.6.0-1 all [installed,automatic]
python-cffi-backend/stable,now 1.12.2-1 amd64 [installed,automatic]
python-click/stable,stable,now 7.0-1 all [installed,automatic]
python-colorama/stable,stable,now 0.3.7-1 all [installed,automatic]
python-constantly/stable,stable,now 15.1.0-1 all [installed,automatic]
python-cryptography/stable,now 2.6.1-3+deb10u2 amd64 [installed,automatic]
python-dbus/stable,now 1.2.8-3 amd64 [installed,automatic]
python-enum34/stable,stable,now 1.1.6-2 all [installed,automatic]
python-gi/stable,now 3.30.4-1 amd64 [installed,automatic]
python-hyperlink/stable,stable,now 17.3.1-2 all [installed,automatic]
python-idna/stable,stable,now 2.6-1 all [installed,automatic]
python-incremental/stable,stable,now 16.10.1-3 all [installed,automatic]
python-ipaddress/stable,stable,now 1.0.17-1 all [installed,automatic]
python-matplotlib-data/stable,stable,now 3.0.2-2 all [installed,automatic]
python-minimal/stable,now 2.7.16-1 amd64 [installed,automatic]
python-openssl/stable,stable,now 19.0.0-1 all [installed,automatic]
python-pkg-resources/stable,stable,now 40.8.0-1 all [installed,automatic]
python-pyasn1-modules/stable,stable,now 0.2.1-0.2 all [installed,automatic]
python-pyasn1/stable,stable,now 0.4.2-3 all [installed,automatic]
python-service-identity/stable,stable,now 16.0.0-2 all [installed,automatic]
python-six/stable,stable,now 1.12.0-1 all [installed,automatic]
python-talloc/stable,now 2.1.14-2 amd64 [installed,automatic]
python-twisted-bin/stable,now 18.9.0-3 amd64 [installed,automatic]
python-twisted-core/stable,stable,now 18.9.0-3 all [installed,automatic]
python-twisted/stable,stable,now 18.9.0-3 all [installed]
python-zope.interface/stable,now 4.3.2-1+b2 amd64 [installed,automatic]
python2-minimal/stable,now 2.7.16-1 amd64 [installed,automatic]
python2.7-minimal/stable,now 2.7.16-2+deb10u1 amd64 [installed,automatic]
python2.7/stable,now 2.7.16-2+deb10u1 amd64 [installed,automatic]
python2/stable,now 2.7.16-1 amd64 [installed,automatic]
python3-apt/stable,now 1.8.4.3 amd64 [installed,automatic]
python3-asn1crypto/stable,stable,now 0.24.0-1 all [installed,automatic]
python3-attr/stable,stable,now 18.2.0-1 all [installed,automatic]
python3-automat/stable,stable,now 0.6.0-1 all [installed,automatic]
python3-brlapi/stable,now 5.6-10+deb10u1 amd64 [installed,automatic]
python3-bs4/stable,stable,now 4.7.1-1 all [installed,automatic]
python3-cairo/stable,now 1.16.2-1+b1 amd64 [installed,automatic]
python3-certifi/stable,stable,now 2018.8.24-1 all [installed,automatic]
python3-cffi-backend/stable,now 1.12.2-1 amd64 [installed,automatic]
python3-chardet/stable,stable,now 3.0.4-3 all [installed,automatic]
python3-click/stable,stable,now 7.0-1 all [installed,automatic]
python3-colorama/stable,stable,now 0.3.7-1 all [installed,automatic]
python3-constantly/stable,stable,now 15.1.0-1 all [installed,automatic]
python3-cryptography/stable,now 2.6.1-3+deb10u2 amd64 [installed,automatic]
python3-cups/stable,now 1.9.73-2+b1 amd64 [installed,automatic]
python3-cupshelpers/stable,stable,now 1.5.11-4 all [installed,automatic]
python3-cycler/stable,stable,now 0.10.0-1 all [installed,automatic]
python3-dateutil/stable,stable,now 2.7.3-3 all [installed,automatic]
python3-dbus/stable,now 1.2.8-3 amd64 [installed,automatic]
python3-debian/stable,stable,now 0.1.35 all [installed,automatic]
python3-decorator/stable,stable,now 4.3.0-1.1 all [installed,automatic]
python3-distro/stable,stable,now 1.3.0-1 all [installed,automatic]
python3-distutils/stable,stable,now 3.7.3-1 all [installed,automatic]
python3-evdev/stable,now 1.1.2+dfsg-1+b10 amd64 [installed,automatic]
python3-gi-cairo/stable,now 3.30.4-1 amd64 [installed,automatic]
python3-gi/stable,now 3.30.4-1 amd64 [installed,automatic]
python3-gst-1.0/stable,now 1.14.4-1+b1 amd64 [installed,automatic]
python3-html5lib/stable,stable,now 1.0.1-1 all [installed,automatic]
python3-hyperlink/stable,stable,now 17.3.1-2 all [installed,automatic]
python3-idna/stable,stable,now 2.6-1 all [installed,automatic]
python3-incremental/stable,stable,now 16.10.1-3 all [installed,automatic]
python3-kiwisolver/stable,now 1.0.1-2+b1 amd64 [installed,automatic]
python3-lib2to3/stable,stable,now 3.7.3-1 all [installed,automatic]
python3-libvoikko/stable,stable,now 4.2-1 all [installed,automatic]
python3-louis/stable,stable,now 3.8.0-2 all [installed,automatic]
python3-lxml/stable,now 4.3.2-1+deb10u2 amd64 [installed,automatic]
python3-magic/stable,stable,now 2:0.4.15-2 all [installed,automatic]
python3-mako/stable,stable,now 1.0.7+ds1-1 all [installed,automatic]
python3-markdown/stable,stable,now 3.0.1-3 all [installed,automatic]
python3-markupsafe/stable,now 1.1.0-1 amd64 [installed,automatic]
python3-matplotlib/stable,now 3.0.2-2 amd64 [installed,automatic]
python3-minimal/stable,now 3.7.3-1 amd64 [installed,automatic]
python3-numpy/stable,now 1:1.16.2-1 amd64 [installed,automatic]
python3-olefile/stable,stable,now 0.46-1 all [installed,automatic]
python3-openssl/stable,stable,now 19.0.0-1 all [installed,automatic]
python3-pampy/stable,stable,now 1.8.4-1 all [installed,automatic]
python3-pexpect/stable,stable,now 4.6.0-1 all [installed,automatic]
python3-pil/stable,now 5.4.1-2+deb10u2 amd64 [installed,automatic]
python3-pkg-resources/stable,stable,now 40.8.0-1 all [installed,automatic]
python3-psutil/stable,now 5.5.1-1 amd64 [installed,automatic]
python3-ptyprocess/stable,stable,now 0.6.0-1 all [installed,automatic]
python3-pyasn1-modules/stable,stable,now 0.2.1-0.2 all [installed,automatic]
python3-pyasn1/stable,stable,now 0.4.2-3 all [installed,automatic]
python3-pyatspi/stable,stable,now 2.30.0+dfsg-3 all [installed,automatic]
python3-pyaudio/stable,now 0.2.11-1+b2 amd64 [installed,automatic]
python3-pygments/stable,stable,now 2.3.1+dfsg-1 all [installed,automatic]
python3-pyinotify/stable,stable,now 0.9.6-1 all [installed,automatic]
python3-pyparsing/stable,stable,now 2.2.0+dfsg1-2 all [installed,automatic]
python3-pyqt5.qtwebchannel/stable,now 5.11.3+dfsg-1+b3 amd64 [installed,automatic]
python3-pyqt5.qtwebengine/stable,now 5.11.3+dfsg-1+b3 amd64 [installed,automatic]
python3-pyqt5/stable,now 5.11.3+dfsg-1+b3 amd64 [installed,automatic]
python3-pyside2.qtcore/stable,now 5.11.2-3 amd64 [installed]
python3-pyside2.qtwidgets/stable,now 5.11.2-3 amd64 [installed]
python3-pyxattr/stable,now 0.6.1-1 amd64 [installed,automatic]
python3-requests/stable,stable,now 2.21.0-1 all [installed,automatic]
python3-send2trash/stable,stable,now 1.5.0-1 all [installed,automatic]
python3-service-identity/stable,stable,now 16.0.0-2 all [installed,automatic]
python3-setproctitle/stable,now 1.1.10-1+b2 amd64 [installed,automatic]
python3-sip/stable,now 4.19.14+dfsg-2 amd64 [installed,automatic]
python3-six/stable,stable,now 1.12.0-1 all [installed,automatic]
python3-smbc/stable,now 1.0.15.6-1+b2 amd64 [installed,automatic]
python3-soupsieve/stable,stable,now 1.8+dfsg-1 all [installed,automatic]
python3-speechd/stable,stable,now 0.9.0-5+deb10u1 all [installed,automatic]
python3-tk/stable,now 3.7.3-1 amd64 [installed,automatic]
python3-twisted-bin/stable,now 18.9.0-3 amd64 [installed,automatic]
python3-twisted/stable,stable,now 18.9.0-3 all [installed]
python3-uno/stable,now 1:6.1.5-3+deb10u6 amd64 [installed,automatic]
python3-urllib3/stable,stable,now 1.24.1-1 all [installed,automatic]
python3-webencodings/stable,stable,now 0.5.1-1 all [installed,automatic]
python3-xapp/stable,stable,now 1.2.0-2 all [installed,automatic]
python3-xdg/stable,stable,now 0.25-5 all [installed,automatic]
python3-xlib/stable,stable,now 0.23-2 all [installed,automatic]
python3-yaml/stable,now 3.13-2 amd64 [installed,automatic]
python3-zope.interface/stable,now 4.3.2-1+b2 amd64 [installed,automatic]
python3.7-minimal/stable,now 3.7.3-2+deb10u2 amd64 [installed,automatic]
python3.7/stable,now 3.7.3-2+deb10u2 amd64 [installed,automatic]
python3/stable,now 3.7.3-1 amd64 [installed,automatic]
python/stable,now 2.7.16-1 amd64 [installed]
```

**Comment by albertosottile** [comment]
@zyusouken  The AppImage should not look at what is installed in your system (Python, PySide, Qt, and so on).
I would ask you to try two things. First, try to run again the 1.6.7 AppImage in an environment with `export QT_VERBOSE=1` set. Please report here the full log that you will obtain. 

Second, try to download the latest prerelease AppImage from GitHub Actions ([direct download](https://github.com/Syncplay/syncplay/suites/1885812156/artifacts/36853556) | [build](https://github.com/Syncplay/syncplay/runs/1754222435?check_suite_focus=true)) and check if you still have the same issue with it.

Thanks for your help.

@SwampRabbit The issue you are describing appears to be caused by your system and/or the GNUmakefile. In any case, it does not concern the AppImage so, I would encourage you to open another issue about it. Thanks.

**Comment by daniel-123** [comment]
@zyusouken I've dusted off my Debian 10 stable install, and it seems like I can reproduce the issue.

@SwampRabbit It seems that PySide 5.11 on Debian 10 is somehow not recognized, I've also confirmed this on my installation. Though this is entirely separate issue from what's happening in the AppImage.

@albertosottile here is the gist with verbose AppImage logs: https://gist.github.com/daniel-123/d42047709e91e00491dd9adcc06e6db7

**Comment by daniel-123** [comment]
After some poking around and with @albertosottile pointing out that the problem might be upstream in [QTBUG-88688](https://bugreports.qt.io/plugins/servlet/mobile#issue/QTBUG-88688) I managed to find a workaround for Debian 10 (possibly more distributions are affected) - you can just manually install libxcb.so.1.1.0

In case of Debian 10, the easiest way to do it is to just grab the [libxcb1 package from Debian 11](https://packages.debian.org/bullseye/libxcb1). There are no dependency problems with it.

**Comment by SwampRabbit** [comment]
@daniel-123 thanks for digging into this even though my issues are unrelated to the appimage.

I packaged that version of libxcb1 back last May so I don't think that affects at least my issue.  (I'm only testing on our AHS release).  I'll update the dependencies to require this specific version now though.
[http://mxrepo.com/mx/repo/pool/ahs/libx/libxcb/(url)

I will create a new issue as suggested by @albertosottile when I get a chance.  Thanks again, I'd like to get this packaged for our users.

**Comment by daniel-123** [comment]
@zyusouken I've tried directly embedding libxcb-xkb into the AppImage, could you download the artifact from https://github.com/Syncplay/syncplay/suites/1920354596/artifacts/37795802 and try it?

If you tried to install libxcb1 as workaround please uninstall it before testing.

**Comment by daniel-123** [comment]
Sadly it seems like simple workaround I tried in #384 didn't do anything.

Given that this is mostly an upstream issue and that PySide2 will soon be succeeded by PySide6 anyway I see having a known workaround as sufficient. Until then we might keep this issue open.

The workaround is to manually download and install [libxcb1 package from Debian 11](https://packages.debian.org/bullseye/libxcb1).

**Comment by zyusouken** [comment]
Crap, I'm sorry for taking so long to get back to this thread. Work has been busy, and this just fell through the cracks.

After a quick `sudo apt install libxcb1`, Syncplay has indeed started working normally for me.

Thank you all for your help in getting this resolved! If you still need anything from me, please let me know.

**Comment by daniel-123** [comment]
As a small side note @zyusouken - thanks to #393 there now is also a workaround for non-functional GUI on deb package in Debian 10.8. It's possible to update pyside2 with pip, though *specifically* 5.15.2 version which is in AppImage also requires the libxcb1:

`pip3 install pyside2 --upgrade`
`curl -O http://http.us.debian.org/debian/pool/main/libx/libxcb/libxcb1_1.14-3_amd64.deb`
`dpkg -i libxcb1_1.14-3_amd64.deb`

**Comment by teohhanhui** [comment]
It doesn't work on openSUSE MicroOS, probably due to missing PySide. I thought an AppImage is supposed to be a platform-independent distribution format? So ideally as a user I shouldn't have to install PySide (`python3-pyside2` package in the case of openSUSE) myself, right?

```
teohhanhui@envy-x360:~/Downloads> export QT_VERBOSE=1
teohhanhui@envy-x360:~/Downloads> ./Syncplay-1.6.8-x86_64.AppImage 
Order: 'PySide2', 'PySide', 'PyQt5', 'PyQt4'
Trying PySide2
Misplaced member has no source: QtGui.QStringListModel
Misplaced member has no source: QtCore.Property
Misplaced member has no source: QtCore.Signal
Misplaced member has no source: QtCore.Slot
Misplaced member has no source: QtCore.QAbstractProxyModel
Misplaced member has no source: QtCore.QSortFilterProxyModel
Misplaced member has no source: QtCore.QItemSelection
Misplaced member has no source: QtCore.QItemSelectionModel
Misplaced member has no source: QtCore.QItemSelectionRange
QtCompat: AttributeError: partially initialized module 'syncplay.vendor.Qt' has no attribute '_QtWidgets' (most likely due to a circular import)
QtCompat: AttributeError: partially initialized module 'syncplay.vendor.Qt' has no attribute '_QtWidgets' (most likely due to a circular import)
QtCompat: AttributeError: partially initialized module 'syncplay.vendor.Qt' has no attribute '_QtWidgets' (most likely due to a circular import)
QtCompat: AttributeError: partially initialized module 'syncplay.vendor.Qt' has no attribute '_QtWidgets' (most likely due to a circular import)
QtCompat: AttributeError: partially initialized module 'syncplay.vendor.Qt' has no attribute '_QtWidgets' (most likely due to a circular import)
QtCompat: AttributeError: partially initialized module 'syncplay.vendor.Qt' has no attribute '_QtWidgets' (most likely due to a circular import)
QtCompat: AttributeError: partially initialized module 'syncplay.vendor.Qt' has no attribute '_QtWidgets' (most likely due to a circular import)
QtCompat: AttributeError: partially initialized module 'syncplay.vendor.Qt' has no attribute '_QtWidgets' (most likely due to a circular import)
QtCompat: AttributeError: partially initialized module 'syncplay.vendor.Qt' has no attribute '_QtWidgets' (most likely due to a circular import)
Could not import GUI libraries. If you do not have PySide installed then you will need to install it for the GUI to work.
Hostname can't be empty!
Some necessary arguments are missing, refer to --help
```

**Comment by daniel-123** [comment]
>due to missing PySide

Unlike libxcb1, PySide is definitely present in AppImage. If installing libxcb1 doesn't fix the problem, it is something entirely different.

Could you check output with `QT_DEBUG_PLUGINS=1 ./Syncplay-1.6.8-x86_64.AppImage`? And assuming it's not libxcb1 just attach the output as gist to a new issue?

**Comment by teohhanhui** [comment]
It was missing `libgthread-2.0.so.0`. Should I open a new issue?

**Comment by daniel-123** [comment]
@teohhanhui to me it sounds like separate, but possibly similar problem. IMHO it makes sense to create a new issue from it along with workaround (I assume that installing libgthread-2_0-0 fixed it for you). Though it's possible that it also is caused by packaging of PySide.

**Comment by teohhanhui** [comment]
Opened https://github.com/Syncplay/syncplay/issues/431

Actually, it seems like it's the same issue with missing `libxcb.so.1`
