### ISSUE TITLE
Downloads Page: Snap Link is 404

### ISSUE THREAD

**Issue by Draco18s** [Syncplay/syncplay#383]
![image](https://user-images.githubusercontent.com/1750680/105616144-4e018000-5d9a-11eb-9e29-37f8904ec4ea.png)

The Linux (Snap) url points to `https://github.com/Syncplay/syncplay/releases/download/v1.6.7/syncplay_1.6.7_amd64.snap` which does not exist (there is no /releases folder in the master branch). I was able to acquire it via the link in [this comment](https://github.com/Syncplay/syncplay/issues/376#issuecomment-753592661), but the site should be updated.

**Comment by albertosottile** [comment]
Interesting... does the snap that you downloaded work for you? 

We are actually in the process of dropping the Snap Store as a release channel, as we were not able to build a snap that consistently worked across all the test systems (as you probably noticed from the issue you mentioned).

**Comment by Draco18s** [comment]
> does the snap that you downloaded work for you?

Yep. Worked just fine, and aside from having a bit of an issue pointing it at VLC (I didn't actually know what it *wanted* to be pointed at, but eventually I noticed that I pointed it at a file, it didn't like it, and the field changed to *something else* and that's when I noticed that it was a dropdown that already knew what it was looking for).

Another person that was going to join us had more issues than I did, and eventually gave up, but I don't know what the problem he had was, just that his video player would immediately crash (he had Syncplay running just fine).

**Comment by daniel-123** [comment]
With regards to the installation errors of deb package: those are because the required packages is somehow not available in the Ubuntu Eoan repository. Which does look a bit weird if you are on Pop!OS?

As a side note Ubuntu Eoan is already past it's support period, so broken repositories wouldn't surprise me. Does Pop!OS extend the duration of support past of what upstream Ubuntu does?

**Comment by Draco18s** [comment]
Ah ha. Interesting.

The system hadn't notified me that there *were* updates (even checking it manually now it says there aren't). So that makes some degree of sense. I've also only been booting back into Pop!OS for maybe three months now? Definitely wasn't back in July/August as I was working from home and needed a Windows OS for Teams (I can't sign in otherwise, some configuration setting IT put on it), so I probably missed the memo.

Thanks for checkin'

**Comment by daniel-123** [comment]
As we stopped building snaps with 1.6.8 due to serious problems with getting them to work consistently, I'm closing this issue.
