### ISSUE TITLE
Drop-down list with media players at start

### ISSUE THREAD

**Issue by MarisKori** [Syncplay/syncplay#398]
It would be great if a user can choose media players when starting the application.
Also it would be doubly great if Syncplay could automatically find media players (e.g. using standard paths or using registry).

**Comment by daniel-123** [comment]
Normally Syncplay already does search for compatible media players in default paths.

Could you describe in details the situation were it apparently doesn't work? In particular:

- What operating system you are using and what version of Syncplay.
- Which players you have installed and in what paths.
- What exactly was the process in which you started the Syncplay and concluded that it doesn't have this feature? This might seem like a silly question, but it's important for us to know in what exact way the user interface has misled you. We cannot really make such observations ourselves given that we know the software inside and out, so a new perspective is invaluable.

**Comment by MarisKori** [comment]
1) Windows 7 x64; Syncplay 1.6.7 (release 94)
2) 
   a) C:\Program Files\MPC-HC\mpc-hc64.exe
   b) C:\Program Files (x86)\VideoLAN\VLC\vlc.exe
   с) C:\Program Files (x86)\K-Lite Codec Pack\MPC-HC64\mpc-hc64.exe  (friend's)  
3) It was Start menu, i.e. explorer.exe I guess.

Seems Syncplay saves previous path if I changed it. So yes, I can confirm that there is drop-down list. But I'm not sure how to check now what was at the beginning.

**Comment by Et0h** [comment]
I think that as per https://syncplay.pl/guide/client/ you can run Syncplay with the --clear-gui-data switch to reset this data.

According to https://github.com/Syncplay/syncplay/blob/master/syncplay/constants.py the first two paths you specified should be listed by default. For K-Lite we didn't have the 64-bit version so I'll add that

**Comment by daniel-123** [comment]
> It was Start menu, i.e. explorer.exe I guess.

@MarisKori sorry, I guess I didn't state my question clearly and simply :) I just wanted to know what you, as an end user, see in the Syncplay window, what you clicked, what you checked etc. In essence I would like to get a perspective of **why** you thought that Syncplay doesn't have a list of existing players. Such description could also help us in actually reproducing the bug (as it does look like one).

Like at @Et0h mentioned - the dropdown should be there and it should have shown first two players you had. Possibly including additional custom path you set in the past.

**Comment by MarisKori** [comment]
Friend is sure that there was no drop-down list.

I guess that I personally could miss it but I remember too that there was no drop-down list.

I can check it again and even make a video if you tell me how to make Syncplay forget previously chosen paths. I think it's smart desision to save all typed paths but now I can't help you to test it.

Btw the friend (a girl) chose unins000.exe by mistake and Syncplay saved it's path. It's a kind of issue.

**Comment by daniel-123** [comment]
@MarisKori like Et0h mentioned, you can use command line option `--clear-gui-data` to reset whatever is in that dropdown menu. I think on Windows the easiest way to do that is to make a temporary shortcut to Syncplay executable and add that option to "Target" field.

It would be great if you also managed to test latest development version of Syncplay after the change Et0h made - it should detect all the paths you listed earlier. You can [download it here](https://ci.appveyor.com/project/Et0h/syncplay/builds/38093748/artifacts).

**Comment by MarisKori** [comment]
I checked 1.6.7 and 1.6.8 versions (reinstalled it). There is drop-down list in both versions. Sorry for the wrong suggestion.

Btw I found syncplay.ini directly in C:\Users\user\AppData\Roaming.
I think there should be a subfolder like "C:\Users\user\AppData\Roaming\Syncplay" or "C:\Users\user\AppData\Roaming\TeamName". But it doesn't really matter.
