### ISSUE TITLE
Playlists on VLC

### ISSUE THREAD

**Issue by nnamrrehdlopoel** [Syncplay/syncplay#40]
If you have multiple files in queue and switch over to the next one, something bad happens:
One of the players jumps into the next file and syncs the time position with the other player. If the file is too short, it continues jumping until a long enough file is reached.
So you often end up playing another file from somewhere halfway through.

nnamrrehdlopoel

**Comment by Et0h** [comment]
The draft Shared Playlist spec is available from: http://syncplay.pl/Syncplay_Shared_Playlist_Draft_Spec.txt

One of the big questions is how Syncplay should handle persistence of shared playlists. If everyone leaves the room, does it stay attached to that room, and if so for how long? Should the length of persistence if everyone leaves be something that is specified server-side, with a default of an hour? Should it be remembered if you close the server and open it again? Should it forget as soon as everyone leaves the room, and rely on restorable client-side backups? Your thoughts are welcomed.

**Comment by Et0h** [comment]
Release Candidate 1 of Syncplay 1.4.0 with its shared playlists feature is out now! http://syncplay.pl/syncplay-1-4-0/
