### ISSUE TITLE
Case sensitivity in room list

### ISSUE THREAD

**Issue by pabter** [Syncplay/syncplay#403]
Whenever one connects to a server, room names are case sensitive (ie. the room "aRoom" is different from "aroom").
However, the saved room list is not case sensitive, and it keeps the casing from the first time a room was entered.

Thereferore, if one were to try to enter the room "aRoom", and mistakenly wrote "aroom", it would go to a different room (as expected), but when trying to correct the mistake to enter "aRoom", as "aroom" is already in the room list, it would keep entering "aroom", even when explictly typing "aRoom" in the "Default room:" field.

A solution for this is manually removing "aroom" from the room list, but i think the default behavior should be for it to save the room names remembering their casing.

(Also, does the question mark button on the room list window title bar do anything?)

**Comment by Et0h** [comment]
Thanks for raising this issue as I was unaware of it. I think it should be possible to fix this by moving to a case-sensitive completer for the comboboxes.

The question mark on the room list doesn't do anything. I think it just means I haven't set the WindowFlags for that window to set Qt.WindowContextHelpButtonHint to false.

**Comment by Et0h** [comment]
Sorry for the wait but both issues should now be resolved in Syncplay 1.7.0.
