### ISSUE TITLE
[Feature Request] Ability to sync video speed

### ISSUE THREAD

**Issue by jvschiavo** [Syncplay/syncplay#406]
Currently there is no possible way to sync video speed across different clients.

The only way to watch videos together in 2x for example would be to everyone manually changing their video player speed to the desired rate or the constant cuts and jumps trying to sync would make it impossible to watch.

But if someone likes to change the video speed frequently depending on the part of the video (like me), the best solution would be to sync the video speed across clients.

Would something like this be possible to implement?

Thanks again for the great software. :)

**Comment by Et0h** [comment]
It's possible, but it isn't easy and would need a lot of testing to ensure it works across all media players, is compatible with managed rooms, changing rooms mid-playback, joining mid-playback (when first loading the file or following a disconnect when the file is already open), and how to handle slowdowns. You would also need a system to determine if some people in the room have an older version of Syncplay to warn them that they will be out of sync. Whoever takes on this project would need to be willing to maintain the feature in the future, which hopefully won't be as difficult as implementing it in the first place.

https://syncplay.pl/about/ideas/ lists "Allowing rooms to have a custom playback rate" as something that "Would need someone to come on board to develop". To date, nobody has volunteered so it isn't happening.

See https://github.com/Syncplay/syncplay/issues/339 for the previous discussion of this suggestion. I have now tagged #339 as 'help wanted' which means if someone is looking for something to volunteer on then they will see it as an option. I'll leave this issue open for a time to see if it sparks interest in anyone wanting to put their time into this project, but if nobody steps forwards then I will close this issue.
