### ISSUE TITLE
m3u playlist parsing

### ISSUE THREAD

**Issue by GreatGrogrodor** [Syncplay/syncplay#408]
I've noticed when i create an m3u8 playlist, Syncplay doesn't parse metadata in the list. Not a huge deal, but it can make things more readable when your username and passwords that are in those links are 128 character randomly generated strings lol

Example.m3u8:
```m3u
#EXTM3U
#EXTINF:123, Movie1
https://username:password@domain.com/Movies/some_movie.mp4
#EXTINF:123, Movie2
https://username:password@domain.com/Movies/some_other_movie.mp4
```

VLC media player will display the names of the movies as "Movie1" and "Movie2" that are 2 minutes and 3 seconds long (123 seconds) rather than the URL, if i open it directly. However syncplay does this:
![image](https://user-images.githubusercontent.com/17716439/114063471-8a6c5480-9890-11eb-9bf4-be92aee21257.png)

It's treating the comments/metadata in the file as though it's a movie to play, rather than the title info & other metadata.

So, i have some suggestions. Either:
A: Make the playlist a "DataGridView Control" or at least that's what it's called in winforms, though i see you're using qt, so whatever the equivalent is in there. Add columns for Artist, Album, Title, Track number, URL, Duration, etc. Have it populate that list from the metadata/URLs.

B: Make it ignore empty lines and metadata. It'll still pull the links through though and it'll work. It just won't be purdy.

I'm willing to put in a herculian effort to add this myself someday, but i have a lot on my plate right now, and probably will for a while. Any questions on implementation, I'm happy to answer though.

There's some documentation here on the subject:
https://docs.fileformat.com/audio/m3u/

**Comment by Et0h** [comment]
I am not in favour of making the playlist more complex as per the principles set out at https://github.com/Syncplay/syncplay/issues/315

However, I think it would be an improvement to strip comments etc from m3u files would be happy to see a PR for this. I think that to properly parse arbitrary m3u files Syncplay might also need to strip out local full and relative paths (if it doesn't already do this). At present Syncplay is only really designed to parse the m3u8 files created through the Save Playlist option (so only a subset of what the format allows).

**Comment by Et0h** [comment]
Okay, the more I look into the details of the .m3u format the more I want Syncplay to simply support txt files with one filename/character per line. Issue include handling filenames starting with a # and using special characters. I'm now in favour of just changing the default file format .txt and making it clear in our documentation that Syncplay does not provide full m3u support.

**Comment by Et0h** [comment]
Okay, I've now added a note to https://syncplay.pl/guide/trouble/ to make it clear that Syncplay does not provide full m3u support and that you need to provide one filename per line and nothing else.

**Comment by JordanPlayz158** [comment]
I'm aware SyncPlay does not support m3u fully but I am trying to play a m3u8 playlist from a website and only have 1 filename per line and have tried 1 url per line and it works fine with mpv normally but not through syncplay, is there any reason syncplay has it's own m3u parsing when mpv can handle m3u fully?

**Comment by Et0h** [comment]
1. Syncplay is not simply for mpv.
2. Syncplay does not have M3U or M3U8 parsing it has parsing for its one file per line system for locally storing playlists.

**Comment by JordanPlayz158** [comment]
1. True, although not sure how many clients officially supported by SyncPlay don't have M3U/8 support
2. Yeah, that's what I meant (and used your wording from the previous comment)
3. Oh alright, might be a good feature though as most players should support it if they support M3U/8. I could attempt to add playlist from website support unless this is not a feature or vision you wish to be in SyncPlay
