### ISSUE TITLE
ERROR:  Could not load mpv: '__Listener' object has no attribute 'mpvpipe'

### ISSUE THREAD

**Issue by asakura42** [Syncplay/syncplay#409]
I use `syncplay-git` package from Arch User Repository and get this error.

**Comment by Et0h** [comment]
@blaenk and @alxpettit are maintainers for that repo so they might be able to comment. Also, it might be helpful to note which build of Syncplay,  mpv and PySide you are using.

**Comment by daniel-123** [comment]
`syncplay-git` package in AUR is outdated - crucially it's older than PR #310 which is required for supporting recent mpv releases. You need at least Syncplay 1.6.5 for that. There is a `syncplay` package in AUR which is actually newer and sits at version 1.6.7

You could also use AppImage release or even run it straight from cloned repo after manually taking care of dependencies.

Since this is a question about outdated package which we don't support ourselves, I'll close this issue.

**Comment by asakura42** [comment]
@daniel-123 Same error with `syncplay` package.

**Comment by asakura42** [comment]
Same with `Syncplay version 1.6.8 (Yoitsu)` which I installed from master branch.

**Comment by daniel-123** [comment]
Can you check what happens if you run the AppImage and if you run the Syncplay directly from cloned repository (`./syncplayClient.py`)?

I've just complied latest mpv git version and used latest Syncplay master along with pySide 5.15.2. It works perfectly fine on my system (Debian 11).

**Comment by asakura42** [comment]
Maybe `mpvpipe` is something Windows-related? I found that `mpvpipe` used as `input-ipc-server` in Windows while Linux uses `/tmp/mpvsocket` for this purpose. (source: https://www.svp-team.com/wiki/SVP:mpv)

**Comment by asakura42** [comment]
> Can you check what happens if you run the AppImage
AppImage ran successfully.

>and if you run the Syncplay directly from cloned repository (`./syncplayClient.py`)?
Got error.

Also I get every time `Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.` warning in terminal but maybe it's minor thing.

**Comment by asakura42** [comment]
Ha-ha, fail. I ran AppImage as other user as typical paranoid. But as other user `./syncplayClient.py` works too. So I think that problem is on my side only. How can I debug syncplay?

**Comment by asakura42** [comment]
Please help me define what's type of problem I have. When I run Syncplay as my normal user with debug mode I get this output:
```
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
[12:46:30 AM] Could not send quit message: 'MpvPlayer' object has no attribute '_listener'
[12:46:31 AM] client/server >> {"TLS": {"startTLS": "send"}}
```

But with other user (and it works):
```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-smth'
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
error: XDG_RUNTIME_DIR not set in the environment.
```

If I run syncplay as normal user with `XDG_RUNTIME_DIR=/tmp/runtime-asakura` or `XDG_RUNTIME_DIR=`, I get error too. So `XDG_RUNTIME_DIR` variable isn't the main problem here. What do you think the problem is?

**Comment by asakura42** [comment]
The problem was solved after a reboot. I do this once a century, so I didn't even think it would help. Nevertheless, I do not understand the cause, but consider the issue closed. Thank you all.
