### ISSUE TITLE
Use PyInstaller or cx_Freeze instead of py2exe

### ISSUE THREAD

**Issue by cryzed** [Syncplay/syncplay#41]
Using [PyInstaller](http://pyinstaller.org/) or [cx_freeze](http://cx-freeze.sourceforge.net/) would allow you to create binaries for every supported system. A small comparison between common tools used to achieve this can be found [here](http://docs.python-guide.org/en/latest/shipping/freezing/). Looking at the table it seems that cx_Freeze would be the best solution all-around, even with eventual Python 3 support, although I have never used it myself and trying to install it on an current Ubuntu 14.04 system raises compilation errors even with the required packages installed.

PyInstaller on the other hand I have used, and creating a stand-alone binary is often as simple as running:

```
pyinstaller <script.py>
```

Additionally if the "--onefile" option is passed, it can even create single-file executables, which I imagine would be especially useful for the server.

**Comment by Et0h** [comment]
Discussions on moving from Python 2.7 to Python 3 can take place at https://github.com/Syncplay/syncplay/issues/169
