### ISSUE TITLE
Syncplay disconnects when streaming from a URL

### ISSUE THREAD

**Issue by kathelynn** [Syncplay/syncplay#411]
https://pastebin.com/7a9J3hMs

On MacOS, currently troubleshooting for a friend.
I made them output this error by running Syncplay through terminal. The error is caused after I let them stream from a link. It works fine if they play it directly through mpv, but if the mpv was running under Syncplay it would cause weird issues by either:
- Disconnecting by Timed Out when playing through playlists or double-clicking a link
- Opening the video on a separate mpv process when dragging the link to mpv itself, causing Syncplay to hang until force-closed.

Thank you~

**Comment by albertosottile** [comment]
Hi, thanks for reporting this.

From the paste, it looks like the problem might be in the URL itself. Could you report here the URL you were using or, at least, any special characters that it included?

**Comment by kathelynn** [comment]
> Hi, thanks for reporting this.
> 
> From the paste, it looks like the problem might be in the URL itself. Could you report here the URL you were using or, at least, any special characters that it included?

`Fictionalized%20BBC%20Special%20Report%20of%20NATO-Russia%20conflict-VWqWAi_H_9o.mkv`
Hosted on an HTTP server, this is the only part of the URL that has special characters on it.

**Comment by albertosottile** [comment]
Hi @kathelynn, are you still experiencing this?

**Comment by Et0h** [comment]
I just tested with mpv 0.34.0 on Windows 10 and it seems to work fine with both the encoded and decoded versions of the URLs.
