### ISSUE TITLE
渴望安装时有中文选项

### ISSUE THREAD

**Issue by Zhaodaidai** [Syncplay/syncplay#412]
非常希望有汉化语言包!!!

**Comment by Et0h** [comment]
Syncplay is an open source project that relies on volunteers for translations into new languages. Nobody has volunteered to translate Syncplay into Chinese, and so no translation exists.

Syncplay是一個開源項目，依靠志願者將其翻譯成新語言。沒有人自願將Syncplay翻譯成中文，因此不存在翻譯。
