### ISSUE TITLE
Syncplay refuses to launch no matter what

### ISSUE THREAD

**Issue by CJSanGaming** [Syncplay/syncplay#415]
I had just reinstalled windows, I had then downloaded Syncplay. However, Once I launched it, it gave me the error "Reinstalling the program may fix this problem. vcruntime140.dll is either not designed to run on Windows or it contains an error". My friend and I  tried a bunch of resolutions then eventually reinstalled that specific file. That fixed the error, However, Syncplay now refuses to launch no matter what, All versions included (Even Portable) The Syncplay server launches as intended however the Syncplay application itself does not.

**Comment by Et0h** [comment]
Try installing the Microsoft Visual C++ 2015 Redistributable Package from https://www.microsoft.com/en-us/download/details.aspx?id=53587 (Download the 32-bit version, i.e. ‘vc_redist.x86.exe’).

**Comment by CJSanGaming** [comment]
Thank you so much! I installed so many different versions of the Microsoft Visual Program. but that's the one that works, TYSM!
