### ISSUE TITLE
Syncplay Protocol v1.6.7

### ISSUE THREAD

**Issue by RozeFound** [Syncplay/syncplay#417]
I'm trying to implement your protocol in my application, and I was confused with this thing:
`Server << {"Set": {"user": {"Bob": {"room": {"name": "SyncRoom"}, "file": {"duration": 0, "name": "filename", "size": 0}}}}}`
What the heck is this: `{"user": {"Bob": `
How can I access data in the row if the key can be ANYTHING?

**Comment by Et0h** [comment]
Every Syncplay user has a username. In this example, one of the users has the name "Bob" and so this message specifies information regarding what Bob is watching.

If you want to see how this is implemented in practice, you can see the Syncplay source code at https://github.com/Syncplay/syncplay and specifically the protocol code at https://github.com/Syncplay/syncplay/blob/master/syncplay/protocols.py

What are you trying to implement the protocol for?

**Comment by RozeFound** [comment]
I mean, why the json key doesn't have a constant name?

**Comment by Et0h** [comment]
The user won't always be called "Bob". Sometimes they might be called "Alice".

**Comment by RozeFound** [comment]
I understand, but JSON keys must be constant for easy accessing data inside. Like '"User":{"username":"Bob", ...}'

**Comment by RozeFound** [comment]
JSON keys with mutable names just hard to deserialize.
> What are you trying to implement the protocol for? @Et0h 

Of course for what it was created, for video playback synchronization.

**Comment by Et0h** [comment]
I agree that the protocol is not ideal in terms of ease of re-implementation, but it's what we've got and changing it would harm forwards and backwards Syncplay combability. If you are trying to make something which is compatible with Syncplay then look at how Syncplay parses it to figure it out. If you do not need compatibility then feel free to revisit many of the protocol design decisions that we made.

**Comment by RozeFound** [comment]
Why just not make something like this?
```
if ver > 1.6.8: 
    return {"User": {"username": "Bob", ...}}
else: return {"User": {"Bob": {...}}}
```
Or you just don't want to make it easier to use?

**Comment by Et0h** [comment]
How would changing the protocol make anything easier for anyone? We want to maintain forward and backwards compatibility, so it just means every implementation would need to support both versions of the protocol, thus doubling the complexity.

**Comment by RozeFound** [comment]
Okay I understand your point, thanks for the answer.
