### ISSUE TITLE
(feature request) Sync play local files

### ISSUE THREAD

**Issue by ffffwh** [Syncplay/syncplay#421]
mainly for comparison after transcoding.

Currently, I use this workflow (on macOS)

1. start a local server in Terminal
2. start a client Syncplay.app
3. start another client `open -n -a Syncplay.app`

It would be better if a single instance of Syncplay.app could handle it.

**Comment by daniel-123** [comment]
To be honest this is pretty far away from core use case. Personally I don't think it warrants changing how the application works for everybody just to make it slightly more convenient for a single very niche use.

For such custom use I think making a wrapper of Syncplay in a script which takes two files as arguments and then runs two instances of client along with a server makes much more sense.

**Comment by Et0h** [comment]
As @daniel-123 mentioned, having multiple versions of Syncplay running on one device is not the intended use case. Syncplay is not designed to consistently sync with frame-perfect precision (prioritising responsiveness on unpausing instead). The level of delay is fine for syncing online with VoIP as the delay is less than the delay in the voice chat, but means it doesn't produce perfectly in sync local playback if you have multiple instances on one machine.
