### ISSUE TITLE
The application was unable to start correctly (0xc000007b)

### ISSUE THREAD

**Issue by derrickxcvi** [Syncplay/syncplay#423]
I looked up the problem and updated my Microsoft Visual C++ 2015 Redistributable both x64 and x86. It won't open after, telling me the same thing as in the headline.

Assist please.
![doc_2021-05-24_14-56-22](https://user-images.githubusercontent.com/20435945/119344440-57471e80-bca0-11eb-8e8f-1d998de407ca.png)

**Comment by Et0h** [comment]
Some troubleshooting questions:
1. Does this issue occur with both the installed and portable version of Syncplay 1.6.8? https://syncplay.pl/syncplay-1-6-8/
2. Does this issue occur with Syncplay 1.6.7? https://syncplay.pl/syncplay-1-6-7/
3. Does installing the latest version of the .NET Framework 4.8 fix the issue? https://dotnet.microsoft.com/download/dotnet-framework

**Comment by derrickxcvi** [comment]
After updating my Windows I ran Syncplay v.1.6.7 both the installer and
portable version and the error came back of "The application was unable to
start correctly (0xc000007b).

With Syncplay v.1.6.8, a different error occurs for each(installer and
portable version) but both are related to log files as seen in the
attachments below.

**Comment by Et0h** [comment]
Okay, I've created two different builds from my own machine. Please test them and let me know if they work:
- https://github.com/Et0h/syncplay/releases/download/168test/Syncplay-168-Test1.zip
- https://github.com/Et0h/syncplay/releases/download/168test/Syncplay-168-Test2.zip

**Comment by derrickxcvi** [comment]
Sorry to disappoint but the error is recurring; "The application was unable
to start correctly (0xc000007b)"

**Comment by Et0h** [comment]
> For me this happened when I deleted Microsoft Visual C++ 2017 Redistribute

Thanks for letting us know as it can help others debug the issue if they come across it.

**Comment by J6ey** [comment]
@Et0h Actually what fixed for me was was installing Microsoft Visual C++ 2017 Redistribute x86 (not x64) since I guess the Syncplay I have is 32 bit.
