### ISSUE TITLE
Syncplay doesn't launch

### ISSUE THREAD

**Issue by Kehanort** [Syncplay/syncplay#425]
I just installed Syncplay 1.6.8 and it refuses to launch with the error?

Errors in 'Syncplay.exe' - See the log file 'C:\Program Files (x86)\Syncplay\Syncplay.log` for details

All the log shows is this:
PySide2/__init__.py: Unable to import shiboken2 from C:\Program Files (x86)\Syncplay\lib/libsync.zip

I've already updated Microsoft Visual C++ 2015 Redistributable both x86 and x64 and still nothing seems to work.

**Comment by abhiraj2** [comment]
having the same issue on one of my laptops, but weirdly not on two others

**Comment by abhiraj2** [comment]
It appears that the issue only exists on the latest release, I just checked 1.6.7 and it works just fine.
It might have something to do with the weird path " C:\Program Files (x86)\Syncplay\lib/libsync.zip" since it uses twp different types of connectors "/" and "\"

**Comment by Et0h** [comment]
If it works on some laptops and not others then I don't think the direction of the slashes is the issue. I think that might just be shorthand for it saying "it isn't working". It is interesting that it works on some laptops and not others, it might depend on whether certain common dependencies are installed on the devices.

Does installing the latest version of the .NET Framework 4.8 fix the issue? https://dotnet.microsoft.com/download/dotnet-framework

It is very helpful to know that it works fine with Syncplay 1.6.7. Does the issue occur with both the installed and portable versions of Syncplay 1.6.8?

**Comment by Et0h** [comment]
Okay, I've created two different builds from my own machine. Please test them and let me know if they work:
- https://github.com/Et0h/syncplay/releases/download/168test/Syncplay-168-Test1.zip
- https://github.com/Et0h/syncplay/releases/download/168test/Syncplay-168-Test2.zip

**Comment by samurai-legend** [comment]
Test-1 worked for my friend thanks a lot :D cheers

**Comment by Et0h** [comment]
Those who have had a problem (or whose friends had a problem): Was this using the 32-bit or the 64-bit version of Windows 10?

**Comment by spidermatt99** [comment]
I have the problem on 64-bit Windows 10, with both the portable version and installed. The test zips don't work for me. Nothing happens when trying to launch the exe, not even an error message.

**Comment by Et0h** [comment]
@spidermatt99 And did Syncplay 1.6.7 work fine for you? When it comes to debugging, the more information the better.

**Comment by abhiraj2** [comment]
Both the test versions worked just fine on the laptop that wasn't able to run the official latest release but was able to run 1.6.7

**Comment by spidermatt99** [comment]
> @spidermatt99 And did Syncplay 1.6.7 work fine for you? When it comes to debugging, the more information the better.

Yes, 1.6.7 continues to work fine.

**Comment by Harry466** [comment]
> Okay, I've created two different builds from my own machine. Please test them and let me know if they work:
> 
> * https://github.com/Et0h/syncplay/releases/download/168test/Syncplay-168-Test1.zip
> * https://github.com/Et0h/syncplay/releases/download/168test/Syncplay-168-Test2.zip

Thank you so much. your 1st test file worked for me:)

**Comment by albertosottile** [comment]
So, it seems the issue is caused by either Python 3.8 or PySide2 5.15, as these are the differences between the Test1 build and 1.6.8 release (the Test1 build embeds Python 3.6 and PySide2 5.12).

Since the issue is caused by dependencies, I am not sure how we should approach this. For the moment, I would encourage all the people that experience this issue to try again with the Test1 build and confirm this fixed the bug for them.

**Comment by kittsville** [comment]
Both `Test1` and `Test2` work for me.

The portable and installed 1.6.8 releases both fail with the `Unable to import shiboken2` error.

I have Python 3.9.2 installed but not an existing copy of PySide2:
```
C:\Windows\System32>python -V
Python 3.9.2

C:\Windows\System32>pip show PySide2
WARNING: Package(s) not found: PySide2
```

**Comment by Et0h** [comment]
@Kehanort @abhiraj2 @samurai-legend @Harry466 @kittsville @spidermatt99

I've updated the automatic build venerator to use 32-bit, and it works fine for me on Windows 10 64-bit.

Can people have who had problems please test Syncplay 1.6.9 and let me know what version of Windows they are using and if it worked for them:
* [Syncplay-1.6.9-Setup](https://github.com/Syncplay/syncplay/suites/3433017248/artifacts/81346628)
* [Syncplay_1.6.9_Portable](https://github.com/Syncplay/syncplay/suites/3433017248/artifacts/81346627)

**Comment by kittsville** [comment]
It works for me now (Windows 10 64-bit), many thanks 👍

**Comment by spidermatt99** [comment]
FYI, this is still not working for me on my Surface Pro 3. I know the hardware is old and do not know if this is having an impact. I have tried installing 1.6.9 and using the portable version. I've installed Visual C++ 2015 Redistributable, 32-bit and 64-bit. This is also after a completely clean install of Windows 10, so it seems unlikely that other software is interfering. However, the latest version works perfectly fine on my Alienware R3. I cannot tell what could possibly be different about the setups that would be interfering.

**Comment by Et0h** [comment]
@spidermatt99 Thanks for letting me know. Unfortunately I don't know what the key difference is between the build of 1.6.7 which works and the build of 1.6.9 which doesn't work and I don't have a Surface Pro 3 to test things out. For now it seems like you will have to choose between continuing to use 1.6.7, running Syncplay directly from Python, or trying to find a developer who can provide helpful suggestions.

**Comment by Et0h** [comment]
@spidermatt99 Does installing the Microsoft Visual C++ 2017 Redistributles fix the issue?

**Comment by yashkhamkar21** [comment]
Windows 10 32 bit...any of these links are not working

**Comment by Et0h** [comment]
> Windows 10 32 bit...any of these links are not working..please help

Does installing the 2015-2019 x86 package fix things? Go to https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-160 and install vc_redist.x86.exe.

**Comment by yashkhamkar21** [comment]
@Et0h no sir.. it's not working..

**Comment by Et0h** [comment]
@yashkhamkar21 Good to know. Please answer the following questions to help me better understand the issue:
* Does the current development build of Syncplay 1.7.0 work for you: https://github.com/Syncplay/syncplay/suites/4726530779/artifacts/130134033 ?
* Are you using a regular Windows 32-bit PC system or something more unusual?
* When you say "doesn't run" what precisely do you mean. At what point does it fail? Does it give any error message?
* Has Syncplay ever worked for you? If so, which version worked?

**Comment by yashkhamkar21** [comment]
We have tried above mentioned ways. Still it is not working. If possible for you, can we host a meeting on google meet?

**Comment by Et0h** [comment]
> We have tried above mentioned ways. Still it is not working. If possible for you, can we host a meeting on google meet?

Sure. Send an email to etoh@syncplay.pl with details on when you would be free for a meeting and we can arrange something and hopefully we can figure out what is wrong.

**Comment by yashkhamkar21** [comment]
Sure..Thank you so much for your kind response sir!
