### ISSUE TITLE
how does it work?

### ISSUE THREAD

**Issue by autoteelar** [Syncplay/syncplay#426]
im kind of confused how this works, do both my friends need to download the same file or does it have some sort of P2P way to send them it?

**Comment by Et0h** [comment]
Syncplay relies on users having the same files as one another. It is not a file sharing programme, and has nothing to do with P2P.

If you all have mpv and youtube-dl it does support streaming YouTube videos.

**Comment by Et0h** [comment]
https://www.youtube.com/watch?v=OuyYLOZBLI4 is quite a good guide on how to use Syncplay.
