### ISSUE TITLE
[Suggestion] Adminstrated rooms

### ISSUE THREAD

**Issue by Swag7User** [Syncplay/syncplay#428]
Hi

First of all, I've been using syncplay with my friends to watch movies for quite some time now with great success. Great piece of software really; Thanks to all developers and maintainers so far.

What I have realized with my usage however is that it can get quite chaotic if too many people are watching. 2-5 people is usually not a problem. Someone pauses to go to the toilet or something and then it resumes. Whenever we are more people (8+) this gets a bit tedious (even tough we are all in a voice server together and complain to each other, lol). 

What I wish was possible is that you could create a room with one or multiple participants being administrators/moderators of said room and only they have the capabilities to pause/start the movie. If a non admin pauses his client the other participants are unaffected from this and whenever he resumes playback he will be synced to the current timestamp where all other are. 
This would make managing bigger groups easier imo.
It would also be possible to hold "public" events, where there may be unknown, malicious participants that simply want to disturb the movie.
As far as I know this is currently not possible. Or did I simply oversee it somehow?

I have thought about implementing this myself, but the last time I coded something was more than 5 years ago and I never wrote a program bigger than ~20 lines in python, so I'm really not confident in my abilities. Therefore I though I could throw this idea as a suggestions here first and see if someone else would be interested in implementing it. If there is no one I may still try it myself.

**Comment by Swag7User** [comment]
Lol, I realized now that this is already possible. I just kinda assumed it would be in the join window, not when you're already in the room.

Well, this is good news however. :)

**Comment by Et0h** [comment]
Yeah, this feature was introduced back in 2015 under the named 'managed room' for the reasons you mention. An explanation for how to use the feature can be found at https://syncplay.pl/guide/client/  - see the section on 'Advanced Syncplay features' under the sub-heading 'Create managed room / Identify as room operator'. Glad you managed to find it eventually.
