### ISSUE TITLE
See the logfile 'C:\Program Files (x86)\Syncplay\Syncplay.log' for details ISSUE

### ISSUE THREAD

**Issue by Izothorp** [Syncplay/syncplay#429]
When I download and install the application, I encounter such an error.
![Ekran görüntüsü 2021-06-08 195159](https://user-images.githubusercontent.com/85576831/121226248-0257fa80-c893-11eb-869e-44e9326787cc.jpg)

**Comment by abhiraj2** [comment]
This is the same issue as #425

**Comment by Izothorp** [comment]
> This is the same issue as #425

Oh, sorry. Thanks!
