### ISSUE TITLE
Location of the IRC channel

### ISSUE THREAD

**Issue by Mikaela** [Syncplay/syncplay#430]
[The support page currently refers to freenode](https://syncplay.pl/guide/), but there are currently at least two disconnected networks claiming to be freenode, one which is being discontinued and one with all the old domains pointing to an entirely new network with new database (including no registered nicknames or channels).

* https://teddit.net/r/irc/comments/o01tmv/freenode_wipes_old_database_and_starts_over/

Personally I would prefer to not be associated with the new freenode, but should Syncplay so choose, I would connect there as I find Syncplay a very important tool in long distance relationships even without the pandemic going on.

\-

I would like to propose [ErgoChat](https://ergo.chat/) as the new IRC network if one isn't chosen yet, it's the official network of Ergo IRCd (while welcoming other communities and e.g. Palaver is there) leading IRCv3 adaption and has features like integrated bouncers that others haven't implemented yet. I am a bit biased though, being active in their community and running two instances for different networks.

Other popular choices are [Libera.Chat](https://libera.chat/) by the old freenode staff with similar IRCd&services and [OFTC](https://oftc.net/) where several FOSS projects have migrated to, while OFTC is a bit dated not supporting e.g. SASL Authentication to NickServ, but I understand them to be planning to migrate onto Solanum that Libera also uses.

**Comment by Et0h** [comment]
The current plan is to discontinue IRC support altogether and encourage people to use GitHub Issues instead.

Syncplay has an intentionally slow pace of development so we don't need a real time chat option, and Issues make it easy for people to search for if something has already been discussed.

**Comment by Mikaela** [comment]
In that case would it be possible to enable [GitHub discussions](https://docs.github.com/en/discussions) ?

**Comment by Et0h** [comment]
> In that case would it be possible to enable [GitHub discussions](https://docs.github.com/en/discussions) ?

Yes, that would be possible. We'll look into that.

**Comment by Et0h** [comment]
We have considered and approved your request for GitHub Discussions: https://github.com/Syncplay/syncplay/discussions - I'll add something linking to it to the client.
