### ISSUE TITLE
Add media / Open File doesn't show any of the files within a folder

### ISSUE THREAD

**Issue by MeltiBoi** [Syncplay/syncplay#438]
Hello! 

My friends and I have tried to create watch party, for 2 of us the program worked perfectly, for the other 2 we faced an issue where we couldn't use the add media option to add the folders into Syncplay. In addition to the media button being greyed out, when using the built in explorer, the same video files the other 2 had on their drives were unviewable as though the folders were empty.

We tried restarting, reinstalling, and running as admin and none of them worked. The only other notable thing is whenever we closed the app we saw a pop up with view the log which suddenly stopped appearing.

Hope this explains the issue well,

Appreciate y'alls work and such a great app <3

**Comment by Et0h** [comment]
My best guess is that they have some weird anti-virus programme which is trying to run Syncplay in a sandbox.

If that's not it then I need a lot more details, like what operating system or version of Syncplay are they using? Can they provide screenshots or screencording? Etc.

**Comment by Et0h** [comment]
Closing due to lack of response. Feel free to reply if you have more information.
