### ISSUE TITLE
SyncPlay error

### ISSUE THREAD

**Issue by redhawk5200** [Syncplay/syncplay#439]
Hi, I just got my new laptop and installed the latest version of SyncPlay but whenever I try to open it this error pops up immediately. I tried installing the Microsoft Visual C++ 2015 Redistributable Package but it didn't solve the problem. Any type of help would by appreciated. Thanks!!

<img width="375" alt="SyncPlay error" src="https://user-images.githubusercontent.com/59371949/127256669-661cb231-a30a-4dbf-802f-092c7aa645c2.PNG">

**Comment by Et0h** [comment]
Have you tried out the test builds at https://github.com/Syncplay/syncplay/issues/425 ?

**Comment by redhawk5200** [comment]
> Have you tried out the test builds at #425 ?

Can you please guide me how to do that? Thanks!

**Comment by redhawk5200** [comment]
> Have you tried out the test builds at #425 ?

Nevermind, your test1 zip file worked for meeee. Thank you so muchhh!
