### ISSUE TITLE
Media plays even though I am not ready

### ISSUE THREAD

**Issue by Acidic9** [Syncplay/syncplay#440]
While watching movies with my friend, I experience an issue where they can play the video even though I have paused and my status is "not ready".

I am on MacOSX BigSur and use VLC Media Player.

To reproduce:
  1. Connect with partner in room
  2. Both are ready, video is playing
  3. Person 1 pauses
  4. Person 2 pauses
  5. Person 2 unpauses
  6. Media is playing even though person 1 never unpaused too

Is this behaivour intended? Or is this a bug?

**Comment by Et0h** [comment]
Hi, as noted at https://syncplay.pl/guide/client/ this is the intended default behaviour. It can be configured (under settings -> Show More Settings -> Play/Pause), but it always allows you to unpause if you press unpause when you are already set as ready (although I think it should show a warning on the OSD to warn you that not everyone in the room is ready).

If you want Syncplay to play by default when you are all ready then you can use the 'Play when all ready' feature explained in the guide. You will first need to go to the menu in the main Syncplay window and select Window -> Show auto-play button. You can then check the 'Play when all ready' checkbox in the main window after having set the "Min users" to the minimum users you want to be in the room for the feature to activate (to prevent it from activating when you are still waiting for someone to arrive).

**Comment by Acidic9** [comment]
Oh okay. I am thinking that pressing spacebar in VLC force plays the video, while I should be manually clicking "I'm ready to watch!" in Syncplay?

**Comment by Et0h** [comment]
> You should remove this "ready" thing at all, it's not really any useful and only creates confusion

I find the feature useful for working in larger groups, which is why it was added as a feature. However, the feature is optional. As such, you can create your own private server with the ``--disable-ready`` command line switch to have a session without this feature.
