### ISSUE TITLE
LAV Filters Megamix mpc-hc filename

### ISSUE THREAD

**Issue by ImportTaste** [Syncplay/syncplay#453]
I use the following fairly popular codec pack: https://www.videohelp.com/software/LAV-Filters-Megamix

Something strange that it does is its filename for the main mpc-hc executable is different. Instead of `mpc-hc.exe` it's `shoukaku.exe`

I got around this issue by making a symbolic link of shoukaku.exe in the same directory it was in and named it mpc-hc.exe and pointed syncplay at it, which worked fine. But it would be convenient if syncplay recognized this filename by default.

**Comment by Et0h** [comment]
Adding `shoukaku.exe` shouldn't be a problem. Is the full path for it: `C:\Program Files (x86)\LAV Filters\x64\mpc-hc\shoukaku.exe`?

**Comment by ImportTaste** [comment]
> Adding `shoukaku.exe` shouldn't be a problem. Are the default full paths for it: `C:\Program Files (x86)\LAV Filters\x64\mpc-hc\shoukaku.exe` and ` c:\program files (x86)\lav filters\x86\mpc-hc\shoukaku.exe`?

Yes, that's correct. Thanks!

**Comment by ImportTaste** [comment]
@Et0h Heads up, I downloaded mpc-hc 1.9.15 today (the .zip one) and I noticed that the executable for the 64-bit version was named mpc-hc64.exe. Not sure if the setup version does the same thing, but regardless, mpc-hc64.exe should be added to the whitelist as well.

**Comment by Et0h** [comment]
I accepted the change but I've also now refactored the code to make it easier to add more filenames in the future. Please test the refactored version and confirm that it works.

**Comment by ImportTaste** [comment]
Seems to work fine, thanks.
