### ISSUE TITLE
Chat message new lines

### ISSUE THREAD

**Issue by arkangel-dev** [Syncplay/syncplay#464]
When you send a message with multiple lines from a client, the other clients get the full message. But SyncPlay clients only displays the first line only. Is this a bug or is it intentional?

![Untitled-1](https://user-images.githubusercontent.com/31138457/133042110-81c301a7-8d1b-42fa-91d1-f58d47919937.png)

Like the original Syncplay client gets the packet. But doesn't display the other 3 lines
```
{"Chat": {"message": "Line 1\nLine 2\nLine 3", "username": "User 2"}}
```

**Comment by daniel-123** [comment]
User interface of standard Syncplay client doesn't really allow you to send multiline messages in first place, so the case of displaying them was never really a consideration. Just as a side note - those messages are also displayed by media players in their own windows and those might behave differently.

IMHO best option would be to simply not allow multiline messages to be sent in your client. Only other alternative would be to implement proper handling of multiline messages everywhere, which would be a larger undertaking. And it would warrant some discussion about how to handle it all in contest of user experience. One immediate concern that was already noticed years ago is that long messages can disrupt the video viewing - whether multiline messages make this problem worse is probably a question worth asking.

**Comment by arkangel-dev** [comment]
> One immediate concern that was already noticed years ago is that long messages can disrupt the video viewing

That's actually a good point. I didn't think about that. I'll just add a toggle for that in my client and disable it by default.

Thanks
