### ISSUE TITLE
Certificate Error / Connection problems

### ISSUE THREAD

**Issue by ibib** [Syncplay/syncplay#465]
**Describe the bug**
When opening https://syncplay.pl/ I get NET::ERR_CERT_COMMON_NAME_INVALID
Additionally the syncplay software can't connect to the syncplay server.

**To Reproduce**
1. Try to open website or try to connect with syncplay to the syncplay server.

**Version and platform:**
 - OS: Windows 10 
 - Syncplay version and build type: 1.6.7 installed

**Comment by rbnrmn** [comment]
I think its an dns issue. I fixed it temporarily by adding  151.80.32.178 syncplay.pl to hosts file.
![image](https://user-images.githubusercontent.com/5112777/135719149-3265bee8-ec45-46a4-9acd-9623e87815ae.png)

**Comment by JBeckwith** [comment]
Can confirm having the same issues, Ubuntu 20.04, browser Firefox.

**Comment by daniel-123** [comment]
The issue should be fixed now + DNS propagation time - typically few minutes to an hour.

**Comment by rbnrmn** [comment]
Now its working for me 
![image](https://user-images.githubusercontent.com/5112777/135723457-e51ef122-4160-42f7-afd7-3a9d69219145.png)

**Comment by Et0h** [comment]
Thanks for the information. It looks like people with problems can try setting their primary DNS to the Google DNS (8.8.8.8).

**Comment by pranshuthegamer** [comment]
From india: ive tried changing dns, and it wont work i think the dns proagation takes longer in india

**Comment by Et0h** [comment]
@pranshuthegamer If necessary you can try manually adding the new IP to your hosts file as per rbnrmn's comments above, but it's important to later remove it or it will break if the IP address ever changes again.

**Comment by ibib** [comment]
For me the problem is gone. Maybe the issue should stay open for visibility another 24h or so until DNS propagation finished.
