### ISSUE TITLE
unable to connect to server on windows

### ISSUE THREAD

**Issue by pranshuthegamer** [Syncplay/syncplay#466]
**Describe the bug**
i open syncplay, connected to https://syncplay.pl:8996
and it says connection to server failed, and its only doing this on windows

**Expected behavior**
i expected it to work normally
ive tried to restart

**Version and platform:**
 - OS: Windows 10
 - Syncplay version and build type: Syncplay 1.6.9 portable

im using vlc

**Comment by Et0h** [comment]
This is because our new IP address hasn't gone out to all the DNS servers. You can wait for your DNS server to update, try a different DNS server, or add our new IP to your hosts file a remember to delete it later as per https://github.com/Syncplay/syncplay/issues/465

**Comment by pranshuthegamer** [comment]
this is weird, my dns is 1.1.1.1 an 8.8.8.8 and its working on a different browser and my phone

**Comment by Et0h** [comment]
@pranshuthegamer Your browser might have cached the old IP address. Closing and reopening it might result in the cache being flushed, or it might require your computer to be restarted.

**Comment by pranshuthegamer** [comment]
> 
> 
> @pranshuthegamer Your browser might have cached the old IP address. Closing and reopening it might result in the cache being flushed, or it might require your computer to be restarted.

i already did that

**Comment by Et0h** [comment]
You can also try using 8.8.8.8 as your primary DNS.

**Comment by pranshuthegamer** [comment]
> 
> 
> You can also try using 8.8.8.8 as your primary DNS.

dns search showed nothing for 8.8.8.8 either

**Comment by pranshuthegamer** [comment]
and adding 151.80.32.178 manually gives a certificate error

**Comment by Et0h** [comment]
I'm closing this thread to combine the conversation with #465
