### ISSUE TITLE
Installer option is blank when using Polish language

### ISSUE THREAD

**Issue by pawelkielb** [Syncplay/syncplay#468]
**Describe the bug**
An installer option is blank when using Polish language.

**To Reproduce**
1. Run the installer
2. Select Polish language
3. See blank option

**Expected behavior**
There should be a description of this option. In polish, it would be "Automatycznie sprawdzaj dostępność aktualizacji".

**Screenshots**
![obraz](https://user-images.githubusercontent.com/35242233/136096307-5d2a1baf-05cb-41ea-9179-c509068030a5.png)

**Version and platform:**
 - OS: Windows 10
 - Syncplay version and build type: Syncplay 1.6.9 (Installer)

**Comment by Et0h** [comment]
Thanks for reporting this. There is not currently a Polish-language version of Syncplay so I think the correct change needed is to remove it as an option.

**Comment by Et0h** [comment]
> Can I somehow contribute the translations for polish?

If you want to make a Polish translation of Syncplay then that would be great.

The changes needed to add a Polish translation is pretty much the same as the changes for the Turkish translation as set out at https://github.com/Syncplay/syncplay/commit/cd52e186b7c2caa7d13badca44ed46a3b7ff8905

**Comment by Et0h** [comment]
@Gieted Also, if you don't have much GitHub/programming experience then let me know and I can just give you a list of messages and you can provide the translations.
