### ISSUE TITLE
Website still references IRC/freenode

### ISSUE THREAD

**Issue by KanchiMoe** [Syncplay/syncplay#469]
**Describe the bug**
Per #430 and https://github.com/Syncplay/syncplay/commit/908c460e98cdad38a5f05a13781174fda87a67d8, references to IRC were removed to IRC/freenode in the app. However, it hasn't been removed from the website.

**To Reproduce**
Visit:
* https://syncplay.pl
* https://syncplay.pl/guide/

**Expected behavior**
Should be removed.

**Comment by tjaderxyz** [comment]
freenode is still mentioned on https://syncplay.pl/about/contact-us/

**Comment by Et0h** [comment]
Cheers, I've removed now updated that page.
