### ISSUE TITLE
Feature Request: Update Video Player when Shared Playlist updates

### ISSUE THREAD

**Issue by Zefferis** [Syncplay/syncplay#472]
When using a Shared Playlist and playing a video in MPV*, if the shared playlist has reached it's end and the player has paused on EOF (End of File), when a new file/URL has been added to the end of the Shared Playlist, the MPV Player does not automatically load the next file/url.

*Not tested in other media player applications

To update the shared playlist a user must either go back in MPV to restart the file in order to play -> trigger EOF again;; or go into SyncPlay and manually open the next playlist item.

Within MPV a user is able to run:
/qa <URL/FilePath> 
This updates the playlist in SyncPlay, but not within MPV, and does not trigger play of this newly added file/url if they are already at EOF of the latest shared playlist item.
________

Recommendation:

1) If a file is already paused on EOF and at the end of the shared playlist, trigger movement to the next shared playlist item if one is added / if the shared playlist is updated.

OR

2) Update MPV's Playlist to reflect that of the SyncPlay Playlist when the playlist is updated. 

Image of issue:
![image](https://user-images.githubusercontent.com/15270437/138271289-84b76ae7-2731-4ed0-8e8b-fbf129cd3e47.png)

**Comment by Zefferis** [comment]
@Et0h I'm so sorry for the delay in responding, I've been out of town until today;

I'll be using 1.7.0 with my group today and I'll provide additional feedback tomorrow.  Thank you for adding the "/qas" command!

**Comment by Zefferis** [comment]
Hey @Et0h my friends are very happy with the /qas command, it's been super helpful and useful for us!

We haven't seen any issues pop up with any of our uses!

**Comment by Et0h** [comment]
Thanks for letting me know @Zefferis. In that case I'll close this issue and the new feature will be included in Syncplay 1.7.0.
