### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by 0lhi** [Syncplay/syncplay#477]
More appropriate for some movies imo.
![Syncplay Dark](https://user-images.githubusercontent.com/74732674/139589290-fd2d7f86-8496-4abd-b4cb-babd5bc4c34a.png)

**Comment by Et0h** [comment]
Last time I looked at having a dark mode on Windows it seemed like a real headache to implement, so this would probably need someone with more PySide experience to develop it and make a pull request.

**Comment by Et0h** [comment]
If you want to discuss this further then please do so on this discussion from February 2020: https://github.com/Syncplay/syncplay/discussions/480
