### ISSUE TITLE
Feature Request: Optional Chat Log on the Client Side

### ISSUE THREAD

**Issue by 0lhi** [Syncplay/syncplay#478]
Could be saved inside */home/user/.config/Syncplay/Roomname.txt* (or Windows equivalent), if the Users enable this option inside their settings.

**Comment by Et0h** [comment]
If you would like to voice your support for this then please comment on https://github.com/Syncplay/syncplay/discussions/479 with relevant information on how you think it should work. As noted there, we were not aware of significant demand for the feature and wanted further details about how it ought to work.
