### ISSUE TITLE
Syncplay 1.6.9 won't launch.

### ISSUE THREAD

**Issue by notdysthymia** [Syncplay/syncplay#482]
So I can't seem to launch my Syncplay. I tried re-installing it and used a portable version of it. I can't seem to make the application to launch. There are also no logs whatsoever made by Syncplay which is weird.

So I tried finding a solution and it seems that from this [thread](https://github.com/Syncplay/syncplay/issues/425l), this particular [comment](https://github.com/Syncplay/syncplay/issues/425#issuecomment-850650624)'s Test1.zip seems to work fine for me.

System: Lenovo Ideapad 330S (Laptop)
Operating System: Windows 11

Just so you guys know launching the app (1.6.9) on my desktop (Win 10) works fine.

**Comment by Et0h** [comment]
@notdysthymia Does installing the 2015-2019 x86 package from https://aka.ms/vs/16/release/vc_redist.x86.exe as listed at https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-160 make syncplay work?

**Comment by anshumanpati6** [comment]
I had the same issue, and installing Visual C++ 2015-19 x86 (above solution) seems to fix it.

**Comment by notdysthymia** [comment]
> @notdysthymia Does installing the 2015-2019 x86 package from https://aka.ms/vs/16/release/vc_redist.x86.exe as listed at https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-160 make syncplay work?

It works now! Thank you. I really appreciate it as well @anshumanpati6.
