### ISSUE TITLE
VLC won't load the video even after setting up the playlist

### ISSUE THREAD

**Issue by Nckynck** [Syncplay/syncplay#484]
I already set up the media directory folder, but whenever I drag the file in the shared playlist it won't open up on my VLC player. I made sure to check the VLC player file path.
Any fixes for this?

**Version and platform:**
 - OS: Windows 10 64-bit operating system, x64-based processor
 - Syncplay version and build type: [e.g. Syncplay 1.6.9 portable]

**Comment by Et0h** [comment]
It works for me in VLC 3.0.16.

Some questions:
* What do you mean by 'drag the file in the shared playlist'? Are you talking about adding a file to the shared playlist?
* What version of VLC are you using?
* If you open a file through File->Open does VLC load it?
* If you load a file from VLC does it register as being played in Syncplay?
* Does Syncplay work fine with other players such as mpv or MPC-HC?

**Comment by Et0h** [comment]
Additional question:
* Have you specified a media directory within Syncplay? If so, is the file you are adding to the playlist within that media directory?

**Comment by Et0h** [comment]
I'm closing this issue due to a lack of required user input. If others have this issue then please provide further details.
