### ISSUE TITLE
Add mpv.net store version path detection to syncplay

### ISSUE THREAD

**Issue by soredake** [Syncplay/syncplay#494]
**Describe the bug**
Syncplay doesn't detect mpv.net from store.

**To Reproduce**
1. Install https://www.microsoft.com/en-us/p/mpvnet/9n64sqztb3lm
2. Run syncplay
3. mpv.net from store is not detected.

**Expected behavior**
Syncplay detected `$env:LOCALAPPDATA\Microsoft\WindowsApps\mpvnet.exe` as mpv.net binary

**Screenshots**

**Version and platform:**
 - OS: Windows 11 Pro
 - Syncplay version and build type: Syncplay 1.6.9

**Additional context**

**Comment by Et0h** [comment]
Syncplay was looking for mpv.net in the following locations:
* 'c:\program files\mpv.net\mpvnet.exe'
* 'c:\program Files (x86)\mpv.net\mpvnet.exe'

Thanks to your suggestion I will now add  '%LOCALAPPDATA%\\Microsoft\WindowsApps\mpvnet.exe' to the list.

**Comment by Et0h** [comment]
@soredake The way mpvnet.exe file in the WindowsApp seems to be some sort of weird dummy file which Python doesn't detect as existing, so I had to hack it to actually look for mpvnet.com instead but then run the .exe version.

When you have time please test it out at and let me know if it works properly for you - you can give either the portable or installer versions of Syncplay a try:
* Portable version: https://github.com/Syncplay/syncplay/suites/4809975579/artifacts/135272074
* Installer version: https://github.com/Syncplay/syncplay/suites/4809975579/artifacts/135272075

**Comment by soredake** [comment]
@Et0h thanks, it detects it now.
