### ISSUE TITLE
可以增加中文语言安装选项吗

### ISSUE THREAD

**Issue by Zhaodaidai** [Syncplay/syncplay#495]
我没有太多的编程经验  可以提供一个消息列表给我

**Comment by tompreuss** [comment]
> 我没有太多的编程经验 可以提供一个消息列表给我

Google translate:

> I don't have much programming experience can you provide me with a list of messages

Here's the messages in English: https://github.com/Syncplay/syncplay/blob/master/syncplay/messages_en.py and here's an example of a translation pull request: https://github.com/Syncplay/syncplay/pull/455

**Comment by Zhaodaidai** [comment]
通过机器进行了翻译  我稍加修改了一下  你看看可以嘛   
[messages_cn.txt](https://github.com/Syncplay/syncplay/files/7833194/messages_cn.txt)

**Comment by Zhaodaidai** [comment]
通过机器进行了翻译 我稍加修改 请把这个.txt改成.py
[messages_cn.txt](https://github.com/Syncplay/syncplay/files/7833197/messages_cn.txt)

**Comment by Et0h** [comment]
@Zhaodaidai Thank you very much for your work on this.

There are a few issues to be resolved, which I hope you or someone else who knows Chinese can help with:

1. Your translation is missing Chinese translations of the following messages from https://github.com/Syncplay/syncplay/blob/master/buildPy2exe.py

```
Associate  =  "Associate Syncplay with multimedia files."
Shortcut = "Create Shortcuts in following locations:"
StartMenu = "Start Menu"
Desktop = "Desktop"
QuickLaunchBar = "Quick Launch Bar"
AutomaticUpdates = "Check for updates automatically"
UninstConfig = "Delete configuration file."
```

2. I also noticed that a few terms from messages_cn.txt are not translated:
```
"file-difference-filename": "name",
"file-difference-filesize": "size",
"file-difference-duration": "duration",
"userlist-room-notification" :   "In room '{}':" ,   # Room
"userlist-file-notification": "File",
"controller-userlist-userflag": "Operator",
"commandlist-notification/room" : " \t r [name] - change room" ,
"commandlist-notification/pause": "\tp - toggle pause",
"client-connected-room-server-notification" : "{0}({2}) connected to room '{1}'" ,   # username, host, room
```

3. The name of the language is set as "Chinese", but this also wants to be translated. Would "中文" be the correct term to use to refer to the Chinese language in this context?

4. It looks like you may have used translation (for example contact-label translates the <a> anchor tag to '一个' which is the Chinese for 'a'). What have you done to manually review the translations to ensure that they are accurate?

5. Have you ensured that the {} tags are in the same order as the original (as listed in the comments)? While a different order could be used, this would need to use special code.

**Comment by Zhaodaidai** [comment]
1.
`Associate  =  "将 Syncplay 与多媒体文件关联。"
Shortcut = "在以下位置创建快捷键:"
StartMenu = "开始菜单"
Desktop = "桌面"
QuickLaunchBar = "快速启动栏"
AutomaticUpdates = "自动检查更新"
UninstConfig = "删除配置文件。"`
2.
`"file-difference-filename": "名称",
"file-difference-filesize": "大小",
"file-difference-duration": "持续时间",
"userlist-room-notification" :   "In room '{}':" ,   # Room
"userlist-file-notification": "文件",
"controller-userlist-userflag": "接线员",
"commandlist-notification/room" : " \t r [name] - change room" ,
"commandlist-notification/pause": "\tp - toggle pause",
"client-connected-room-server-notification" : "{0}({2}) connected to room '{1}'" ,   # username, host, room`
3.
对的 我不确定带{}的表情翻译后顺序相同  特殊代码的可以不用翻译英文就好  只要90%是中文 我觉得日常使用就很棒了！

**Comment by Et0h** [comment]
@Zhaodaidai Could you please check out https://github.com/Syncplay/syncplay/pull/500 and let me know if you are happy with this translation?

**Comment by Zhaodaidai** [comment]
[](javascript:;)非常好 我很满意
Very good. I'm satisfied

**Comment by Zhaodaidai** [comment]
Very good. I'm satisfied
