### ISSUE TITLE
Official hosted syncplay.pl servers having issues

### ISSUE THREAD

**Issue by TeamDman** [Syncplay/syncplay#498]
**Describe the bug**
Connecting to the syncplay.pl servers has been failing recently, and if you do manage to connect then it will shortly start dropping people from the room. It also takes a long time for slider changes to be replicated to all room members. Servers overloaded?

**To Reproduce**
1. Attempt to connect to one of the default syncplay.pl servers
2. If joined, try playing media with more than one person in the room and making time slider adjustments.

**Expected behavior**
People able to join rooms normally, no server lag.

**Version and platform:**
 - OS: Win10
 - Syncplay version and build type: 1.6.9, 1.7.0 development

**Comment by TeamDman** [comment]
I've set up my own server at `syncplay.teamdman.ca` for now in case anyone is looking for alternate public servers

**Comment by daniel-123** [comment]
I've went to the server and restarted the services, it indeed seemed to be under heavy load. The problem should be solved now.

**Comment by TeamDman** [comment]
Sounds good, will reopen if I encounter issues again <3
