### ISSUE TITLE
Can't setup TLS on server

### ISSUE THREAD

**Issue by ElDavoo** [Syncplay/syncplay#501]
**Describe the bug**
I can't setup a TLS server.

**To Reproduce**
1. Set up Let's Encrypt
2. Set up TLS  SyncPlay server
3. Try to connect

**Expected behavior**
Connection

**Error message**
Secure connection failed. The server uses an invalid security certificate. This communication could be intercepted by a third party. 

**Version and platform:**
Server
 - OS: Raspberry pi 4 with debian 11  
 - Syncplay version and build type: Syncplay 1.7.0 development, latest commit from git  

Client  
- OS: Windows 11, Ubuntu  
- Latest syncplay  

**Additional context**
The server only says "TLS Support is enabled", nothing else.  
The only thing the client says (even in debug mode), is:  
```
[00:53:14] client/server >> {"TLS": {"startTLS": "send"}}
[00:53:14] client/server << {"TLS": {"startTLS": "true"}}
```
The certificate is generated using Certbot and is made for HTTPS.  
HTTPS, of course, works with the same certificates.  
It is a wildcard certificate: It has both domain.com and *.domain.com .

**Comment by Et0h** [comment]
TLS isn't my speciality but you may find https://github.com/Syncplay/syncplay/wiki/TLS-support of use.

**Comment by ElDavoo** [comment]
I'm connecting from the Internet

**Comment by ElDavoo** [comment]
I made some debugging:
```
openssl verify -CAfile /etc/ssl/certs/ca-certificates.crt /opt/syncplay/dp/cert.pem
CN = domain.com
error 20 at 0 depth lookup: unable to get local issuer certificate
error /opt/syncplay/dp/cert.pem: verification failed
```
For some reason my let's encrypt certificates are not valid for openssl (maybe because I'm using the E1 Intermediate?), but they are fine for web browsers. This is for sure not syncplay's fault, but I have no idea on how to further debug.
