### ISSUE TITLE
[Bug] Syncplay opens on disconnected monitors, becomes unusable

### ISSUE THREAD

**Issue by Zefferis** [Syncplay/syncplay#504]
**Describe the bug**
When the Syncplay window is opened then closed within a secondary monitor; when re-opened the application attempts to open in the same monitor/location.

If the 2nd monitor is disconnected from the system, a newly opened syncplay window is no longer usable.
Syncplay window gains functionality when the monitor is re-added.

**To Reproduce**

1) Connect a secondary monitor.
2) Run/open Syncplay from Configurations Window
3) Move the Syncplay Window to the 2nd monitor.
4) Close Syncplay
5) Disconnect Monitor
6) Open Syncplay

**Expected behavior**
Syncplay Window should open in the active monitor.

**Version and platform:**
 - OS: Windows 10
 - Version: Syncplay 1.7.0 Development Snapshot 1 - Portable

**Additional context**
This has been tested by my friends as well, all testers have been using Windows 10 on the same version.

P.S. Thanks so much for the program! Donated earlier <3

**Comment by Zefferis** [comment]
It works! 

I didn't realize that the site itself would have the CLI Commands - totally forgot that was part of Syncplay. 
____
I have noticed something now that I can do a bit more experimenting with the --clear-gui-data command.

The Configuration Window always appears on the main monitor, regardless of where or how it is closed.
The Syncplay Client opens and remembers where it was last used/closed leading to potential GUI Issues.

For the users of Syncplay who are not familiar with CLI; 
Could an option be added to the Syncplay Configuration Window to "Clear Client GUI Data" or "Restore Client GUI" ?

![image](https://user-images.githubusercontent.com/15270437/153526678-be7b60b5-15de-4696-bee6-276d65463437.png)

Which could start the client with cleared GUI Data or restart the Syncplay exe using the --clear-gui-data flag for the user?

**Comment by Zefferis** [comment]
This is gonna sound a bit dumb but -

How to I build this project so I can make those changes and test it?

I've downloaded the repo, but I'm a 100% Python beginner 😓

**Comment by Et0h** [comment]
@Zefferis It's a bit tricky, so I've built if for you: https://github.com/Syncplay/syncplay/actions/runs/1833515590 - you can download the [Syncplay-1.7.0-Setup.exe](https://github.com/Syncplay/syncplay/suites/5277814262/artifacts/163305427) version or the [Syncplay_1.7.0_Portable](https://github.com/Syncplay/syncplay/suites/5277814262/artifacts/163305426) version.

If you ever want to learn Python and run Syncplay through it then you can check out https://syncplay.pl/about/development/ for instructions.

**Comment by Zefferis** [comment]
> That's great. In addition to not crashing, does it still save the position correctly when the second monitor is actually still connected?

No, it seems that if the client is used on the main monitor and closed it's position is saved.

If it is moved to a secondary monitor and closed, it will always re-appear on the main monitor when opened again.

It currently does not save the position on the 2nd monitor if it starts with the 2nd monitor available.
______
Closed in main monitor = Saved Position.
Closed in 2nd monitor = Always appears on main monitor.

**Comment by Et0h** [comment]
@Zefferis Can you please test my most recent update to #504 and let me know if it manages to fix the new bug while also not reintroducing the original bug.

- [Syncplay-1.7.0-Setup.exe](https://github.com/Syncplay/syncplay/suites/5423805566/artifacts/171651391)
- [Syncplay_1.7.0_Portable](https://github.com/Syncplay/syncplay/suites/5423805566/artifacts/171651390)

**Comment by Zefferis** [comment]
@Et0h 

When Multiple Monitors are Active:
- Syncplay Client Opens and Closes on the last known monitor (expected behavior) (PROGRESS 🎊 )

When Last Known Monitor is Disconnected:
- Syncplay Client attempts to open on the missing monitor (previous behavior) 
- Syncplay Client appears on the monitor when re-connected (previous behavior) ; 

CLI --clear-gui-data is still needed in this situation

____

The position is now saved on the extended monitor, but is not reset when that monitor is no longer available

1 part of the 2 part bug is now fixed 💪

**Comment by Et0h** [comment]
Thanks for testing this. If it causes the same problem with the previous behaviour then I'll revert the change and just go with the first fix. If someone with a second wants to come up with something which allows multiple monitor to save without causing problems on disconnection they are free to make a PR in the future.
