### ISSUE TITLE
Does not work on windows 11

### ISSUE THREAD

**Issue by Rinas234** [Syncplay/syncplay#507]
Syncplay does not work at all on Windows 11.

**Comment by Et0h** [comment]
I just tried using the Windows 11 64-bit VirtualBox Virtual Machine available from https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/ and both Syncplay 1.6.9 and the latest build of 1.7.0 ran fine for me alongside mpv.

Do you need to install the [Visual C++ 2015-2019 Redistributable Package](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-160) on a normal installation of Windows 11?

If that isn't he issue then I'll need more information on your set-up and what you mean by it not working.

**Comment by Et0h** [comment]
I'll close this for now due to a lack of information. However, if Syncplay 1.7.0 Beta 1 doesn't work for you then please let me know along with more information about what is not working about it.
