### ISSUE TITLE
Sponsorblock Integration from Youtube-DL from mpv(.net)

### ISSUE THREAD

**Issue by LShirohana** [Syncplay/syncplay#510]
**Describe the bug**
When you pass "--sponsorblock-mark=ALL" to youtube-dl, it will mark the chapters which have sponsors and so on, and automatically embed them into the video. When you set the youtube-dl config to automatically run that command, it does not work with syncplay.

**To Reproduce**
1. Open syncplay and join any server
2. Put a video that has sponsors and is marked by SponsorBlock into it.
3. The video will load in mpv.net (and mpv, I assume)
4. There is no chapters marked

**Expected behavior**
Chapters to be marked correctly with sponsorblock.

**Screenshots**
Normal mpv.net, just manually loading the URL into the player
![image](https://user-images.githubusercontent.com/24824311/155058445-4789e385-c66b-4f97-b2a3-521c9d7f4d76.png)

mpv.net opened up through syncplay.
![image](https://user-images.githubusercontent.com/24824311/155058611-5c734002-f886-43ad-b115-1f3d816d1080.png)

**Version and platform:**
 - OS: Windows 10 Build 19044
 - Syncplay version and build type: Syncplay 1.5.9 installer version

**Additional context**
I have tested multiple different things. I have attempted to set the youtube-dl settings to automatically be placed into mpv's config. I tried to set youtube-dl's config. I tried passing arguments through syncplay to mpv. None of them worked. It works if I open mpv alone. It does not work if I open it through syncplay's mpv. I looked into it, but syncplay's hook does not *seem* to change how things are passed.

Is there a reason it does not seem to work? or am I doing something wrong?

Update: I set the "arguments to player" section to `ytdl-raw-options="sponsorblock-mark=ALL"`, but it did nothing, seemingly. I watched the console, and I don't see anything popping out in particular. This is all it said when I loaded it with the command line options.

![image](https://user-images.githubusercontent.com/24824311/155059876-0a34062b-bd4a-4891-a8b2-e334a0d6ab81.png)

**Comment by Et0h** [comment]
I just tried on Windows and sponsorblock-mark didn't seem to do anything on the latest base mpv/ytdl, so I unfortunately can't help with this one.

**Comment by Et0h** [comment]
I've not been able to get sponsorblock to work with vanilla mpv.net so I'm not able to test this.

**Comment by LShirohana** [comment]
To be exact, I use [youtube-dlp](https://github.com/yt-dlp/yt-dlp), not youtube-dl, I should've specified, my bad.

To make vanilla mpv.net work with it, I simply created yt-dlp.conf next to the yt-dlp.exe, and inside the .conf file is nothing but

`--sponsorblock-mark=ALL`

Once you save that, you should be able to run yt-dlp and test:
1. It inserts the chapters into the file you download via yt-dlp.exe "URL_OF_VIDEO"
2. It inserts the chapters into the file you open with mpv.net via dragging the "URL_OF_VIDEO" onto the mpv.net window

Both of the above should work. If they do, then proceed to use that same mpv.net, which is now setup to work with yt-dlp natively, with syncplay, and it will fail to insert chapters.


It should be noted, that IIRC, mpv.net comes with an old, broken version of youtube-dl.exe with it (mpv.net GitHub hasn't had a release in like 8 months, I am using a version of mpv.net compiled in October by me)

If you need any help setting up the test steps, just let me know. I basically have yt-dlp in my PATH, so that mpv.net always uses it. If you have the local youtube-dl inside of your mpv.net folder, it will use that one.

Most importantly, I should mention. I don't think youtube-dl supports --sponsorblock, so thats why it might have not worked. Sorry!

**Comment by soredake** [comment]
> I've not been able to get sponsorblock to work with vanilla mpv.net so I'm not able to test this.

Try this command `(Get-Content $env:APPDATA\mpv.net\scripts\sponsorblock.lua).replace('local_database = true', 'local_database = false') | Set-Content $env:APPDATA\mpv.net\scripts\sponsorblock.lua`, it's working for me.

**Comment by Et0h** [comment]
While Syncplay supports mpv and mpv.net it does not support SponsorBlock.

> > I've not been able to get sponsorblock to work with vanilla mpv.net so I'm not able to test this.
> 
> Try this command in powershell `(Get-Content $env:APPDATA\mpv.net\scripts\sponsorblock.lua).replace('local_database = true', 'local_database = false') | Set-Content $env:APPDATA\mpv.net\scripts\sponsorblock.lua`, it's working for me.

Are you saying that with this change sponsorblock works with Syncplay when using mpv.net?

**Comment by soredake** [comment]
> While Syncplay supports mpv and mpv.net it does not support SponsorBlock.
> 
> > > I've not been able to get sponsorblock to work with vanilla mpv.net so I'm not able to test this.
> > 
> > Try this command in powershell `(Get-Content $env:APPDATA\mpv.net\scripts\sponsorblock.lua).replace('local_database = true', 'local_database = false') | Set-Content $env:APPDATA\mpv.net\scripts\sponsorblock.lua`, it's working for me.
> 
> Are you saying that with this change sponsorblock works with Syncplay when using mpv.net?

Yes, ads are skipped in mpv.net when using syncplay.

**Comment by LShirohana** [comment]
To be specific, that is because the script in question that soredake is talking about, sponsorblock.lua which is a plugin for mpv.net, does not use yt-dlp for sponsorblock integration, but instead uses its own https GET request on the sponsorblock database and manually inserts the chapters in via `mp.set_property_native("chapter-list", new_chapters)`

yt-dlp has sponsorblock integration, and *should* insert the chapters when it downloads the video. You can see this in vanilla mpv.net, and thats why I am confused. As far as I know, syncplay just inserts the video into mpv.net, and lets mpv.net play the video on its own. 

Theoretically, if mpv.net works with sponsorblock, then syncplay using mpv.net, should also support it. Does syncplay change the pipeline of mpv/mpv.net somehow? Does it load a video into mpv.net differently than how a normal user would just drag-and-drop a file into it?

**Comment by Et0h** [comment]
One difference could be that mpv.net is using Syncplay's path instead of the mpv.net path.

**Comment by LShirohana** [comment]
What do you mean path?

**Comment by Et0h** [comment]
I mean the start-in path (i.e. where a program initially searches for files with a relative path).

I'm closing this issue as Syncplay has no expected behaviour for sponsorblock as it is not an officially supported Syncplay feature. However, people are still free to reply to this issue if they wish to share any tips and tricks with others, etc.
