### ISSUE TITLE
Server password is visible to all system users

### ISSUE THREAD

**Issue by Infinisil** [Syncplay/syncplay#519]
**Describe the bug**
When passing the server password using `--password the-password`, the password can be seen by every user of the system due to command line arguments being accessible to all. There is currently no way to get around that because there's no other way to pass the server password.

**To Reproduce**
1. Start syncplay with `--password the-password`
2. Run `ps -ef | grep syncplay` as any user
3. See the password in the output

**Expected behavior**
Be able to pass the password in another way that doesn't expose it to other system users. This can be done by reading the password from a given file path instead, e.g. with
- A `--password-file` option
- A `PASSWORD_FILE` environment variable

**Version and platform:**
 - NixOS unstable
 - Syncplay 1.6.9

**Comment by Infinisil** [comment]
Similarly I believe the `--salt` option should get a `--salt-file` option that doesn't expose the salt in the command line arguments

**Comment by Et0h** [comment]
Are you aware of any real world use cases why you would need to keep this information hidden from other system users?

**Comment by Infinisil** [comment]
I can think of these scenarios:
- A multi-user server where an administrator hosts a private syncplay server. The other users on the system shouldn't be able to join, because they aren't given the password and aren't the people the administrator invites
- The password for syncplay could also be the password for another service, because passwords are frequently reused.

Another good reason imo is integration with `systemd`s new [credential management](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Credentials), which is based around passing secrets via files

**Comment by Infinisil** [comment]
Ohh, I just realized that the password can be set with `SYNCPLAY_PASSWORD` and the salt with `SYNCPLAY_SALT`. This should work well, environment variables can't be read by arbitrary users. Given that, I think this is mostly not an issue anymore.
