### ISSUE TITLE
SyncplayServer does not run with room permanence enabled

### ISSUE THREAD

**Issue by haz429** [Syncplay/syncplay#526]
**Describe the bug**
I have tried to start a private server with the new "room permanence" option, but when trying to run the server, the window would close immediately after opening and briefly show an error message (below). I've had no problems running a private server without this option, and the only thing I can assume is that it's just broken.

**To Reproduce**
1. Run the server with `--rooms-db-file [file]` option, for example:
`"C:\Program Files (x86)\Syncplay\syncplayServer.exe" --password X --salt Y --port Z --rooms-db-file [anything] --permanent-rooms-file [something else]`
I am not 100% sure what the last two parameters are meant to be, but I tried multiple different things (full path, .db file & .txt file, files with no extension)
2. Server window opens and immediately closes, showing an error message for a very brief amount of time.

**Expected behavior**
For the server to start with room permanence enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/91679433/164997595-ebf170bc-c36d-45a9-b9da-d2808b7b9a14.png)

**Version and platform:**
 - OS: Windows 10 64-bit
 - Syncplay version and build type: Syncplay 1.7.0 Beta 1 
 - Media player and version: n/a

**Additional context**
n/a

**Comment by Et0h** [comment]
@haz429 Please try the Windows portable development build from https://github.com/Syncplay/syncplay/suites/6312710765/artifacts/226583972 and let me know if that works.

```
Instructions on the command line switches from the docs:
--rooms-db-file [file] Enables room persistence. Path is
to where a database file should be loaded/create where room data will be
written to and read from. This will enable rooms to persist without
watchers and through restarts. Will not work if using
--isolate-rooms.

--permanent-rooms-file [file] Specifies a list of rooms
that will still be listed even if their playlist is empty. Path is to
where a text file with one room per line. This will require persistent
rooms to be enabled.
```

So if you want persistent rooms then all you need is --rooms-db-file which specifies a path for Syncplay to use to store the database file. However, if you want it to have rooms which are always listed even when they have no files in the playlist then you also have to specify a .txt file as permanent-rooms-file with one room per line

**Comment by haz429** [comment]
Thanks for the instructions, can confirm that room permanence works on the development build. One thing I have run into is that any rooms named in the  `--permanent-rooms-file` text file will be created upon server launch, but will disappear if a user leaves that respective room (with or without files in the playlist). Shouldn't affect me personally but I don't think it's working as intended.

**Comment by Et0h** [comment]
> Thanks for the instructions, can confirm that room permanence works on the development build.

Great!

One thing I have run into is that any rooms named in the `--permanent-rooms-file` text file will be created upon server launch, but will disappear if a user leaves that respective room (with or without files in the playlist). Shouldn't affect me personally but I don't think it's working as intended.

Yeah that's something which wants fixing. Thanks for the report.

**Comment by Et0h** [comment]
> One thing I have run into is that any rooms named in the `--permanent-rooms-file` text file will be created upon server launch, but will disappear if a user leaves that respective room (with or without files in the playlist). Shouldn't affect me personally but I don't think it's working as intended.

@haz429 f555c1d should resolve the issue of permanent rooms disappearing when it becomes empty.
