### ISSUE TITLE
Use --force-window and --idle=once with mpv

### ISSUE THREAD

**Issue by wiiaboo** [Syncplay/syncplay#53]
Allows Syncplay to open mpv without having a media file ready:

![](https://i.fsbn.eu/lzQ.png)

**Comment by Uriziel** [comment]
This is cool.

**Comment by Et0h** [comment]
Nice one. I'll look into that when I am next free. The important question is the version when the features wete added so Syncplay knows whether to use the functionality or not.

**Comment by wiiaboo** [comment]
[--force-window in 0.2.0](https://github.com/mpv-player/mpv/commit/f01744ac4e1da514aedbb51e6fad42fdb308937e), [--idle=once hasn't been applied to 0.7.3, I think?](https://github.com/mpv-player/mpv/commit/f56fcd71bbf302595afc19b3a8291cd47f485cfc) but --idle has been there since mplayer.

**Comment by Et0h** [comment]
Thanks for the intel. We try to maintain backwards compatibility within Syncplay so this kind of information is rather useful.

**Comment by wiiaboo** [comment]
Just --idle seems to work too, so it's probably safe to use that.

**Comment by Et0h** [comment]
Try https://github.com/Uriziel/syncplay/commit/a795acae0a2e8b19e50e0dfad34acbbeb17be585 and let me know if it works / if it causes any problems.

**Comment by wiiaboo** [comment]
Seems to be working fine. I'll try a few episodes with friends tomorrow.

**Comment by Et0h** [comment]
Quick fix: https://github.com/Uriziel/syncplay/commit/fd6d15790a93c3089b914c84e27a677951cecfa7

**Comment by wiiaboo** [comment]
No bugs so far. I think it's safe to close this?

**Comment by Et0h** [comment]
Yup, all seems good. Thanks for your contribution :)
