### ISSUE TITLE
syncplay.pl has broken links to the beta download

### ISSUE THREAD

**Issue by z411** [Syncplay/syncplay#531]
**Describe the bug**
Links to download the beta version of Syncplay in the official website syncplay.pl are broken

**To Reproduce**
1. Go to syncplay.pl
2. Click Download Syncplay 1.7.0 beta 1
3. Attempt to download any version

**Additional information**
The links point to 1.70beta1 where they should point to 1.7.0beta1 - I assume the release on Github got renamed but the links at syncplay.pl didn't get updated.

**Comment by Et0h** [comment]
Cheers, that's been fixed. You're right on all fronts.
