### ISSUE TITLE
VLC web UI doesn't work when using Syncplay; works fine without

### ISSUE THREAD

**Issue by Bestfast** [Syncplay/syncplay#533]
**Describe the bug**
As the title says, VLC web UI doesn't work when using Syncplay; works fine without.

**To Reproduce**
1. Enable VLC web UI 
2. Go to localhost:[port] 
3. Error message saying "Unable to connect"

**Expected behavior**

Web UI should ideally work out of the box.

**Screenshots**
![image](https://user-images.githubusercontent.com/31173611/172078955-0c601f63-7d30-446c-99dd-75c50fecc4fb.png)
![image](https://user-images.githubusercontent.com/31173611/172078965-7dfbc276-6396-417a-ae96-d7cf03c8dbfe.png)
![image](https://user-images.githubusercontent.com/31173611/172078973-87361820-45b4-4d92-a7da-d9b3abe08016.png)

**Version and platform:**
 - OS: Windows 11 64bit
 - Syncplay version and build type: Syncplay v1.6.9 installed, same happens with v1.7.0 beta portable
 - Media player and version:  VLC, any version (tested with latest 3)

**Comment by Bestfast** [comment]
the issue here is using `--extraintf=luaintf`, as it overrides the preferences. I don't know if it's an issue with Syncplay or VLC, but for the moment being having that argument is an issue.

**Comment by Et0h** [comment]
@Bestfast Can you please try the latest build of Syncplay-1.7.0-ubuntu-18.04-x86_64.AppImage at https://github.com/Syncplay/syncplay/suites/9912347462/artifacts/479228859 and let me know if it fixes your UI issues?

**Comment by Et0h** [comment]
I don't know whether or not this is something that can be readily solved from Syncplay as it is not a feature I use. I do know that any changes to how Syncplay launches VLC would need testing on multiple platforms.
