### ISSUE TITLE
Cannot connect to server from China after updating to 1.7.0 beta

### ISSUE THREAD

**Issue by jiang-yuan** [Syncplay/syncplay#534]
Describe the bug
Cannot connect to server after updating to 1.7.0 beta
We can connect to sever and see each other at the room when we use 1.6.9 but in 1.7.0 beta, it always shows time out and cannot see each other

Version and platform:

OS: Windows 11 64-bit
Syncplay version and build type: 1.7.0 beta
Media player and version: mpv

**Comment by Et0h** [comment]
I'm not based in China so it's a difficult one for me to debug. If you know a Python developer based in China then it might be helpful if they could run through the different commits to figure out precisely which change caused the issue. However, I'll do what I can to figure it out. My best guess at the moment is that it relates to the introduction of support for the Chinese language, but it might be something random like an update to a third-party library.

Some questions:
- Does this issue occur for both the Chinese and English language options?
- Is this problem just for you, or have others from China also experienced the same problem?
- Do both versions give the same message regarding TLS (e.g. "Secure connection established (TLSv1.3)", "Secure connection failed", etc?
- Are you connecting to one of the public servers or a privately-run server? Does changing to a different type of server help?

**Comment by Et0h** [comment]
As I've had no response on this issue in some time I'll assume the issues has somehow resolved itself.
