### ISSUE TITLE
Accelerating video on mpv does not lead to accelerated playback for other participants.

### ISSUE THREAD

**Issue by vi** [Syncplay/syncplay#535]
**Describe the bug**

When I accelerate or slowdown video with mpv, I expect syncplay to duplicate those actions across other participants. However, it resyncs and resets speed back to 1x instead.

**To Reproduce**

1. Start two instances of `syncplay`, join the same private room. mpv starts along with syncplay's window.
2. Add a file from media folder to playlist and playit.
3. Start playing the file.
4. In one of mpv's window, press `}` key to speed up video 2x.

**Expected behavior**

Other mpv also switches playback speed to 2x without explicit keyboard input. 

**Actual behavior**

Other mpv still plays video at 1x. syncplay detects it and rolls back video speed to 1x.

**Version and platform:**
 - OS: Linux Debian Bullseye
 - Syncplay version and build type: 1.6.7 (Yoitsu)
 - Media player and version: mpv 0.32.0

**Additional context**

**Comment by daniel-123** [comment]
I'm afraid nothing has really changed since this was discussed in #339 

Syncplay isn't designed to sync playback speeds across and adding this feature would need very significant amount of effort. Possibly up to including rethinking entire syncing algorithm.

**Comment by Et0h** [comment]
@daniel-123 has summarised it well and linked to relevant discussions so I'll not go into details. In summary, while I can see why this would be a neat feature it is a big development headache due to how Syncplay and its protocol have been designed.
