### ISSUE TITLE
"Pause" button under Other commands reads "Play" in Linux

### ISSUE THREAD

**Issue by uguu123** [Syncplay/syncplay#56]
![syncplay](https://cloud.githubusercontent.com/assets/11448379/6629125/e9cd916c-c8e1-11e4-9ef0-7f5e693212c4.png)

**Comment by Uriziel** [comment]
Cannot reproduce.
Please update to the newest version.

**Comment by daniel-123** [comment]
@uguu123 this already got fixed along with UI overhaul in 1.3 (currently in "beta").

**Comment by uguu123** [comment]
@daniel-123 
Alright, good to know! Thanks guys and good work!
