### ISSUE TITLE
Kodi support

### ISSUE THREAD

**Issue by Skaytacium** [Syncplay/syncplay#562]
I made a Kodi addon that adds Syncplay support. The source code is over at https://github.com/Skaytacium/synko. Installation can be done by downloading the repository as a zip file and installing in Kodi. Any testing will be very beneficial for bug identifying.

Also atleast one person decided to implement the [syncplay protocol](https://syncplay.pl/about/protocol/).
![joke](https://syncplay.pl/wp-content/uploads/2014/03/counter.gif)

**Comment by Et0h** [comment]
As there is already a discussion for this at #560I ask that people discuss the Kodi support there instead of on this issue.

**Comment by Skaytacium** [comment]
My bad. I created this issue to add Kodi in the Syncplay list of supported players since my addon has reached its first release.
