### ISSUE TITLE
[Feature request] Add audio and video call support

### ISSUE THREAD

**Issue by albuic** [Syncplay/syncplay#568]
Hello,

I was wondering whether it would be possible to add audio call ? (and video maybe as some people might like it)
I know it is not an easy task, but for audio, this is a nice feature to share reactions and talk during the movie.
At least discussing how you would want those in case I start working on them would be helpful.
Oh and... Thank you for Syncplay as it is a wonder !

Regards,
A.

**Comment by Someone7un7** [comment]
yeah I agree it needs at least audio call

**Comment by Et0h** [comment]
Syncplay is intended to be used in conjunction with a third-party communications solution such as [Mumble](http://mumble.sourceforge.net/). There are many VoIP options out there and people can choose the one which is right for their group.

**Comment by albuic** [comment]
I totally understand that creating our own is out because of complexity/maintenance/cost but I was thinking about integrating other solutions in here not to need to open the web browser.

**Comment by Et0h** [comment]
> I totally understand that creating our own is out because of complexity/maintenance/cost but I was thinking about integrating other solutions in here not to need to open the web browser.

Discord and Mumble can both be used as applications on your computer and so don't require you to use your web browser beyond needing to download them in the first place.

**Comment by daniel-123** [comment]
In general I think it's effectively impossible to do.

The main reason for it is simple: VoIP and video calls are orders of magnitude more complicated than Syncplay is. This is akin to trying to add a whole, fully functional web browser to a basic text editor.

As far as integration with other VoIP software, that doesn't sound impossible from get go at very least. Typically I see myself using [Muble](https://www.mumble.info/) and I've never really felt of anything missing with just running it alongside, especially as like @albuic mentions I don't like to run entire browser for that. What kind of integration would be useful? Would it be anything different from run of the mill overlay already present in Mumble?

**Comment by powerjungle** [comment]
Lots of people have gotten used to "one program does it all", but that's not a good development model. Sticking to [KISS](https://en.wikipedia.org/wiki/KISS_principle) is important for reliability and efficiency. Even if there were enough developers here willing to do this, it still would be a pretty bad idea.

**Comment by Et0h** [comment]
I'm closing this issue for the reasons given by @daniel-123 and @powerjungle - Syncplay is not trying to do it all, and for good reason.
