### ISSUE TITLE
[Feature request] Subtitle suport

### ISSUE THREAD

**Issue by albuic** [Syncplay/syncplay#569]
Hello,

I was wondering if there is a way to add subtitles in Syncplay for all users ?
It seems that only the video can be added and it would be nice to be able to add the subtitles for everyone. I know that some players just replace the extension with ".srt", this might be a first step maybe ?
It might also be linked with #408 to add ".m3u" playlists.

Regards,
A.

**Comment by Et0h** [comment]
I can't think of any media-agnostic way of doing this. I think many media players will automatically load a .srt file if it is in the same local directory as a media file, and tools such as mkvmerge exist to allow for subtitles to be added to files.

**Comment by zlmao666** [comment]
similar request so I'm not making a new thread, but would it be possible to add support for the --sub-file=<file-name> CLI option for mpv? syncplay currently (1.7.0 beta) errors out and says that it's an invalid CLI option
