### ISSUE TITLE
Successfully reached server but not connected

### ISSUE THREAD

**Issue by YounesArj** [Syncplay/syncplay#579]
I set up Syncplay on my private server using [this](https://nischay.pro/blog/setup-syncplay/) tutorial. but on the client, it doesn't fully connect to the server.
```
[06:54:14] Attempting to connect to [REDACTED]:23875 
[06:54:14] Attempting secure connection 
[06:54:14] Successfully reached [REDACTED] ([REDACTED])
[06:54:14] This server does not support TLS
```
tested it on different computers and the results were the same 

as suggested in #256 I changed the port but it didn't help 

I tried looking up a more detailed tutorial on how to set up a private server but there wasn't much - #445

[debug](https://gist.github.com/YounesArj/a7ceb57a586bf9857f6c1e47002a827b)

it works fine on official servers and behaved as expected
```
[06:54:55] Attempting to connect to syncplay.pl:8996
[06:54:55] Attempting secure connection
[06:54:55] Successfully reached syncplay.pl (151.80.32.178)
[06:54:56] Secure connection established (TLSv1.3)

Hello ,

The Syncplay latest is available from http://syncplay.pl/


[06:54:56] Successfully connected to server
```
it would be perfect if you could provide a detailed and accurate tutorial for setting up private servers 

 - Ubuntu 22.04.1 LTS
 - Windows 10 64-bit
 - Syncplay 1.6.9 portable
 - VLC 3.0.16

**Comment by albertosottile** [comment]
@YounesArj In the first example, does the client connect to the server even without TLS support?

**Comment by YounesArj** [comment]
> @YounesArj In the first test, does the client connect to the server even without TLS support?

On the very first try, I got the TLS error above 
so I looked into it and found [this](https://github.com/Syncplay/syncplay/wiki/TLS-support#server), and implemented it
after doing TLS stuff, it shows the error randomly, sometimes it gives the error sometimes not

**Comment by daniel-123** [comment]
@YounesArj One thing I'd recommend starting with is just installing the syncplay package - it's available on Ubuntu and you don't need to go out of your way to download anything from git:
`sudo apt install syncplay`

With regards to TLS - for private server I'd say you shouldn't bother with it unless you know what you are doing. Server will work without it, you will simply see the message in the client about it.

**Comment by YounesArj** [comment]
> @YounesArj One thing I'd recommend starting with is just installing the syncplay package - it's available on Ubuntu and you don't need to go out of your way to download anything from git: `sudo apt install syncplay`

I'm trying to set up syncplayServer on my VPS, not the client, so others can connect to it and...
I installed Syncplay using your method but it seems it's only the client for watching videos
I couldn't find any option to host it for others to join

**Comment by daniel-123** [comment]
@YounesArj the command to run the server is `syncplay-server`, though looking at it - that command is in the recommended dependencies of main Syncplay package. So it might not have gotten installed by default.

**Comment by YounesArj** [comment]
> @YounesArj the command to run the server is `syncplay-server`, though looking at it - that command is in the recommended dependencies of main Syncplay package. So it might not have gotten installed by default.

`syncplay-server` was installed automatically 
```
syncplay-common/jammy,now 1.6.9+repack1-4 all [installed,automatic]
syncplay-server/jammy,now 1.6.9+repack1-4 all [installed,automatic]
syncplay/jammy,now 1.6.9+repack1-4 all [installed]
```
but still no different result than the previous method

**Comment by Et0h** [comment]
The only things I can think of is to try mpv rather than VLC and to check your firewall settings. The other guidance we have is available from https://syncplay.pl/guide/server/
