### ISSUE TITLE
Can't open Syncplay with MPV in Manjaro Linux

### ISSUE THREAD

**Issue by SeveroGXD** [Syncplay/syncplay#580]
**Describe the bug**
I cannot start the program. Previously it worked without any problem, however I suppose after a system update Syncplay started giving this error message: 
![image](https://user-images.githubusercontent.com/72367951/210474539-5022342f-7427-472d-a7fe-bf1e20f9b7ef.png)

This is what I get when run in the terminal with --debug:
![image](https://user-images.githubusercontent.com/72367951/210474862-c5c00e0a-9e70-4ad4-a49c-7338e691f649.png)

**Version and platform:**
 - OS: Manjaro Linux (KDE)
![Screenshot_20230103_233043](https://user-images.githubusercontent.com/72367951/210473779-5e4978cc-6fc9-46f3-b97d-6bf6756d8a94.png)

 - Syncplay version and build type: Syncplay 1.6.9-5
![Screenshot_20230103_233312](https://user-images.githubusercontent.com/72367951/210473917-fd73c80d-8c16-4042-b271-eb8a52699e41.png)

 - Media player and version:  mpv 1:0.35.0-2
![image](https://user-images.githubusercontent.com/72367951/210474041-61e307bf-40a7-4881-b8a1-48bc40f8d9b4.png)

**Comment by SeveroGXD** [comment]
I think I got a more detailed screenshot.
![image](https://user-images.githubusercontent.com/72367951/210476532-3181d6a1-8eba-4a88-b8a1-2e19316c66df.png)

**Comment by cold-nagai** [comment]
Try running mpv with --no-config option. [This](https://github.com/Syncplay/syncplay/issues/509#issuecomment-1049897942) thread might help.
![image](https://user-images.githubusercontent.com/126972909/222987415-2653cc57-cfb5-48f1-88ae-d47761917dce.png)
