### ISSUE TITLE
wildcard matching in trusted domains

### ISSUE THREAD

**Issue by name-snrl** [Syncplay/syncplay#587]
Wildcard matching doesn't work. I tried `trusteddomains = ['youtube.com', 'youtu.be', 'eu.ngrok.io']` and `trusteddomains = ['youtube.com', 'youtu.be', '.eu.ngrok.io']`.

Details here: _Originally posted by @name-snrl in https://github.com/Syncplay/syncplay/issues/437#issuecomment-1424710089_

**Comment by Et0h** [comment]
@name-snrl &  @Tremolo4 : I've created a [pull request](https://github.com/Syncplay/syncplay/pull/588) which hopefully adds the feature requested here, but it uses regex so it's worth giving it lots of testing to make sure it doesn't break the trust logic in some weird way. Please give it a try via https://github.com/Syncplay/syncplay/actions/runs/4237707314 and let me know if it works via the pull request discussion.

**Comment by Et0h** [comment]
The change has now been made. All that is left is to consider what, if any, changes want to be made to the client documentation at https://syncplay.pl/guide/client/

**Comment by Et0h** [comment]
I've now updated the client guide, so this issue is being closed.
