### ISSUE TITLE
Warning with cryptography when starting a private syncplay server (QUESTION)

### ISSUE THREAD

**Issue by ChillyPigeon742** [Syncplay/syncplay#604]
I dont know if its just me or not but whenever i start my syncplay server on 1.7.0 final it gives me this warning before starting my server:
**frozen zipimport:259: UserWarning: You are using cryptography on a 32-bit Python on a 64-bit Windows Operating System. Cryptography will be significantly faster if you switch to using a 64-bit Python.**

I've tried reinstalling python, reinstalling the cryptography module, installing the cryptography module with no binaries, and nothing has worked for me. When I try the third one I mentioned it gives me a error and i dont know what it means, I know that a warning isnt the end of the world but it would be nice to get rid of it.

Some help would be greatly appreciated, a image of the warning message is also attached.
![image](https://user-images.githubusercontent.com/96913971/236396650-fefd380b-36b4-42a1-9b98-cd495f182ba3.png)

**Comment by Et0h** [comment]
I also get that error. As far as I know it won't have any real world impact on the performance of the Syncplay server and can just be ignored.

**Comment by ChillyPigeon742** [comment]
Ah ok thanks a lot
