### ISSUE TITLE
Do not destoy the main window when the player becomes unresponsive

### ISSUE THREAD

**Issue by selurvedu** [Syncplay/syncplay#605]
**Describe the bug**
Sometimes the player may freeze for various reasons (e.g. system being unresponsive, switching to another tty/vt, etc.), and this should not make the Syncplay main window disappear in an instant.

**To Reproduce**
1. Start Syncplay and connect to a server.
2. Execute `pkill -STOP mpv && sleep 120 && pkill -CONT mpv`, this should take two minutes.
3. See the main window disappear and a message box pop up reading "mpv has not responded for 120 seconds so appears to have malfunctioned. Please restart Syncplay."

**Expected behavior**
I should be able to e.g. save the chat log or the playlist content. The last one was really painful before persistent playlists were added, and it is still desired for those servers where persistence is not available.

**Version and platform:**
 - OS: GNU/Linux
 - Syncplay version and build type: Syncplay 1.7.0 from [Arch Community repository](https://github.com/archlinux/svntogit-community/tree/packages/syncplay/trunk)
 - Media player and version: mpv 0.35.1

**Additional context**
While mpv is frozen via SIGSTOP, Syncplay is not responsive as well. So I cannot do anything before it's too late. This may or may not be another bug, since I can't reliably make the player freeze without using SIGSTOP.

**Comment by Et0h** [comment]
I'm not sure if Syncplay freezing if mpv freezes is an issue with Syncplay or an issue with Python MPV JSONIPC by @iwalton3 or a bit of both.

I use Windows so the reproduction instructions don't work for me, but thanks for providing them - hopefully someone will be able to use them to try to figure out why Syncplay freezes and how to fix it in a way which doesn't break stuff.
