### ISSUE TITLE
Sync issues in Managed room

### ISSUE THREAD

**Issue by BlepBlep** [Syncplay/syncplay#607]
I'm not entirely sure if it's a bug, or if I am misunderstanding how things work, so I apologize if that is so. I watch stuff regularly with 3-4 other friends, and I always had an issue where I would constantly notice my player slowing down to "catch up" with the others. I also noticed that whenever I would skip around, Syncplay would "ignore" my skip, and skip back to where we were before. This would happen like 5-10 times in a row and would be incredibly frustrating when all I'm trying to do is skip the opening of a show.

Because I'm usually the one to set up everything and say when to go and whatnot, I decided to make us a managed room with me as the operator. From my understanding, this means that everyone else syncs to **me** instead. However in practice, I have found that others regularly become desynced, sometimes up to 15-20 seconds ahead, requiring them to manually fast forward to force syncplay to re-sync them to the correct time. This has us double-checking the time with eachother constantly in the middle of watching things. I have a relatively stable internet, and am usually the one to host when it comes to playing games and whatnot.

I've also noticed that since setting up the Managed Room, now only I can see the "X people are ready" messages that pop up, leading to some people to not even know they aren't marked as ready yet. (I have it set to start when everyone readies up) I'm not sure if there is some setting I, or they, need to change to get it to show up again.

I have confirmed that they all (me as well) have not changed any of the default settings in Syncplay, same version, and all of us use the same exact video player and version. Same exact OSs as well.

**Version and platform:**
 - OS: Windows 10 64-bit 22H2
 - Syncplay version and build type: Syncplay 1.7.0 (Final) (though this has happened for the past few versions)
 - Media player and version: MPV.net v6.0.3.2

**Comment by Et0h** [comment]
I'll look into managed room behaviour when I have time, but as a preliminary matter I note that you stated that you used MPV.net, but what media player are the other people using?

If anyone is using VLC, then one thing you should do is see if the same problem occurs if everyone is using either mpv or MPV.net.

**Comment by BlepBlep** [comment]
As I stated already, all of them use the same exact MPV.net as I do. We sometimes have a user join us who uses Manjaro and VLC, but they rarely join us and haven't complained about any of the issues (not that they don't happen, they are just the "I don't care" type so they haven't mentioned anything)

**Comment by Et0h** [comment]
> I'm not entirely sure if it's a bug, or if I am misunderstanding how things work, so I apologize if that is so. I watch stuff regularly with 3-4 other friends, and I always had an issue where I would constantly notice my player slowing down to "catch up" with the others. I also noticed that whenever I would skip around, Syncplay would "ignore" my skip, and skip back to where we were before. This would happen like 5-10 times in a row and would be incredibly frustrating when all I'm trying to do is skip the opening of a show.

This is not an issue I have ever experienced other than when testing with VLC. I use Syncplay all the time with either mpv or mpv.net.

To me that sounds like you have the setting "Never slow down or rewind others (experimental)" enabled in your Syncplay sync settings.

If setting that to off doesn't work (or if it was never on) try using a clean installation of Syncplay (e.g. you can rename the syncplay.ini file in %APPDATA% to see what it looks like if you reset to default values) and a clean installation of mpv.net (using default conf settings).
 
> Because I'm usually the one to set up everything and say when to go and whatnot, I decided to make us a managed room with me as the operator. From my understanding, this means that everyone else syncs to **me** instead. However in practice, I have found that others regularly become desynced, sometimes up to 15-20 seconds ahead, requiring them to manually fast forward to force syncplay to re-sync them to the correct time. This has us double-checking the time with eachother constantly in the middle of watching things. I have a relatively stable internet, and am usually the one to host when it comes to playing games and whatnot.

I just tried to re-create this with a clean installation of mpv.net and could not reproduce. I had one copy of mpv.net which was the room operator and a viewer using mpv, and when I deliberately slowed down the mpv playback it jumped forward to match the room operator rather than the other way around.

> I've also noticed that since setting up the Managed Room, now only I can see the "X people are ready" messages that pop up, leading to some people to not even know they aren't marked as ready yet. (I have it set to start when everyone readies up) I'm not sure if there is some setting I, or they, need to change to get it to show up again.

Now that's a bug. I seem to recall that how it was to avoid complaining to non-controllers that other non-controllers are not ready to avoid it annoying them with information that they cannot do anything about, but it was never intended to prevent you from not being told that you are not set as ready.

**Comment by Et0h** [comment]
Okay, I've now made the following changes to the 'not ready' display behaviour.

**For non-controlled rooms:**
* If someone in the room is not ready, it will always show you and keep the message visibile until they are ready.

**For controlled rooms:**
* If either you or the room operator(s) are not ready, it will always show you, and keep the message visible until they are ready.
* If people who are not you and are not room operators are not ready, it will indicate as such when the readiness message is displayed but will not keep the not ready message on the screen.

This is included in build 106. You can try it out from https://github.com/Syncplay/syncplay/actions/runs/5032737126

If would be helpful if someone could test it to confirm that is behaving reasonably.

**Comment by BlepBlep** [comment]
> To me that sounds like you have the setting "Never slow down or rewind others (experimental)" enabled in your Syncplay sync settings.

> If setting that to off doesn't work (or if it was never on) try using a clean installation of Syncplay (e.g. you can rename the syncplay.ini file in %APPDATA% to see what it looks like if you reset to default values) and a clean installation of mpv.net (using default conf settings).

Can confirm I kept that setting off, though I will try the clean installation route. Should I tell the others to do so as well, just to make sure it's not them either? Maybe my internet just isn't as stable as I thought it is. Thank you for the prompt replies and changes for the ready messages!
