### ISSUE TITLE
Client does not sync playlist clearing actions to the server

### ISSUE THREAD

**Issue by gavtroy** [Syncplay/syncplay#609]
Following the changes for #567, the `playlistNeedsRestoring()` check prevents a playlist clearing action from being processed. Although the GUI does still show an empty playlist, other users will still see the previous playlist.

This also makes it impossible to delete persistent rooms.

**Comment by Et0h** [comment]
Thanks for reporting this. I can confirm the issue but as I'm away from home I can't work on it right now. If anyone wants to try to fix this and make a PR then feel free.

**Comment by Et0h** [comment]
@gavtroy Please try out my fix at https://github.com/Syncplay/syncplay/actions/runs/5158492715 and let me know if it works.

**Comment by gavtroy** [comment]
Deleting both definitions of `playlistNeedsRestoring()` looks like an accident. That version gets stuck in a connection loop for me. Assuming the correct change was `return self._client.playlistMayNeedRestoring and ...` then from my very limited testing it appears to work.

**Comment by Et0h** [comment]
That's weird, thanks for letting me know. There was a definition for playlistNeedsRestoring in my PyCharm version, but it must not have committed properly for some reason. I've now updated GIT HEAD to add in the version which I was using to develop the fix and you can test with that.

**Comment by gavtroy** [comment]
Yes that seems to be working well. Thanks for coming with a fix.
