### ISSUE TITLE
Is it possible to change the position of the chat output in mpv?

### ISSUE THREAD

**Issue by TheLongLife** [Syncplay/syncplay#615]
If not, would it be possible to add that as an option in the future?

**Comment by Et0h** [comment]
Yes, it is possible - it is just not obvious how to do so.

As https://syncplay.pl/guide/client/ states:
> There are a number of settings which can be changed by modifying the syncplay.ini / .syncplay file. If your change breaks something then you can just delete the entry to restore it to the default, but you might still want to make a backup of your configuration file before making changes. You can figure out what these do by searching for the setting name in the Syncplay source code.
>
> [GUI] options relating to mpv OSD and chat input:
> Numeric: chatMaxLines, chatTopMargin, chatLeftMargin, chatBottomMargin, chatOSDMargin, notificationTimeout, alertTimeout, chatTimeout
> Boolean (True/False): chatMoveOSD

If you increase the value of chatTopMargin in syncplay.ini it will move the chat further down the mpv window.

If you reduce the value of chatMaxLines in syncplay.ini it will make the output more compact because it won't display as many lines at once.

(From the GUI configuration chat tab you can also change the output style from 'chatroom style' to 'scrolling style', but I'm guessing that is not what you are interested in doing.)

**Comment by TheLongLife** [comment]
Thank you, I just wanted to move it down.  
And I guess I have one more question...Is it possible to make messages appear bottom-top, instead of top-bottom?

**Comment by Et0h** [comment]
I've just done some experimentation, and one way to do that is to modify the \Syncplay\resources\syncplayintf.lua file.

Specifically, you need to change line 170 to:
> 				chat_ass = to_add .. chat_ass

If you want the chat output to move upwards as well, you will need to change line 263 to:
> 				local ypos = opts['chatTopMargin'] - (#chat_log * 24 * FONT_SIZE_MULTIPLIER)

Note:
* The number 24 represents the default font size. If you have a larger different font size then you will need to change this number accordingly.
* You will need to re-implement this change whenever you update Syncplay.
* If you have Syncplay installed to Program Files then you may need to run your text editor in Administrator mode to be able to modify the file.

**Comment by TheLongLife** [comment]
Not quite what I had in mind :sweat_smile:. I'm sorry, my explanation wasn't very good.  

I was thinking more like how traditional chat works: the new message appears just above the input field, and then the new one pushes the previous message one line above it. So like the chat in the Syncplay window.

But in all honesty, it's not a big deal at all. It's a very minor detail. Thank you for your time. I appreciate your help. I've been using Syncplay for a few days now, and it's awesome.
