### ISSUE TITLE
bomi support

### ISSUE THREAD

**Issue by Alzarath** [Syncplay/syncplay#62]
bomi seems to be a branch of mpv, so I imagine it wouldn't be too much trouble to add support for it.

http://bomi-player.github.io/

**Comment by Et0h** [comment]
Thanks for the suggestion. My understanding is that Bomi uses an mpv wrapper so you can't simply control it as if it were mpv. Instead I think Syncplay would have to use an undocumented JSON API which may not have all the right features. I'll look into it at some point, unless someone gets there first, but I'm not expecting an easy win.

**Comment by Et0h** [comment]
Just had a quick look and can confirm that adding support doesn't look like it'll be easy.
