### ISSUE TITLE
Connection to server lost

### ISSUE THREAD

**Issue by aks1508** [Syncplay/syncplay#624]
Connection with server keeps getting lost everytime I open Syncplay and create a room

**To Reproduce**
1. Open Syncplay
2. Create and Join room
3. 

**Expected behavior**
Server connection should be established 

**Screenshots**
![image](https://github.com/Syncplay/syncplay/assets/79452350/5cf97a61-6db1-4b5e-b046-482c92468141)

**Version and platform:**
 - OS: Windows 10 64-bit
 - Syncplay version and build type: Syncplay v1.7.0
 - Media player and version:  VLC 3.0.18 32-bit]

**Additional context**

**Comment by Et0h** [comment]
I can confirm that our public servers seem to be a bit unreliable at present. I have asked our server administrator to restart the public server. Hopefully when they do so this will resolve the issue. Private servers should be unaffected by this issue.

**Comment by Et0h** [comment]
The public servers should be working again now :-)

**Comment by aks1508** [comment]
Yep its working now!

**Comment by Serkodim** [comment]
Same problem again right now ((

![Снимок экрана 2023-09-23 194611](https://github.com/Syncplay/syncplay/assets/145862371/1f98d25d-9897-4dbc-9b85-61ac4b4cef25)

**Comment by Et0h** [comment]
Thanks for reporting this issue again. We've restarted our public servers and that should have fixed it.
