### ISSUE TITLE
Windows Installer Generates Shortcuts For Wrong (Admin) Account

### ISSUE THREAD

**Issue by mindmeshlink** [Syncplay/syncplay#625]
**Describe the bug**
When installing with Windows 7 from a non-admin account, the program only puts shorcuts in the start menu of the account with administrator privilege.

**To Reproduce**
1. Have windows 7 with an account with Administrator access, and an account without.
2. Run installer as non-administrator.
3. When Windows prompts for the admin access needed to install system files, select the admin account and enter the password.
4. When finished, the application will not be on the start menu of or generally visible to the original user who prompted the installation. 

**Expected behavior**
The installed program should generate shortcuts for the user who prompted the installation. To many people, "I installed this application and it didn't show up in the start menu" is synonymous with "It didn't install", so it should probably be treated as a breaking bug equivalent to the application not installing (Though, for reference, the application *is* accessible to the non admin user if they navigate to the install directory.)

**Version and platform:**
 - OS: Windows 7
 - Syncplay version and build type: Syncplay Windows Installer 1.7.0
 - Media player and version:  Not Relevant.

**Additional context**
Reporting for a friend here, so any additional system details may have a small wait for me to check in.

**Comment by Et0h** [comment]
Thanks for letting us know of this issue. I have now updated https://syncplay.pl/guide/trouble/ to advise people on Windows 7 to use the portable version of Syncplay and noting that Windows 7 reached End of Life status on the 14th of January 2020. If someone figures out an easy fix for this which limits its impact to Windows 7 (or Win 7 and Vista) then they are free to make a pull request.
