### ISSUE TITLE
Windows Installer Pins Instead of Adding To Start Menu

### ISSUE THREAD

**Issue by mindmeshlink** [Syncplay/syncplay#626]
**Describe the bug**
The Windows installer pins Syncplay's executable to the start menu, rather than *adding* it. 

**To Reproduce**
1. Install Syncplay.
2. Look at Start menu.
3. Syncplay is pinned, but does not exist in the larger list of programs. 

**Expected behavior**
Syncplay should create a start menu folder for the multiple executables (Syncplay, Syncplay Server, and Syncplay Uninstaller) it creates. Pinning is for frequently used/important programs, chosen by the user, and the list of programs should be a reliable source of *all* programs installed, including ones which are also pinned. 

**Version and platform:**
 - OS: Windows 7
 - Syncplay version and build type: Syncplay 1.7.0 Windows Installer
 - Media player and version: Not Relevant

**Additional context**
Discovered alongside #625, again by my friend.

**Comment by Et0h** [comment]
Thanks for letting us know of this issue. I have now updated https://syncplay.pl/guide/trouble/ to advise people on Windows 7 to use the portable version of Syncplay and noting that Windows 7 reached End of Life status on the 14th of January 2020. If someone figures out an easy fix for this which limits its impact to Windows 7 (or Win 7 and Vista) then they are free to make a pull request.
