### ISSUE TITLE
Syncplay won't open

### ISSUE THREAD

**Issue by Pandoroz** [Syncplay/syncplay#630]
**Describe the bug**
The program doesn't open, I installed the 32bit NET version with the requirements described but nothing, I saw another post where it works with the portable version 1.6.8.

**To Reproduce**
1. When I open the program

**Expected behavior**

**Screenshots**
![image](https://github.com/Syncplay/syncplay/assets/128830542/f2e42d1e-074f-4fa8-9f03-ca9a86b3bdba)

**Version and platform:**
 - OS: Windows 10 Pro x64
 - Syncplay version and build type: Syncplay 1.7.0
 - Media player and version:  VLC 3.0.18 Vetinari

**Additional context**

**Comment by Et0h** [comment]
Hi, some questions:
1. What do you mean by NET version?
2. Have you installed Microsoft Visual C++ 2015 Redistributable Update 3 available from https://www.microsoft.com/en-us/download/details.aspx?id=53587 ?
3. Do you get anything in %APPDATA%\Syncplay.log - you may need to run Syncplay with the --debug command line switch.
4. Does the 1.7.1 RC1 portable available from https://github.com/Syncplay/syncplay/releases/tag/v1.7.1-RC1 work?
5. Does 1.6.8 portable work for you?
6. Are you using any anti-virus which might be causing problems?

**Comment by Pandoroz** [comment]
1. I mean the package year or whatever you can call it
2. Yes, I also tried to install it from the given link and got an error:
https://pastebin.com/pJyPFPSK
4. I didn't think about logs, how should I add --debug?
<details><summary>Logs</summary>During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "syncplayClient.py", line 17, in <module>
  File "syncplay\ep_client.pyc", line 8, in main
  File "syncplay\clientManager.pyc", line 9, in run
  File "syncplay\ui\ConfigurationGetter.pyc", line 553, in getConfiguration
  File "syncplay\ui\ConfigurationGetter.pyc", line 455, in _forceGuiPrompt
  File "syncplay\ui\ConfigurationGetter.pyc", line 419, in _promptForMissingArguments
  File "syncplay\players\playerFactory.pyc", line 11, in getAvailablePlayerPaths
  File "syncplay\players\mpv.pyc", line 80, in getDefaultPlayerPathsList
  File "syncplay\players\mpv.pyc", line 103, in getExpandedPath
  File "ntpath.pyc", line 651, in realpath
  File "ntpath.pyc", line 601, in _getfinalpathname_nonstrict
FileNotFoundError: [WinError 53] Impossibile trovare il percorso di rete: '\\\\UnLockCatch\\tools\\vcruntime;'</details>
 5. No
 7. No, if I remember the package downloaded from another post didn't have a library or anything similar
 8. No
 9. Yes
10. No

**Comment by Et0h** [comment]
Thanks for answering those questions.

Please try the Visual Studio 2015, 2017, 2019, and 2022 redistributable which as per https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170 is available from https://aka.ms/vs/17/release/vc_redist.x86.exe and let me know how it works.

**Comment by Pandoroz** [comment]
I tried reinstalling it but nothing, the program continues to crash.

**Comment by Et0h** [comment]
I'm not talking about re-installing the 2015 Redistributable, but installing the 2015-2022 Redistributable.

**Comment by Pandoroz** [comment]
I intended to reinstall the 2015-2022 Redistributable

**Comment by Et0h** [comment]
Does `syncplayServer.exe` run okay for you?

**Comment by Pandoroz** [comment]
![image](https://github.com/Syncplay/syncplay/assets/128830542/c9390b22-85ae-4a7c-8128-9bb2aa90137f)

Yes, i think

**Comment by Et0h** [comment]
As you are the only Windows user reporting this issue I'm not sure what can be done to fix it, but it seems like a Windows library issue rather than a Syncplay issue. If you figure out how to fix it please let us know so we can update our guidance.

In the meantime I can provide a workaround through a a console version of Syncplay that does not rely on those Windows dependencies. Please download this from: https://github.com/Syncplay/syncplay/actions/runs/6214207919?pr=631

**Comment by Pandoroz** [comment]
After an hour of understanding how it works I managed to understand and it works, I'll see if I can fix it and I'll inform you, thank you very much

**Comment by MicroMihai4** [comment]
The problem persists.
I've tried all the ways, but nothing is wrong.
The log is full of this:

"<frozen zipimport>:259: UserWarning: You are using cryptography on a 32-bit Python on a 64-bit Windows Operating System. Cryptography will be significantly faster if you switch to using a 64-bit Python.
WNDPROC return value cannot be converted to LRESULT
TypeError: WPARAM is simple, so must be an int object (got NoneType)"

**Comment by Et0h** [comment]
@MicroMihai4 Is this issue reasolved by running an x64 (64-bit) version of Syncplay.exe/syncplayConsole.exe? 
https://github.com/Syncplay/syncplay/actions/runs/6488218619

**Comment by Et0h** [comment]
I've tried running Syncplay.exe and SyncplayConsole.exe on fresh VM installs of Windows 10 (32-bit and 64-bit) and they all work once vc_redist.x86.exe is installed. I also tried syncplayServer.exe on Windows 11 and that worked too.
