### ISSUE TITLE
Add UI to show current state

### ISSUE THREAD

**Issue by alok0** [Syncplay/syncplay#64]
I'd like to see something that shows the current state of room (or state of each user), eg, playing/paused and what the current time is.

**Comment by Et0h** [comment]
It might be possible to provide some of this information through a modified version of the console-based userlist. Could you please provide a more detailed example of what you want and why you want it.

**Comment by Uriziel** [comment]
@Et0h, as far as I remember it is not possible to show states of other room easily (without modifications to protocol, server code or butchering the server).

**Comment by Et0h** [comment]
Yeah, that's my understanding too, and is why I am interested, because if that is what the user wanted then it isn't feasible in the short term.

**Comment by Uriziel** [comment]
@Et0h not even sure it would be possible in Syncplay 2

**Comment by Et0h** [comment]
@Uriziel Good to know.

**Comment by alok0** [comment]
Oh, uh, I guess I wasn't really clear. I just want the current state of the current room to be displayed in the ui.

**Comment by Et0h** [comment]
Why are you interested when that information is already displayable in the media player?

**Comment by alok0** [comment]
Call it paranoia,  but it makes me worry when there is no indication the application is working or not.

**Comment by DerGenaue** [comment]
Actually this could just be integrated into the player controls in Syncplay.
Who doesn't want them just deactivates them.
Currently there are only controls but they could easily also give feedback about the current state.
(Change Time-Box content when not selected / editing; deactivating play / pause depending on state)

**Comment by Et0h** [comment]
Disabling play/pause as appropriate to show state seems reasonable, but I'm not convinced about changing the seek time input box as it is useful for people to know what it will seek to if they press the seek button.

**Comment by DerGenaue** [comment]
After it is edited you can just stop the updating for either 10 seconds or until the set time button is pressed
