### ISSUE TITLE
How to use QT theme on appimage?

### ISSUE THREAD

**Issue by astridbunny** [Syncplay/syncplay#641]
I'm using 1.7.0 as an appimage on void linux. I have made my own qt theme which I would like all of my applications to use, but I'm unsure how to get it to use the theme I've made. The theme is set as default in qt5ct, but syncplay isn't using it.

**Comment by Et0h** [comment]
I'm a Windows user so I could be wrong but my understanding is that the AppImage bundles it's own version of PyQt so if you want a custom theme then you have to install Syncplay directly as per https://syncplay.pl/guide/client/

Some aspects of the Syncplay theme are hard coded so you might need to make some tweaks to constants.py to get things looking perfect.

**Comment by Et0h** [comment]
I am closing this issue because Syncplay has now discontinued AppImage support. See: https://github.com/Syncplay/syncplay/issues/643 for more details. If an issue recurs with the Deb package or Tarball then please re-open this comment and let us know of the details.
