### ISSUE TITLE
[Feature Request] Current Offset in Set Offset

### ISSUE THREAD

**Issue by Xeiv** [Syncplay/syncplay#642]
Hello, I'd like to request to show the currently set offset in the set offset popup windows. 
Sometimes the offset needs to be changed mid playback but when it's been paused/seeked multiple times you need to search for the current offset in the middle of it all which is kinda tedious.
If the Current Offset would be shown in the Set Offset popup it would be easy to know what it is and adjust accordingly.

**Comment by Et0h** [comment]
That's a great idea as it improves usability for those who set offsets, doesn't have any backwards compatibility issues, and is easy to implement. As such, I've made the change and it will be included in Syncplay 1.7.1. You can test it out at https://github.com/Syncplay/syncplay/actions/runs/6816222476

**Comment by Et0h** [comment]
@Xeiv Can you please test the feature and confirm that it works as expected.

**Comment by Xeiv** [comment]
> @Xeiv Can you please test the feature and confirm that it works as expected.

Yep it's working pretty well however when I use decimals and put something like 10.50, it will set it as 10.050

**Comment by Et0h** [comment]
@Xeiv Thanks for testing this. I think the problem you identified was a pre-existing bug rather than something introduced by these changes.

I've hopefully fixed it, though. Please try https://github.com/Syncplay/syncplay/actions/runs/6883506778 once it has finished building and let me know.

**Comment by Xeiv** [comment]
@Et0h Yeah, it's fixed now, thank you 👍

**Comment by Et0h** [comment]
Excellent, in that case I'll close this issue as resolved.
