### ISSUE TITLE
NOTICE: Syncplay has discontinued support for AppImage and Snap

### ISSUE THREAD

**Issue by Et0h** [Syncplay/syncplay#643]
We have made the difficult decisions to drop support for AppImage and Snap on the basis that maintaining support for these packaging options proved unworkable. As such, we ask that Linux users use Deb packages or install Syncplay directly in line with the instructions at https://syncplay.pl/guide/install/

**Context:**

Syncplay is complex software that both relies on various packages (including PySide) and interfaces with media players. This makes it inherently difficult to make a package that will work on all systems, especially as we have no AppImage/Snap specialists as part of the core dev team. We managed to get a set-up that worked for most people, but it didn't work for everyone (somewhat defeating the point of Snaps and AppImages) and when we tried to update our dependencies the packages stopped working on all systems.

Given that Syncplay is a small project, we came to the conclusion that we just don't have the resources to maintain AppImage and Snap support.

If you don't care about new features you can still try the AppImage for Syncplay 1.6.9 which is available from https://github.com/Syncplay/syncplay/releases/download/v1.6.9/Syncplay-1.6.9-x86_64.AppImage but be aware that we do not officially support this AppImage.

**Comment by Mikaela** [comment]
I wonder whether it would be possible to support pipx for installation or if that is perhaps already unofficially supported and would just be a matter of documenting it?

**Comment by Et0h** [comment]
@Mikaela I'm a Windows user so have never used pipx, and I've not heard any reports from anyone trying to get it to work with Syncplay.

From the pipx documentation it looks like if you wanted to make it work with Syncplay you might need to use the `inject` command to add VLC and/or mpv media players to the Syncplay environment. You might also need to inject ytdl if you are using mpv for streaming functionality.

If anyone does mange to get it work to get it to work then it would be helpful if they provided us with instructions for others who want to go down this path.

**Comment by ryuuzaki42** [comment]
Hello @Et0h,  thanks for all hard work,  and also for all the contributors.

For those looking for an AppImage version...
I create one, however with no guarantee that it will work on all distributions.
https://github.com/ryuuzaki42/Syncplay_AppImage

All code used to create the AppImage can be viewed in the build.yml file.
https://github.com/ryuuzaki42/Syncplay_AppImage/blob/main/.github/workflows/build.yml

**Comment by daniel-123** [comment]
@ryuuzaki42 Thanks for the work on trying to make something out of the AppImage. I tried and it sadly didn't start on my Debian Unstable system with the key part of error message being:

    qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
    This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
    
    Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.

I have grown quite sick of that message (and ones like it) when I was trying to make the AppImage work :)

As a side note - I noticed your build settings to use ubuntu-latest. Per best practices for AppImages and to ensure wider compatibility they recommend using oldest supported base system (ubuntu-20.04 in case of current Github Actions). Not that it actually helped me when I tried all of the available versions...

**Comment by ryuuzaki42** [comment]
Hello @daniel-123, thanks for the feedback.

I have tested the AppImage in some "Debian like", Ubuntu e Kubuntu last version, and its work.
In the Ubuntu, my Calibre 7.1.0 AppImage give this same error, xcb plugin not found when I try run it as root, as normal user its runs OK.

Witch version of Debian are you using? With the version I may can see the error and may see what is wrong.

Try install libxcb-*, may resolve the problem

`apt install libxcb-xinerama0 
`
or
`apt install libxkbcommon-x11-0`

https://stackoverflow.com/questions/68036484/qt6-qt-qpa-plugin-could-not-load-the-qt-platform-plugin-xcb-in-even-thou
https://discuss.pixls.us/t/solved-could-not-load-the-qt-platform-plugin-xcb-in-even-though-it-was-found/17677

Thanks about the note of Ubuntu version in Github Actions, I will take look.
Keep me posted.

**Comment by daniel-123** [comment]
@ryuuzaki42 The specific version is Debian 13 Trixe (current testing branch).

I already have all of the libxcb libraries present on my system - I installed them a few times when I was playing with trying to make the appimage work myself.

I'm always running the appimage as standard user. I've now tried it as root as well, but the final message is identical.

**Comment by ryuuzaki42** [comment]
Hello @daniel-123

I tested the AppImage in VM with Debian Testing Live and seems to work fine.

https://cdimage.debian.org/cdimage/weekly-live-builds/amd64/iso-hybrid/
[ISO]	[debian-live-testing-amd64-kde.iso](https://cdimage.debian.org/cdimage/weekly-live-builds/amd64/iso-hybrid/debian-live-testing-amd64-kde.iso)	2023-12-04 03:17 	3.0G

![image](https://github.com/Syncplay/syncplay/assets/11284038/5752c97c-d826-4f41-b654-37abba962c88)

I only installed VLC to a "full" test.

Try extract the AppImage and run.
Or try install Syncplay in our machine and check if have others libs besides the one in the .yml file.
