### ISSUE TITLE
Click on other users to play their stream

### ISSUE THREAD

**Issue by bitingsock** [Syncplay/syncplay#65]
Assuming that the other person(s) in your server are playing url streams, clicking on their filename in order to send it to your own player would be a much desired feature among my friends. What do others think?

**Comment by Et0h** [comment]
Thanks for the suggestion. Being able to easily switch to what someone else is playing sounds like a great idea, although it may be less useful when we have shared playlists as that would offer similar functionality. In relation to streams, whether it could work would depend on whether the URIs can be requested by Syncplay from the media players (and I assume they can). Once retrieved, this would have to either be transmitted as a filename (replacing stream name, which is currently used by VLC) or the protocol would need to be modified to be able to transmit both the title and the URI of a stream.

**Comment by Et0h** [comment]
Okay, should work now for mpv. VLC will be a bit harder because the URIs it gives are very long and therefore cause GUI issues. This means I either need to figure out a way of getting a shorter URI from VLC, or I have to improve the GUI to handle overly long URLs.

**Comment by Et0h** [comment]
Okay, should work for VLC now. Windows test build at: http://syncplay.pl/syncplay-ClickToSwitchToMedia-Beta-1.zip (*NIX users can just use Git HEAD). Please test it and let me know how it goes.

**Comment by Et0h** [comment]
Version 2 of the beta http://syncplay.pl/syncplay-ClickToSwitchToMedia-Beta-2.zip - Adds error messages and fixes an issue if no file was playing.

**Comment by bitingsock** [comment]
seems to work for me. thanks for the work man!

**Comment by Et0h** [comment]
It should work even better in latest beta: http://syncplay.pl/Syncplay_1.3.2_Beta_Setup_[2015_08_14].exe

**Comment by Et0h** [comment]
The feature is now implemented in http://syncplay.pl/syncplay-1-3-2/ - thanks for your suggestion.
