### ISSUE TITLE
`syncplay --no-gui` is difficult to terminate from the CLI

### ISSUE THREAD

**Issue by alxpettit** [Syncplay/syncplay#650]
**Describe the bug**

**To Reproduce**

Run `syncplay --no-gui`. Hit Ctrl+C. It kills the child process (MPV, in my case), but just hangs instead of terminating fully.

**Expected behavior**

It should gracefully terminate.

**Version and platform:**
 - OS: NixOS 23.11
 - Syncplay version and build type: 1.7.0, NixOS cache
 - Media player and version:  mpv 0.36.0

**Supplemental Information**

Terminates with the following being printed:
```
ERROR:        <class 'twisted.python.failure.Failure'>
ERROR:  [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
]
ERROR:  Connection to the other side was lost in a non-clean fashion: Connection lost.
Socket connection died.
Traceback (most recent call last):
  File "/nix/store/sh99jh1wr8lpl4z56yxmvn0qq86a3fwg-syncplay-1.7.0/lib/syncplay/syncplay/vendor/python_mpv_jsonipc/python_mpv_jsonipc.py", line 166, in run
    current_data = self.socket.recv(1024)
                   ^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
```

Do note that I've seen this bug before -- in fact, I encountered it last year on Arch Linux, IIRC -- so it is not a Nix-specific issue. The problem most likely stems from the exception handling being too broad and catching the KeyboardInterrupt, and assuming the exception means something else.

**Comment by Et0h** [comment]
Is this the same issue as https://github.com/Syncplay/syncplay/issues/322 or a different issue?

**Comment by alxpettit** [comment]
Well, I believe Ctrl+C sends SIGINT, so yes. Whoops!
