### ISSUE TITLE
Adding `--input-ipc-server=\\.\pipe\mpvsocket` to "player arguments" results in double `input-ipc-server` in arguments

### ISSUE THREAD

**Issue by soredake** [Syncplay/syncplay#658]
**Describe the bug**
Adding `--input-ipc-server=\\.\pipe\mpvsocket` to "player arguments" results in double `input-ipc-server` in arguments:
![image](https://github.com/iamkroot/trakt-scrobbler/assets/5204968/effeeeec-709b-45f7-905f-69e185b969f5)
I don't think it should work like this.

**To Reproduce**
1. Install latest syncplay.
2. Install latest mpv.net and configure it's path in syncplay.
4. Add `--input-ipc-server=\\.\pipe\mpvsocket` to player arguments.
5. Look at process arguments in "process explorer" app or another.
6. Double `input-ipc-server` is set.

**Expected behavior**
Only `--input-ipc-server=\\.\pipe\mpvsocket` should be used.

**Screenshots**
![image](https://github.com/iamkroot/trakt-scrobbler/assets/5204968/effeeeec-709b-45f7-905f-69e185b969f5)

**Version and platform:**
 - OS: Windows 11 Pro 23H2
 - Syncplay version and build type: Syncplay 1.7.1
 - Media player and version:  mpv.net 7.0.0.5

**Additional context**
Originally reported here https://github.com/iamkroot/trakt-scrobbler/issues/266#issuecomment-1873410881

**Comment by Et0h** [comment]
Discussion of how Syncplay handles input-ipc-server is already taking place in https://github.com/Syncplay/syncplay/issues/529 so I think this issue should be considered a duplicate.
