### ISSUE TITLE
Add Tray Icon

### ISSUE THREAD

**Issue by fermuch** [Syncplay/syncplay#66]
A "close to tray" would be nice :grinning:

**Comment by Uriziel** [comment]
I don't think syncplay deserves any place in tray
28 cze 2015 04:03 "Fernando Mumbach" <notifications@github.com> napisał(a):

**Comment by Et0h** [comment]
Why would it be nice? I share Uriziel's views and can't think of a use case where it would be useful, and even if there were nice for some reason then it would still not be worth the time it would take to implement on all operating systems.

**Comment by Et0h** [comment]
You can use tools to minimise any app to the System Tray, e.g. http://rbtray.sourceforge.net/ - feel free to try them out and tell us how well they work.

**Comment by fermuch** [comment]
The use case is simple.

I just don't see why we should have the GUI of Syncplay open while we're watching something, since everything we need to know is being showed right on the player. I often close accidentaly the window, since I use two screens and I forget it kills the program and the player if I close the window.


I'm not so used to PyQt, but I know it has QSystemTrayIcon. Maybe that'd help to get the sys tray icon on all the OSes? If you don't mind, I may create a PR to add the systray icon this weekend, but I'm not a Qt nor Py dev, so my code may be somewhat ugly.

Is that okay with you?

**Comment by Uriziel** [comment]
You can start Syncplay without gui

**Comment by fermuch** [comment]
I sometimes do that. But a friend, who uses Windows, and is not used to windows' shell, so she isn't really sure if everything is okay or not with a bat script. So that option is not viable for her.

IMO a tray icon would add simplicity to the app.
What are the cons of adding a tray icon?

**Comment by Et0h** [comment]
Only cons I can think of is that it takes time to code (not an issue for me if you do it), and that some silly users might minimise when they meant to close then complain that they can't close it.

The latter point isn't so much of an issue on Windows/Linux where closing the media player will automatically close Syncplay, but on OSX that behaviour only works half the time in VLC for some reason. One potential workaround is simply to disable the 'minimise to tray' feature in OSX, or require that it be specifically enabled via a command line switch, but that might be overboard.

Whilst it *should* be the case that if you write it using QSystemTrayIcon that it'll work on all operating systems, that wasn't the case for menu bars which at the moment work for everything but OSX.

In terms of things that require the GUI when in GUI mode, if you want to toggle your 'ready' state while Syncplay is paused without unpausing then the only way to do this is via the GUI's "I'm ready to watch" pushbutton.

For Syncplay development I recommend PyCharm Community Edition.

**Comment by fermuch** [comment]
> Only cons I can think of is that it takes time to code (not an issue for me if you do it), and that some silly users might minimise when they meant to close then complain that they can't close it.

I am a silly user and I try to hide the window by pressing on the "close window" icon as I'm used to. Close to tray is not "weird" for a GUI.

> The latter point isn't so much of an issue on Windows/Linux where closing the media player will automatically close Syncplay, but on OSX that behaviour only works half the time in VLC for some reason. One potential workaround is simply to disable the 'minimise to tray' feature in OSX, or require that it be specifically enabled via a command line switch, but that might be overboard.

So we shouldn't add a feature because there's an unsolved bug?

> Whilst it should be the case that if you write it using QSystemTrayIcon that it'll work on all operating systems, that wasn't the case for menu bars which at the moment work for everything but OSX.

This may be a problem with PyQt. If this is the case, then I would (in the case I do write the code) open a ticket on PyQt and keep a separate branch with a trayicon until this problem is solved. Isn't this the ideal way?

> In terms of things that require the GUI when in GUI mode, if you want to toggle your 'ready' state while Syncplay is paused without unpausing then the only way to do this is via the GUI's "I'm ready to watch" pushbutton.

I understand your point of "you can use this app without a GUI", but it is no the desired way for some users. I'm not the only dummy user who tries to hide the GUI by click the close icon on the window.

> For Syncplay development I recommend PyCharm Community Edition.

Thanks.

**Comment by Et0h** [comment]
> So we shouldn't add a feature because there's an unsolved bug?

We should take into account that there is an unresolved issue that could cause issues for users.

> This may be a problem with PyQt. If this is the case, then I would (in the case I do write the code) open a ticket on PyQt and keep a separate branch with a trayicon until this problem is solved. Isn't this the ideal way?

Syncplay uses PySide rather than PyQT (for licensing reasons), and PySide is not under particularly active development, so if there is an issue that really is unresolvable within Syncplay then there is no point waiting for them to fix it, it would be better to develop a workaround.

I expect the menu bar issue could be resolved by an OSX developer, but it might require making a proper application package for OSX. Making such packages is something I have never done and couldn't even test.

**Comment by fermuch** [comment]
Now I understand the problem. Is it okay if I try to write it and, if I succeed and there are no compatibility issues, I create a PR?

After all, pyside gives an [example](https://github.com/PySide/Examples/blob/master/examples/desktop/systray/systray.py) of how to write a systray app.

**Comment by Et0h** [comment]
I'm not 100% sure what you intend to push. The "close window" icon/option should always close Syncplay by default, it should never minimise to tray.
