### ISSUE TITLE
Makefile installs desktop files with executable permissions

### ISSUE THREAD

**Issue by notpeelz** [Syncplay/syncplay#667]
**Describe the bug**
When installing syncplay, the desktop files get chmod-ed to 755. On my system (Arch Linux), syncplay is the only package that deploys desktop files with executable permissions.

`/usr/share/applications`:
![image](https://github.com/Syncplay/syncplay/assets/920910/233f8aa8-9133-4b35-b2fa-70e100e7e665)

**Expected behavior**
Permissions of 644, not 755. Desktop files aren't supposed to be executable.

**Version and platform:**
 - OS: Arch Linux
 - Syncplay version: [Syncplay 1.7.1](https://archlinux.org/packages/extra/any/syncplay/)

**Comment by daniel-123** [comment]
I've traced back the specific code that changes those permissions to a commit with several changes almost 10 years ago. There was no explanation why .desktop files needed executable permissions in it.

I see no reason not to change them to follow what all the other .desktop files do.
