### ISSUE TITLE
Ideas about Managed Rooms

### ISSUE THREAD

**Issue by co3xist** [Syncplay/syncplay#67]
Would it be possible to use the Syncplay server itself as an operator? I can't really do anything with the server (are there any commands at all?) and everything seems to be done clientside, which is an issue for me. I'm developing a web application that uses SyncPlay to start multiple rooms with different videos around the same time, and playing back all of those videos at the same time would be impossible for me.

After opening the SyncPlay server it would be great to be able to just run a command like "unpause <room>" to unpause playback for everyone.

Alternatively, would there be a way to use the Syncplay client CLI to connect, authenticate, unpause the room, and then leave without everyone's videos having a conniption? I tried this to little avail, video playback reset to zero repeatedly while the client tried to synchronize to an operator that was no longer there. 

I know this is likely an obscure request, but any input would be greatly appreciated.

**Comment by Uriziel** [comment]
It used to be possible with IRC API, but it was removed as nobody used it and it wasn't really working well. On the other hand if you explain fully what you want (can be on private if you need) I can provide you with a patch to the server that allows you to manage rooms with some kind of API
