### ISSUE TITLE
mpvSyncplaySocket created in $HOME

### ISSUE THREAD

**Issue by notpeelz** [Syncplay/syncplay#674]
**Describe the bug**
Since 459c9e91985796210fbc36968f8a6e572141f24f, a file named `mpvSyncplaySocket` is created in my home folder.

**Expected behavior**
On Linux, these kind of files would normally be created under `$XDG_RUNTIME_DIR`.
This env var might be undefined on non-systemd setups, in which case it should probably default to `$TMPDIR` (and fall back to `/tmp` if undefined).

Or as the [XDG Base Directory spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) puts it:
> `$XDG_RUNTIME_DIR` defines the base directory relative to which user-specific non-essential runtime files and other file objects (such as sockets, named pipes, ...) should be stored.

You can find more information about the standard file hierarchy (as defined by systemd) here: https://man7.org/linux/man-pages/man7/file-hierarchy.7.html

**Version and platform:**
 - OS: Arch Linux
 - Syncplay version: [Syncplay 1.7.2](https://archlinux.org/packages/extra/any/syncplay/)
 - Media player and version:  [MPV 0.37.0](https://archlinux.org/packages/extra/x86_64/mpv/)

**Comment by Et0h** [comment]
I use Windows rather than Linux so am not in a position to fix and test this, but hopefully someone can do so in a way that works on Linux and doesn't break anything on macOS or Windows.

**Comment by port19x** [comment]
So this is where these mystery files have been coming from
