### ISSUE TITLE
Cannot change video speed in MPV

### ISSUE THREAD

**Issue by jiang-yuan** [Syncplay/syncplay#684]
We both try to change video speed to 2X in MPV, but the video speed immediately reset to 1x.
We use 1.7.3 and 1.7.1 in win11.

**Comment by Et0h** [comment]
Hi, Syncplay does not currently support playback at different speeds.

For an explanation of why see previous discussions:
* https://github.com/Syncplay/syncplay/issues/406
* https://github.com/Syncplay/syncplay/issues/339

**Comment by jiang-yuan** [comment]
> Hi, Syncplay does not currently support playback at different speeds.
> 
> For an explanation of why see previous discussions:
> 
> * [[Feature Request] Ability to sync video speed #406](https://github.com/Syncplay/syncplay/issues/406)
> * [[suggestion] Possibility to increase playback speed #339](https://github.com/Syncplay/syncplay/issues/339)

This chrome extension allow player to adjust speed by each of themself [https://2gether.video/zh-cn/](url), but it allow supports play .mp4.
I think it only syncs the time but not the speed, which is easier to implement. Each player adjust the speed by them self to the same ratio manually. Is it enough for using.
The only different is that this extension does not force users player's speed to reset to 1x.
