### ISSUE TITLE
Playlist not loading even i've set the media directory

### ISSUE THREAD

**Issue by Arsks12** [Syncplay/syncplay#694]
idk am noticing nowadays when i load a file in playlist it stuck for a moment i mean the app then it disconnects and reconnect from the server now it does not load the file that i am adding in the playlist saying could not found the file in media directory even if it is i have to load the file manually in other words its not scanning files even in selected directories and its pretty annoying. 

am in windows 11 using 1.7.3

**Comment by Et0h** [comment]
Hi, I want some more information to understand the issue:
1) Roughly how many files are in your media directory?
2) Are the files on a local hard drive? If so, what type of hard drive?

**Comment by arifsk08** [comment]
> Hi, I want some more information to understand the issue:
> 
> 1. Roughly how many files are in your media directory?
> 2. Are the files on a local hard drive? If so, what type of hard drive?

its a ssd and its any folder even i try to use 1 folder containing 1 video it does make no problem after 10 15 min of scanning everything seems fine later but initial time it makes problem like this, what i mean by initial is if i restart my pc.

**Comment by Arsks12** [comment]
its getting stuck soo much these days getting not responding so much whenever we change video or try to add also nothing load even if it  in the media directory, am using ssd and there is not much video files 10 15 only, we always have to load video manually

**Comment by Et0h** [comment]
I would be interested to know if anyone else has experienced this issue as I have no idea why it has happening for you but seemingly nobody else.

What media player are you using and if you have multiple hard drives have you tried using a different drive as the media folder?

**Comment by Et0h** [comment]
PR #699 has now been merged into the main branch so hopefully this has resolved the issue. Please let me know if you continue to have any problems.

**Comment by Arsks12** [comment]
thank you so much!!!! the new update helped me a lot!!
