### ISSUE TITLE
"ImportError: No module named zope.interface"

### ISSUE THREAD

**Issue by timvermeulen** [Syncplay/syncplay#72]
I'm on OS X Yosemite, have followed all the instructions, and I do reach the Syncplay configuration screen. However, when trying to join a room, VLC never opens and I get the error

>ImportError: No module named zope.interface

Your official troubleshooting guide says

>the trick is go to into the installed zope module and add an empty __init__.py file in the zope directory

but this doesn't fix anything. The same error arises when trying the mvp player. Is there anything else I can try?

**Comment by timvermeulen** [comment]
Additional information: the zope directory was installed at

>/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python

and not at

>/usr/local/lib/python2.7/site-packages

**Comment by Et0h** [comment]
Try installing zope at /usr/local/lib/python2.7/site-packages

**Comment by timvermeulen** [comment]
Just did that (the first) and the same error message is shown. Following the suggestion of the troubleshooting guide still doesn't help, either.

**Comment by Uriziel** [comment]
Please check out this first:
http://stackoverflow.com/questions/11010412/importerror-no-module-named-zope-interface
https://github.com/kpdyer/fteproxy/issues/66
http://lmgtfy.com/?q=ImportError%3A+No+module+named+zope.interface+mac+os

**Comment by timvermeulen** [comment]
I tried all of that, and unfortunately, the error persists.

**Comment by timvermeulen** [comment]
Turns out, /usr/local/lib/python2.7/site-packages wasn't in PYTHONPATH, for some reason. Adding it fixed it.
