### ISSUE TITLE
Syncplay Version check

### ISSUE THREAD

**Issue by DerGenaue** [Syncplay/syncplay#75]
I still have Syncplay v.1.3.1 and although there already is v.1.3.3 Syncplay always tells me it's up to date.

Not true

(Probably just forgot to update server info?)

**Comment by Et0h** [comment]
We decided to leave it a bit before updating for those who were not already on the beta track to see if anyone reported any major bugs. They haven't so I have now set it to update everyone. :+1:

**Comment by DerGenaue** [comment]
Good idea, like with notepad++, etc...
Just maybe add it on the website, sth. like
"automatic updates will be triggered 1 week after if no bugs are reported"

**Comment by DerGenaue** [comment]
For the website:
You might want to advertise the language support in the sidebar ;)

**Comment by Et0h** [comment]
Good ideas. I have now updated the website to reflect the languages supported and the delay policy. I may also make it so that if you do a manual update check it tells you about the very latest version, even a beta.

**Comment by Et0h** [comment]
It now reports a new version is available (Syncplay 1.3.4 RC1) if someone on an earlier version does a manual update check.
