### ISSUE TITLE
Joining a room that's already watching something sets the time to 0

### ISSUE THREAD

**Issue by SirCmpwn** [Syncplay/syncplay#82]
Which is disruptive for everyone else. The new person should just skip to the timestamp everyone else is at.

**Comment by Et0h** [comment]
That shouldn't happen so is probably related to a bug in the Syncplay code for that media player. Which media player and version of Syncplay are they using?

**Comment by SirCmpwn** [comment]
Everyone involved was using mpv and syncplay 1.3.3.

**Comment by Et0h** [comment]
Did this occur when someone joined with no file? If so, that issue was hopefully fixed in Syncplay 1.3.4 as per http://syncplay.pl/changelog/

**Comment by SirCmpwn** [comment]
Yes, that was the case. Thanks!
