### ISSUE TITLE
Can't open files with unicode characters

### ISSUE THREAD

**Issue by minus7** [Syncplay/syncplay#84]
When opening a video file on Linux via `syncplay some☺file.mkv` (or via a .desktop file) the field has the file name decoded wrong. You see three characters representing the bytes of the unicode code point.

**Comment by Et0h** [comment]
Does https://github.com/Syncplay/syncplay/pull/85 fix your problem?

**Comment by minus7** [comment]
Yep. File name shows up correctly with that and it plays.
