### ISSUE TITLE
OS X: change "python2" menu bar title to "Syncplay"

### ISSUE THREAD

**Issue by blaenk** [Syncplay/syncplay#87]
Issue #86 fixes the menu bar on OS X, which is awesome, but it shows "python2" instead of "Syncplay" as the application title.

It looks like in order to change the application name from "python2" to something else, we need to edit some `Info.plist` file in the generated .app (if we're even generating one at the moment). [Source](http://stackoverflow.com/questions/7827430/setting-mac-osx-application-menu-menu-bar-item-to-other-than-python-in-my-pyth).

Alternatively, this [answer](http://stackoverflow.com/a/34161466/101090) in particular seems to go over packaging methods for python apps on OS X.

**Comment by nilsding** [comment]
This issue will be fixed once we manage to package Syncplay as an .app.  I'll take a look at generating one using _PyInstaller_.

**Comment by blaenk** [comment]
Yep. Check out the last link, the guy surveys a couple of options including PyInstaller.

**Comment by alby128** [comment]
Fixed by PR #150.
