### ISSUE TITLE
sometimes players don't pause

### ISSUE THREAD

**Issue by alok0** [Syncplay/syncplay#95]
I've seen this happen with mpv, vlc, and mpc, on both windows and linux.

Every once in a while (maybe 1 in a 1000 times), very rare, we will try and pause, but one of the players will stay in play, syncplay seems to notice that the time is off so it will move the player back to the correct time, but leave the the player in "play" so it just seems to loop the same 2-4 seconds over and over again.

**Comment by Et0h** [comment]
Thanks for reporting this. Two questions:
1) Are you using low, medium or high spec PCs?
2) Is this problem resolved by Tari's cookie system from #77 that has recently been added to Syncplay's sharedplaylist branch? (Might be a bit hard to test)

**Comment by alok0** [comment]
So, unfortunately I don't know how to replicate this, but if I ever have more info I'll add more. 

as for my pc, it is fairly high specd.
