### ISSUE TITLE
LUA file is installed still VLC is giving issue

### ISSUE THREAD

**Issue by ankmachine** [Syncplay/syncplay#96]
Hi,

My vlc is giving "syncplay.lua not found error" even thought syncplay.lua is installed in proper directory. 

![vlcissue](https://cloud.githubusercontent.com/assets/17567788/13425587/f1c0e226-dfcd-11e5-8a99-c13757c3c41c.jpg)
![vlcpathinstalled](https://cloud.githubusercontent.com/assets/17567788/13425588/f1cebc02-dfcd-11e5-91a5-ccd380d279a1.jpg)

**Comment by Et0h** [comment]
I only use Syncplay on Windows and most of the other developers only use Syncplay on Linux with mpv, but we'll do our best to get this to work...

1) What OS and version of VLC are you using?
2) What folder is cli.luac in? If it is a different folder, then use that folder.
3) Are the permissions/owner for syncplay.lua the the same as for cli.luac? If not, then try and make the syncplay.lua file have the same details

**Comment by Et0h** [comment]
See https://github.com/Syncplay/syncplay/issues/102
