### ISSUE TITLE
Fresh Install on Debian with mplayer - syncplayClient just quits after 'save config an start'

### ISSUE THREAD

**Issue by mokrates** [Syncplay/syncplay#99]
Fresh install of debian (stable, amd64) and mplayer (and the syncplay dependencies).
I push 'save config and play', the syncplay-play-windows appears (my friend, who I wanted to watch together with sees me arriving and leaving) and disappears instantly.
No error message.

VLC works, though.

**Comment by mokrates** [comment]
there are versions of mplayer which don't accept --hr-seek=always. says 'unrecognized option' and quits.
(the version from debian-multimedia. 3:1.1.1+20150226+svn37375-dmo5 doesn't work)

**Comment by daniel-123** [comment]
Lack of "--hr-seek=always" option is the reason for Syncplay not supporting mplayer in first place - as opposed to mplayer2 and mpv. This option allows for seeking to precise time, which is crucial for Syncplay to work sensibly. Old mplayer can only seek to nearest key frame.

In general though, mplayer has been forked to mplayer2 which in turn was forked to mpv. At this point of time there aren't really any reasons for typical user not to use the mpv with its richest feature set. It is avaliable in stock Debian from Jessie onwards.
